<div id="ajaxloading"></div>
<!-- 当前位置 /////////////////////////////////// -->
<div id="help_position"><a href="/help/">校友互助</a></div>

<!-- 提示 //////////////////////////////////////////// -->
<div class="sidebar">
    <div id="topic" class="help_on">
        <h2>提示 </h2>
        <!-- 提示表格 ///////////////////////////////////////////// -->

		    <table width="100%" border="0">
              <tr>
                <td>&nbsp;</td>
              </tr>
              <tr>
                <td><div align="center" class="fb14"><?= $this->message; ?></div></td>
              </tr>			  
              <tr>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td></td>
              </tr>
              <tr>
                <td></td>
              </tr>			  
            </table>        

    </div>
</div>

<!-- 待处理 ////////////////////////////////////////////// -->
<div class="sidebar">
    <table class="rightside_dot">
        <tr>
            <th class="txtl" colspan="2">待处理</th>
        </tr>
        <tr>
            <td><strong>·</strong><a href="" target="_blank" class="dot">待处理</a></td>
            <td></td>
        </tr>
    </table>
</div>
