<h2>添加信息分类</h2>
<div id="man">
<?php if($this->tips): ?>
  <p class="tips"><?= $this->tips ?></p>
  <?php endif; ?>
	<form method="POST">
		<p>显示图标 
		<select name="cate_icon" onchange="icon_show(this.value)" class="iconset">
		<?php 
			$iconDir = dir('../../public/static/images/icon/');
			while (false !== ($entry = $iconDir->read())): if(strstr($entry,'.gif')): 
		?>
			<option class="icon" value="<?= substr($entry,0,-4) ?>"><?= substr($entry,0,-4) ?></option>
		<?php
			endif; endwhile;
   		?>
		</select>
		<span id="iconinner"></span>
		<script>
			icon_show($('.icon:first').val());
		</script>
		</p>
		<p>
		分类名称 <input type="text" name="cate_name" size="40" />
		<input type="hidden" value="0" name="cate_pub" />
		<label for="cate_pub"><input type="checkbox" value="1" name="cate_pub" id="cate_pub" />在首页显示</a>
		<input type="submit" value="创建" />
		</p>
	</form>
</div>