<h2>添加新资讯</h2>

<div id='man'>
  <form method="POST">
  <?php if($this->tips): ?>
  <p class="tips"><?= $this->tips ?></p>
  <?php  endif; if(!$this->categories): ?>
  <p class="tips">您目前没有权限增加信息</p>
  <?php else: ?>
  <p>
  所属分类 <select name="cate_id">
  <?php foreach ($this->categories as $row): ?>
  	<option value="<?= $row->category_id ?>"<?php if($this->cate_id == $row->category_id) echo 'selected="selected"' ?>>
  	<?php echo $row->category_name ?>
  	</option>
  <?php endforeach; ?>
  </select>
  发布时间 <input type="text" name="pub_time" value="<?php if(!$this->pub_time) echo Commons::date(); else echo $this->pub_time; ?>" size="40" />
  <input type="hidden" name="top" value="0" />
  <input type="checkbox" name="top" value="1"<?php if($this->row->entity_top == 1): ?> checked="checked"<?php endif;?> /> 顶置
  </p>
  <p>
  标题 <input type="text" name="title" value="<?= $this->title ?>" size="80" /> 
  </p>
  <p>
  标签 <input type="text" name="tag[]" size="6" value="<?= $this->tag ?>" /><span class="tag_inner"></span>
  <a href="javascript:add_tag()">增加</a>
  </p>
  <?php endif; ?>
  <textarea name="content" id="content" style="display:none;"><?= $this->content ?></textarea>
  <?= $this->editor(); ?>
  <p style="text-align:center"><input type="submit" value="提交新信息" style="padding:5px 10px; font-size:14px; border:3px double #aaa; cursor:pointer; background:#ffc;" /></p>
  </form>
</div>