<div id="footer_decoration">&nbsp;</div>

<table id="footer">
	<tr>
		<td class="sub_nav">
			<a href="/info/support/help">帮助</a> | 
			<a style="color:red" target="_blank" href="http://v2.zjuhz.com/public/index/doc/of/aboutus">关于本会</a> | 
			<a target="_blank" href="http://v2.zjuhz.com/addon_partners/list">赞助单位</a> | 
			<a href="/info/support/contact_us">联系我们</a> | 
			<a href="/info/support/privacy_claim">隐私声明</a> | 
			<a href="http://www.zjuhz.com/old" target="_blank">旧版回顾</a> | 
			<a href="http://ourzju.uu1001.com" target="_blank">校友论坛</a>
		</td>
		<td class="sub_info">
			杭州浙江大学校友会 &copy; 2008 
			<a href="http://www.miibeian.gov.cn" target="_blank">浙ICP备08109401号</a>
			<script type="text/javascript" src="http://js.tongji.cn.yahoo.com/705170/ystat.js"></script><noscript><a href="http://tongji.cn.yahoo.com"><img src="http://img.tongji.cn.yahoo.com/705170/ystat.gif"/></a></noscript>
		</td>
	</tr>
</table>