<div id="footer_decoration">&nbsp;</div>

<table id="footer">
	<tr>
		<td class="sub_nav">
			<a href="">帮助</a> | 
			<a href="/info/support/about">关于</a> | 
			<a href="/info/support/contact_us">联系我们</a> | 
			<a href="/info/support/privacy_claim">隐私声明</a> | 
			<a href="http://www.zjuhz.com/old" target="_blank">旧版回顾</a> | 
			<a href="http://ourzju.uu1001.com" target="_blank">校友论坛</a>
		</td>
		<td class="sub_info">
			杭州浙江大学校友会(筹) &copy; 2008 
			<a href="http://www.miibeian.gov.cn" target="_blank">浙ICP备06052510号</a>
		</td>
	</tr>
</table>