<form method="POST">
<input class="input" type="text" onmouseover="this.style.borderColor='#666'" onmouseout="this.style.borderColor='#ccc'" onfocus="input_focus('input')" onblur="input_blur('input','在zjuhz.com中查找')" value="在zjuhz.com中查找" />
<input class="btn" type="submit" value="搜索" /> 
<?php if($this->modelName == 'help'): ?>
<input class="btn" type="submit" value="提问" /> 
<?php endif ?>
</form>