<?php // 是否为当前班级的管理人员
	$charge = false;
	foreach ($this->class as $k => $v)
	{
		if($v['class_id'] == $this->class_id)
		{
			if($v['class_charge'] == 1 || $v['class_member_charge'] == 1)
			$charge = true;
		}
	}
	if($charge == true):
?>
<!-- 管理员部分 -->
<a href=""><img src="/static/images/icon/lock.gif" /> 隐私控制</a>
<a href=""><img src="/static/images/icon/chart_pie.gif" /> 空间管理</a>
<a href=""><img src="/static/images/icon/group.gif" /> 成员管理</a>

<?php endif; ?>

<a href=""><img src="/static/images/icon/user.gif" /> 邀请同学</a>
<a href=""><img src="/static/images/icon/email.gif" /> 群发邮件</a>
<a href=""><img src="/static/images/icon/book.gif" /> 班级通讯录</a>