<table class="global_search">
<tr>
<!-- 状态信息 /////////////////////////////////////////// -->
	<td class="nav">
    <?php if ($this->login) { ?>
		您好 , <?= $this->login['realName'] ?> | 
		<?php if(false != DbModel::hasClass($this->login['uid'])) :?> <a href="/class/home">我的班级</a></a> | <?php endif; ?> 
		<a href="">站内信<?= ($this->login['unRead'] > 0) ? "({$this->login['unRead']})" : ''; ?></a> | <a href="/member/logout/" onClick="return window.confirm('确实要退出吗？');">退出</a>
	<?php }	else { ?>
		<a href="/member/register/">注册</a>|<a href="/member/login/">登录</a>
	<?php } ?>
	</td>
</tr>
</table>
<table class="global_search">
	<tr>
	<!-- 模块选择 /////////////////////////////////////////// -->
	<td class="models">
	<a href="/member/">校友</a>
	<a href="/info/">资讯</a>
	<a href="/help/">互助</a>
	<a href="/class/" class="on">班级</a>
	<a href="#">群组</a>
	<a href="#">活动</a>
	<a href="#">相册</a>
	</td>
	</tr>
	<tr>
	<td class="search_form" colspan="2">
	<!-- 搜索框 /////////////////////////////////////////// -->
	<form method="GET" action="/class/search">
	<input type="hidden" name="year" value="<?= $this->year ?>" />
	<input type="hidden" name="college" value="<?= $this->college ?>" />
<input class="input" name="for" type="text" onmouseover="this.style.borderColor='#666'" onmouseout="this.style.borderColor='#ccc'" onfocus="input_focus('input')" onblur="input_blur('input')" value="<?= $this->keywords ?>" />
<input class="btn" type="submit" value="搜索" /> 
</form>
	</td>
	</tr>
</table>