
<div class="span-5">
    <div class="sideBar">
        <?= $this->sortbar(); ?>
    </div>
</div>

<div class="span-19 last">
    <div class="oneCol pd10">
        <h3>群组活动 <span class="f12">(找到<?= $this->numrows ?>个)</span></h3>
        <p style="float:right; margin-top:-35px;">
            <a href="/group/events/list" <?= ($this->where == null)?'style="font-weight:bold"':'' ?>>所有活动</a> , 
            <a href="/group/events/list?where=join" <?= ($this->where == 'join')?'style="font-weight:bold"':'' ?>>我参与的</a> ,
            <a href="/group/events/list?where=founder" <?= ($this->where == 'founder')?'style="font-weight:bold"':'' ?>>我发起的</a>
            <button onclick="location.href='/group/events/create'" class="btn">发起新活动</button>
        </p>
        <table class="table-1" width="100%">
            <tr>
                <th class="txtl" width="35%">标题</th>
                <th class="txtc" width="15%">状态(人数)</th>
                <th class="txtc" width="20%">报名截止</th>
                <th class="txtc" width="20%">活动开始</th>
                <th class="txtc" width="10%">发起人</th>
            </tr>
            <?php if($this->rows): foreach($this->rows as $row): ?>
            <tr>
                <td class="pd10 dashBorder">
                    <a href="/group/events/show?eid=<?= $row->event_id ?>">
                        <?= $row->title ?>
                        <?php if($row->sign_close > time()): ?>
                        (接受报名中)
                        <?php endif; ?>
                    </a>
                </td>
                <td class="txtc dashBorder">
                    <?php if($row->event_start > time()): //没有开始 ?>
                    <span style="color:green">未开始</span>
                    <?php elseif($row->event_close > time()): // 进行中 ?>
                    <span style="color:orange">进行中</span>
                    <?php else: // 结束 ?>
                    <span style="color:red">已结束</span>
                    <?php endif; ?>
                    (<?= $row->member_num ?>)
                </td>
                <td class="quiet txtc dashBorder">
                    <?php if($row->sign_close > time()): ?>
                    <?= Lp_Date::timespan(time() - ($row->sign_close - time())); ?>后
                    <?php else: ?>
                    <?= Lp_Date::timespan($row->sign_close) ?>前
                    <?php endif; ?>
                </td>
                <td class="quiet txtc dashBorder">
                    <?php if($row->event_start > time()): ?>
                    <?= Lp_Date::timespan(time() - ($row->event_start - time())); ?>后
                    <?php else: ?>
                    <?= Lp_Date::timespan($row->event_start) ?>前
                    <?php endif; ?>
                </td>
                <td class="txtc dashBorder">
                    <a onclick="location.href='/group/member/profile?uid=<?= $row->founder ?>'" href="javascript:ucard(<?= $row->founder ?>)"><?= UserModel::fetch($row->founder, 'realName') ?></a>
                </td>
            </tr>
            <?php endforeach; else: ?>
            <tr>
                <td colspan="5" class="pd10">没有活动</td>
            </tr>
            <?php endif; ?>
        </table>
        <div class="pagination"><?= $this->pagination ?></div>
    </div>
</div>