<table class="table" cellpadding="0" cellspacing="0" style="background:#fff; border:none;" width="100%">
    <tr>
        <th width="50%">企业名称</th>
        <th width="40%">提交申请时间</th>
        <th width="10%">状态</th>
    </tr>
<?php foreach ($this->companies as $value) { ?>
    <tr>
        <td><?= $value['name']; ?></td>
        <td><?= $value['regTime']; ?></td>
        <td>等待审核</td>
    </tr>
<?php } ?>
</table>

<?php if (!$this->companies) { ?>
<table width="100%" border="0" cellspacing="0" cellpadding="1" class="tx_box">
    <tr>
        <td width="60" rowspan="2"><img src="/static/images/icon/edit-b.gif" /></td>
        <td class="tx_title"><b>共有 0 个企业资料审核中！</td>
    </tr>
    <tr>
        <td class="tx_content"><a href="/company/my/company/type/join/">现在就去提交新的企业加入申请 >></a></td>
    </tr>
</table>
<?php } ?>