<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="imagetoolbar" content="no" />
<title><?php echo $this->header_title ?> - 浙江大学校友会 - zjuhz.com</title>
<script type="text/javascript" src="/static/scripts/jquery.js"></script>
<script type="text/javascript" src="/static/scripts/home.js"></script>
<link rel="stylesheet" type="text/css" href="/static/styles/home.css" media="screen" />
</head>

<body>
	<div id="wrap">
	
		<div id="header">
			<a href="/" id="logo">
				<b>zjuhz.com</b>
				<p>杭州浙江大学校友会</p>
			</a>
			
			<form method="post">
			<table id="mini_search">
				<tr>
					<td class="tips">您目前的身份是游客,更多精彩请登陆~</td>
					<td class="lbg"></td>
					<td class="mbg"><input type="text" value="搜索 zjuhz.com" onfocus="search_focus('mbg')" onblur="search_blur('mbg','搜索 zjuhz.com')" /></td>
					<td class="mbg"><a href="javascript:"></a></td>
					<td class="rbg"></td>
				</tr>
			</table>
			</form>
		</div>