<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <title><?php echo $this->header_title ?> - 杭州浙江大学校友会信息平台管理</title>
  <link rel="stylesheet" type="text/css" href="/static/styles/info_console.css" media="screen" />
  <script type="text/javascript" src="/static/scripts/jquery.js"></script>
  <script type="text/javascript" src="/static/scripts/common.js"></script>
  <script type="text/javascript" src="/static/scripts/info/action.js"></script>
</head>

<body>