<table id="global_search">
	<tr>
	<!-- 模块选择 /////////////////////////////////////////// -->
	<td class="models">
	<a href="/info/" class="on">资讯</a>
	<a href="/help/">互助</a>
	<a href="/class/">班级</a>
	<a href="/group/">群组</a>
	<a href="/blog/">博客</a>
	<a href="/photo/">相册</a>
	</td>
	<!-- 状态信息 /////////////////////////////////////////// -->
	<td class="nav">
	欢迎：<a href=""><?php echo $this->realName ?></a>
<a href="">站内信<?php echo ($this->unRead > 0) ? "({$this->unRead})" : ''; ?></a>
<a href="/member/login/dologout/" onClick="return window.confirm('确实要退出吗？');">退出</a>
	</td>
	</tr>
	<tr>
	<td class="search_form" colspan="2">
	<!-- 搜索框 /////////////////////////////////////////// -->
	<form method="POST">
<input class="input" type="text" onmouseover="this.style.borderColor='#666'" onmouseout="this.style.borderColor='#ccc'" onfocus="input_focus('input')" onblur="input_blur('input')" value="" name="keywords" id="keywords" />
<input class="btn" type="submit" value="搜索" /> 
</form>
	</td>
	</tr>
</table>