<table id="global_search">
	<tr>
	<!-- 模块选择 /////////////////////////////////////////// -->
	<td class="models">
	<a href="/info/" class="on">资讯</a>
	<a href="/help/">互助</a>
	<a href="/class/">班级</a>
	<a href="/member/">校友</a>
	<a href="/blog/">日志</a>
	<a href="/play/">活动</a>
	</td>
	<?php if($this->role != 'member'): ?>
	<!-- 未登陆 /////////////////////////////////////////// -->
	<td class="nav">
	尚未登陆,<a href="">登陆</a>
	</td>
	<?php else: ?>
	<!-- 登陆后 /////////////////////////////////////////// -->
	<td class="nav">
	欢迎：<a href=""><?= $this->login['realName'] ?></a>
<a href="">站内信<?= ($this->login['unRead'] > 0) ? "({$this->login['unRead']})" : ''; ?></a>
<a href="/member/login/dologout/" onClick="return window.confirm('确实要退出吗？');">退出</a>
	</td>
	<?php endif; ?>
	</tr>
	<tr>
	<td class="search_form" colspan="2">
	<!-- 搜索框 /////////////////////////////////////////// -->
	<form method="POST">
<input class="input" type="text" onmouseover="this.style.borderColor='#666'" onmouseout="this.style.borderColor='#ccc'" onfocus="input_focus('input')" onblur="input_blur('input')" value="" name="keywords" id="keywords" />
<input class="btn" type="submit" value="搜索" /> 
</form>
	</td>
	</tr>
</table>