<?= $this->render('home/index.phtml'); ?>
<!-- 管理条目 ///////////////////////////////////// -->
<div class="sidebar" style="width:160px">
<p class="toolbar">
<a href="/class/home?c=<?= $this->class_id ?>"><img src="/static/images/icon/arrow_undo.gif" /> 返回</a>
</p>
</div>

<div class="sidebar class_show" style="width:500px; padding:0 10px;">
<h2 class="quiet"><img src="/static/images/icon/group.gif" /> 成员列表</h2>
<table class="class_list" style="width:100%; margin-left:0">
<tr class="quiet">
<th>班级成员</th>
<th>身份</th>
<th>最后登录<input type="hidden" name="class_id" value="<?= $this->class_id ?>" /></th>
</tr>
<?php foreach ($this->members as $k=>$v): ?>
<tr>
<td><a target="_blank" href="/group/member/profile?uid=<?= $v['class_member_id'] ?>"><?= $v['realName'] ?></a></td>
<td><?php 
	if($v['class_member_charge'] == 1) echo '管理员'; 
	elseif($v['class_charge'] == $v['class_member_id']) echo '创建人'; 
	else echo '成员' ?></td>
<td class="quiet f9"><?= $v['class_member_last_access'] != '' ? Commons::date($v['class_member_last_access']) : '未登录过' ?>
</td>
</tr>
<?php endforeach; ?>
</table>
</div>

<!-- 班级基本信息 ///////////////////////////////////////// -->
<?= $this->render('home/baseinfo.phtml'); ?>