<div class="oneCol">
    <h3 class="mglf10"><?= Cmd::icon('coins.png') ?> 校友创业</h3>
	<table width="95%" class="mglf10">
		<tr>
			<td class="pd5 vm" style="width:5px; font-weight:bold">
                <a href="http://www.zjuhz.com/group/home/name/of/venture" style="color:#186DA9; text-decoration:none">
					创业俱乐部</a>
            </td>
			<td class="list-2">
                <ul class="f14">
                    <?php
                    $topics = $this->Group->getTopicFrom(10, 5);
                    foreach($topics as $t): ?>
                    <li><a title="<?= $t['title'] ?>" href="/group/topic/show?gid=10&tid=<?= $t['topic_id'] ?>">
                        <?= Commons::utfSubStr($t['title'],40).'..' ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </td>
		</tr>
        <tr>
            <td class="pd5 vm" style="border-top:1px solid #D7E4EC; width:5px; font-weight:bold">
                <a href="/biz/" style="color:#186DA9; text-decoration:none">校友企业</a>
            </td>
            <td style="border-top:1px solid #D7E4EC" class="list-2 pdu10">
                <ul class="f14">
                    <?php
                    $bizs = $this->Biz->get(3);
                    foreach($bizs as $b): ?>
                    <li><a title="<?= $b['name'] ?>" href="/biz/detail/index/cid/<?= $b['topic_id'] ?>">
                        <?= $b['name'] ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </td>
        </tr>
	</table>
</div>