<div class="mgu10">     
        <ul class="mglf10">
            <h3 class="quiet"><?= Cmd::icon('bricks.png') ?> 网站开发进度</h3>
            <li><?= Cmd::icon('bug_delete.png') ?> 群组站内信批量清除/删除</li>
            <li><?= Cmd::icon('bug_delete.png') ?> 群组邀请函部分错误</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组相册投入使用</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组自定义标志</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 我的群组增加好友列表</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 完成群组搜索邀请</li>
            <li><?= Cmd::icon('bug_delete.png') ?> 群组主题回复无效</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 成员可退出群组</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组个人资料补充</li>
        </ul>
    </div>