<div class="mgu10">     
        <ul class="mglf10">
            <h3 class="quiet"><?= Cmd::icon('bricks.png') ?> 网站开发进度</h3>
            <li><?= Cmd::icon('plugin_add.png') ?> 校友会公共聊天室</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组搜索</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组成员列表</li>
            <li><?= Cmd::icon('bug_delete.png') ?> 群组主题发布自动跳转</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 默认保存登录信息</li>
            <li><?= Cmd::icon('bug_delete.png') ?> 群组站内信批量清除/删除</li>
            <li><?= Cmd::icon('bug_delete.png') ?> 群组邀请函部分错误</li>
        </ul>
    </div>