<div class="sideBar list-1 mgu10">
    <ul class="mglf10">
            <h3 class="tt">校友助手</h3>
            <ul>
                <li><a class="lk-1" target="_blank" href="http://test.zjuhz.com/psetup1584508.exe">“杭州浙大校友会”版360安全卫士</a></li>
                <li><a class="lk-1" target="_blank" href="http://www.jpskb.com/down.htm">火车公交时刻表</a></li>
                <li><a class="lk-1" target="_blank" href="http://www.zjuhz.com/info/view/detail/id/184">网站排名查询工具条</a></li>
                <li><a class="lk-1" target="_blank" href="http://count.ecgoods.com">网站流量统计系统</a></li>
                <li><a class="lk-1" target="_blank" href="http://ip138.com">IP地址查询</a></li>
            </ul>
        </ul>
</div>