<div class="sideBar list-1 mgu10">     
        <ul class="mglf10">
            <h3 class="tt">专题</h3>
            <li><a class="lk-1" target="_blank" href="http://www.zjuhz.com/info/view/detail/id/673">浙江大学校友活动落幕 杭州校友会正式启航</a></li>
            <li><a class="lk-1" target="_blank" href="http://www.zjuhz.com/info/view/detail/id/186">杭州校友会筹备工作一览</a></li>
            <li><a class="lk-1" href="/info/subject/index/of/qiushixungen-jiangxi">浙江大学求是寻根 - 江西段</a></li>
        </ul>
    </div>