<?php $rows = $this->Group->getNewTopic(); ?>
<table class="table-1" width="100%">
    <th>
		<strong class="f14">群组新帖</strong> 
	</th>
	<th width="20%" class="txtc">发布时间</th>
    <?php foreach($rows as $r): ?>
    <tr>
        <td class="f12 pd5 dashBorder txtl">[<a style="color:#666" href="/group/home?gid=<?= $r['group_id'] ?>"><?= $r['group_name'] ?></a>]<a href="/group/topic/show?gid=<?= $r['group_id'] ?>&tid=<?= $r['topic_id'] ?>"><?= stripslashes($r['title']) ?></a></td>
        <td class="quiet dashBorder txtc"><?= date('y-m-d',$r['pub_time']) ?></td>
    </tr>
    <?php endforeach; ?>
</table>
