<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>08年9月20日杭州浙江大学校友会成立大会</title>
<script type="text/javascript" src="/static/scripts/jquery.js"></script>
<script type="text/javascript" src="/static/scripts/jquery.cookie.pack.js"></script>
<script type="text/javascript" src="/static/scripts/common.js"></script>
<link rel="stylesheet" type="text/css" href="/static/styles/group/subject/found.css">
</head>
<body>
    <div id="container">
        <div id="header"></div>
        <div id="nav">
            <a class="plan" href="javascript:tab('plan')"><img src="/static/images/icon/date.gif" /> 成立大会活动安排</a>
            <a class="signup" href="javascript:tab('signup')"><img src="/static/images/icon/edit.gif" /> 在线订票</a>
            <a class="ls_intro" href="javascript:tab('ls_intro')"><img src="/static/images/icon/user.gif" /> 理事成员简介</a>
            <a class="zh_intro" href="javascript:tab('zh_intro')"><img src="/static/images/subject/found/photo/user_gray.gif" /> 校友总会老师简介</a>
            <a class="cb_intro" href="javascript:tab('cb_intro')"><img src="/static/images/icon/group.gif" /> 筹备组成员简介</a>
        </div>
        <div id="content">
            <div style="margin:20px; font-size:14px;" id="loading" class="error txtc">内容加载中请稍等...</div>
            <?php if($this->listview): // 已经报名的人员 ?>
            <div class="pdlr10">
            <h2>已经报名参加的人员 <a target="_blank" href="/group/subject/found?list=view&export=xls">导出Excel</a></h2>
            <ol style="list-style-position:inside">
            <?php foreach($this->listview as $uid => $data): ?>
            <li><?= $uid ?>:<?= $data['name'] ?>/<?= $data['email'] ?>/<?= $data['mobile'] ?></li>
            <?php endforeach; ?>
            </ol>
            </div>
            <?php else: ?>
            <div id="plan" class="item">
                <div class="notice" style="font-size:13px; text-align:left; font-weight:normal">
                        <b>9月16号</b>将开通四个<b>现场取票点</b>，地址和联系方式如下：<br />
                        城西：西溪路525号浙大科技园C楼608杭州浙大校友会(89988185)<br />
                        城北：莫干山路789号美都广场C座612室浙江建林电子电气有限公司(88979740)<br />
                        城中：庆春路216号浙江省卫生厅二楼长江证券营业部(87709267)<br />
                        滨江：滨江区江南大道3880号华荣时代大厦16楼D座浙江凯富律师事务所(87859355)<br />
                        <b style="color:red">通知：已经在线订票还没领票的校友可以20号直接到活动现场取票(时间：下午2点之前，地点：浙大紫金港小剧场)</b>
                    </div>
                <div class="pdlr10">
                    <h2>活动概述 <span style="font-size:14px;">2008年9月20日（周六）下午13:30—21:00</span></h2>
                    <table width="80%" class="table" style="margin:20px auto;">
                        <tr>
                            <th>参考地图(点击可放大)</th>
                            <th>安排</th>
                            <th>地点</th>
                        </tr>
                        <tr>
                            <td rowspan="5" align="center">
                                <a target="_blank" href="/static/images/subject/found/map.jpg"><img 

src="/static/images/subject/found/map-small.jpg" /></a>
                            </td>
                            <td>报到，会议和音乐会</td>
                            <td>浙大紫金港校区，小剧场</td>
                        </tr>
                        <tr>
                            <td>会展参观</td>
                            <td>浙大学生活动中心</td>
                        </tr>
                        <tr>
                            <td>游园</td>
                            <td>紫金港校区，南华园</td>
                        </tr>
                        <tr>
                            <td>用餐</td>
                            <td>学生食堂</td>
                        </tr>
                    </table>
                    <h2>一、成立大会</h2>
                    <table width="80%" class="table" style="margin:20px auto;">
                        <tr>
                            <th>序号</th>
                            <th>内容</th>
                            <th>地点</th>
                        </tr>
                        <tr>
                            <td><div align="center">1</div></td>
                            <td><div align="center">校友签到，领会议资料</div></td>
                            <td rowspan="2"><div align="center">紫金港校区小剧场</div></td>
                        </tr>
                        <tr>
                            <td><div align="center">2</div></td>
                            <td><div align="center">杭州校友会成立大会</div></td>
                        </tr>
                    </table>
                    <h2>二、参观展览</h2>
                    <table width="80%" class="table" style="margin:20px auto;">
                        <tr>
                            <th width="15%">序号</th>
                            <th>内容</th>
                            <th>地点</th>
                        </tr>
                        <tr>
                            <td><div align="center">3</div></td>
                            <td>
                                <div align="center">“浙江大学校史展”（毕业20年以上校友值得重温）<br />
                          </div></td>
                            <td><div align="center">校史馆(学生活动中心二楼,小剧场对面)</div></td>
                        </tr>
                        <tr>
                          <td><div align="center">4</div></td>
                          <td><div align="center">“浙江大学本科生创新成果展”（孩子的最爱）</div></td>
                          <td><div align="center">展馆(学生活动中心一楼,小剧场对面)</div></td>
                        </tr>
                        <tr>
                          <td><div align="center">5</div></td>
                          <td><div align="center">“浙江大学科技创新成果展”(创业校友、企业家值得关注)</div></td>
                          <td><div align="center">展馆(学生活动中心一楼,小剧场对面)</div></td>
                        </tr>
                    </table>
                    <h2>三、晚餐</h2>
                    <table width="80%" class="table" style="margin:20px auto;">
                        <tr>
                            <th width="15%">序号</th>
                            <th>内容</th>
                            <th width="15%">地点</th>
                        </tr>
                        <tr>
                            <td><div align="center">6</div></td>
                            <td>
                               <div align="center">晚餐</div></td>
                            <td><div align="center">学生食堂</div></td>
                        </tr>
                    </table>
                    <h2>四、欣赏晚会</h2>
                    <table width="80%" class="table" style="margin:20px auto;">
                        <tr>
                            <th width="15%">序号</th>
                            <th>内容</th>
                            <th width="15%">地点</th>
                        </tr>
                        <tr>
                            <td><div align="center">7</div></td>
                            <td>
                               <div align="center">“庆祝新浙大成立十周年暨杭州浙江大学校友会成立晚会”
                            (文琴艺术团)</div></td>
                            <td><div align="center">小剧场</div></td>
                        </tr>
                    </table>
                    <h2>五、安全返回</h2>
                    <table width="80%" class="table" style="margin:20px auto;">
                        <tr>
                            <th width="15%">时间</th>
                            <th>内容</th>
                            <th width="15%">地点</th>
                        </tr>
                        <tr>
                            <td>20：30-21：00</td>
                            <td>
                               五辆校车（小剧场门口），送校友，活动结束。
                            </td>
                            <td>小剧场</td>
                        </tr>
                    </table>
                    <h2>校车接送路线</h2>
                    <p style="padding:20px;">
                        <b>校车A：</b>紫金港小剧场 - 古墩路 - 天目山路 - 古荡 - 玉泉校区主席像前<br />
                        <b>停靠：</b>政苑小区、金田花园、古荡公交站、玉泉校区北门、主席像
                    </p>
                    <p style="padding:20px;">
                        <b>校车B：</b>紫金港小剧场 - 古墩路 - 文一路 - 教工路 - 西溪校区门口<br />
                        <b>停靠：</b>政苑小区、雅仕苑、益乐新村、物美、杭师大、伟星大厦、西溪校区
                    </p>
                    <p style="padding:20px;">
                        <b>校车C：</b>紫金港小剧场 - 古墩路 - 文二路 - 学院路 - 西溪校区 - 武林小广场<br />
                        <b>停靠：</b>政苑小区、紫桂花园、南都德加、翠苑五区、颐高、西溪校区、武林小广场
                    </p>
                    <p style="padding:20px;">
                        <b>校车D：</b>紫金港小剧场 - 丰潭路 - 文三路 - 学院路 - 西溪校区 - 保叔路 - 省府路 - 金衙庄 - 城站<br />
                        <b>停靠：</b>政苑小区、天湖公寓、古荡新村、天苑大厦、八字桥、沿山河社区、省府大楼、庆春路、金衙庄、城站火车站
                    </p>
                    <p style="padding:20px;">
                        <b>校车E：</b>紫金港小剧场 - 丰潭路 - 天目山路 - 西溪校区 - 武林小广场 - 延安路 - 凤起路 - 红会医院<br />
                        <b>停靠：</b>政苑小区、天湖公寓、国力大酒店、古荡公交站、西溪校区、八字桥、武林小广场、延安新村、外文书店、杭高、红会医院

                    </p>
                </div>
            </div>
    
            <div id="signup" class="item">
                <div class="pdlr10">
                    <?php if(!$this->passport()): ?>
                    <form method="post" id="relogin_form" onsubmit="return relogin();">
                        <table id="login_form">
                            <tr>
                                <td class="txtr vm">登录账号：</td>
                                <td><input class="text" name="uname" type="text" maxlength="16" value="<?= $this->uname; ?>" 

/></td>
                            </tr>
                            <tr>
                                <td class="txtr vm">登录密码：</td>
                                <td><input class="text" name="pswd" type="password" maxlength="16" value="<?= $this->pswd; ?>" 

/></td>
                            </tr>
                            <tr>
                                <td class="txtr vm">下次自动登录：</td>
                                <td><input id="alive" type="checkbox" value="0" <?= ($this->uname) ? 'checked="checked"':'' ?> 

name="alive" /></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><p class="txtr"><input style="width:100%" class="btn" id="btnLogin" type="submit" value="登 录" 

/></p></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="sub f14"><p>没有帐号？
                                <a target="_blank" href="/member/register/">创建新帐号</a></p></td>
                            </tr>
                        </table>
                    </form>
                    <?php else: ?>
                    
                    <h2 style="text-align:center">
                        前<span style="color:red">200</span>张邮寄票已经全部抢完！
                        还剩余<span style="color:red"><?= ($this->last < 0) ? 0 : $this->last ?></span>张可以在线订票
                    </h2>
                    <br />
                    <div class="notice" style="font-size:13px; text-align:left; font-weight:normal">
                        <b>9月16号</b>将开通四个<b>现场取票点</b>，地址和联系方式如下：<br />
                        城西：西溪路525号浙大科技园C楼608杭州浙大校友会(89988185)<br />
                        城北：莫干山路789号美都广场C座612室浙江建林电子电气有限公司(88979740)<br />
                        城中：庆春路216号浙江省卫生厅二楼长江证券营业部(87709267)<br />
                        滨江：滨江区江南大道3880号华荣时代大厦16楼D座浙江凯富律师事务所(87859355)<br />
                        <b style="color:red">已经在线订票还没领票的校友可以20号直接到活动现场取票(时间：下午2点之前，地点：浙大紫金港小剧场)</b>
                    </div>
                
                    <?php if($this->signup == true): ?>
					<div class="success">
                        您已经成功预定No.<?php echo $this->t_start; if($this->t_start != $this->t_end) echo '~'.$this->t_end ?>张票
                        (前200张我们会将票邮寄至您所填地址)
                        门票数量有限，请珍惜。同时欢迎邀请其他校友访问本网页订票。
                    </div>
                    <?php endif; ?>
                    
                    <?php if($this->last >= 1 || $this->signup == true): ?>
                    <form id="sign_form" onsubmit="return signup();">
                        <input name="uid" type="hidden" value="<?= $this->passport('uid') ?>" />
                        <table style="margin:0 auto; text-align:center">
                            <tr>
                                <td>姓名&nbsp;</td>
                                <td><input readonly="true" class="text" type="text" name="name" value="<?= $this->passport

('realName') ?>" /></td>
                            </tr>
                            <tr>
                                <td>邮箱&nbsp;</td>
                                <td><input class="text" type="text" id="email" name="email" value="<?= $this->passport('eMail') ?>" 

/></td>
                            </tr>
                            <tr>
                                <td>手机&nbsp;</td>
                                <td><input class="text" type="text" id="mobile" name="mobile" value="<?= $this->passport('mobile') 

?>" /></td>
                            </tr>
                           	<tr>
                                <td>入学年份&nbsp;</td>
                                <td align="left">
                                	<select name="year" id="year"><option>入学年份</option><?php for ($i=1940;$i<=2008;$i++) { 

?><option <?= ($i == $this->passport('year') ? 'selected' : ''); ?> value="<?= $i; ?>"><?= $i; ?>年</option><?php } ?></select>
                                </td>
                            </tr>
                            <tr>
                                <td>专业&nbsp;</td>
                                <td><input class="text" type="text" id="major" name="major" value="<?= $this->passport('major') ?>" 

/></td>
                            </tr>
                            <tr>
                            	<td>住址&nbsp;</td>
                            	<td><input class="text" type="text" id="address" name="address" value="<?= $this->passport

('address') ?>" /></td>
                            </tr>
                            <tr>
                            	<td>票数&nbsp;</td>
                            	<td align="left">
                            		<select name="tnum">
                            			<option value="1" <?= ($this->tnum == 1)?'selected="selected"':'' ?>>1张 </option>
                            			<option value="2" <?= ($this->tnum == 2)?'selected="selected"':'' ?>>2张 </option>
                            			<option value="3" <?= ($this->tnum == 3)?'selected="selected"':'' ?>>3张 </option>
                            		</select>
                            	</td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>
                                	<?php if($this->signup != true): ?>
                                	<input class="btn" type="submit" value="信息无误，我要订票" />
                                	<?php else: ?>
                                	<input class="btn" type="submit" value="修改信息" />
                                	<?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" id="sign_tip"></td>
                            </tr>
                        </table>
                    </form>
                    <?php else: ?>            
                    <div class="notice">在线预票活动结束...您可以通过现场取票方式参加校友会成立大会的活动。(取票地点请参考上面的联系方式)</div>
                    <?php endif; endif; ?>
                </div>
            </div>
                
            <div id="ls_intro" class="item">
                <div class="pdlr10">
                    <?php if($this->passport()): ?>
                    <h2>荣誉会长</h2>
                    <table>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image001.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">张浚生</h3>
                                1958年毕业于浙江大学机械系光学机械仪器专业后留校任教。<br />
                                1983年任杭州市委副书记等职。<br />
                                1985年起任新华社香港分社宣传部副部长、部长、副社长，新华社香港分社发言人。<br />
                                1998年3月调回内地任浙江大学、杭州大学、浙江农业大学、浙江医科大学四校合并领导小组副组长，新浙江大学

筹建小组组长，浙江省政府特邀顾问。<br />
                                1998年9月起任浙江大学党委书记。
                            </td>
                        </tr>
                    </table>
                    <h2>顾问</h2>
                    <table>
                        <tr>
                            <td style="padding:10px;" width="15%">
                                <img src="/static/images/subject/found/photo/image003.jpg" /><br />
                            </td>
                            <td valign="top" width="35%">
                                <h3 class="pos">陈端</h3>
                                原杭州市副市长、市政协副主席，现任杭州市关心下一代工作委员会副主任，著名心血管病专家。
                            </td>
                            <td style="padding:10px;" width="15%">
                                <img src="/static/images/subject/found/photo/azy.jpg" width="108" /><br />
                            </td>
                            <td valign="top" width="35%">
                                <h3 class="pos">安志云</h3>
                                杭州市人大原副主任
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/yrr.jpg" width="108" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">虞荣仁</h3>
                                杭州市原政协主席
                            </td>
                            <td style="padding:10px;">
                               <img src="/static/images/subject/found/photo/lzf.jpg" width="108" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">林正范</h3>
                                杭师大校长
                            </td>
                        </tr>
                    </table>
                    <h2>预选理事</h2>
                    <table>
                        <tr>
                            <td style="padding:10px;" width="15%">
                                <img src="/static/images/subject/found/photo/image005.jpg" /><br />
                            </td>
                            <td valign="top" width="35%">
                                <h3 class="pos">陈鸿</h3>
                                浙江大学89年化工自动化本科毕业，92年工业自动化硕士毕业，03年中欧国际工商管理学院MBA毕业，和多位校友

合伙人一起创建恒生电子股份有限公司，公司于03年成功上市，已经成为中国IT业的领先企业。现任公司董事，从公司具体经营工作中抽身转而投入

较多精力负责筹建杭州浙江大学校友会，任筹备组组长，酒量不好但是贪杯。
                            </td>
                            <td style="padding:10px;" width="15%">
                                <img src="/static/images/subject/found/photo/image007.jpg" /><br />
                            </td>
                            <td valign="top" width="35%">
                                <h3 class="pos">刘巍</h3>
                                2005年浙江大学—香港理工大学国际房地产学系硕士毕业。天禄广告传媒有限公司总经理，旗下有汽车公司、媒

体、网吧、信息技术公司等。刘巍用一年时间将一个人的公司发展到一百人，在奢侈品媒体行业发展出一定的品牌影响力。现任杭州浙大校友会筹备

组副组长。想追求奢侈品的男士或女士请追随刘巍和天禄。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image009.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">赵巧雅</h3>
                                96届浙大电机系校友，现任杭州亚恺电子科技有限公司总经理。是北京校友会副秘书长张一春推荐参与校友会工

作的。杭州校友会志愿者部负责人。她特别喜欢谈她的儿子，讲她儿子的故事。
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image011.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">陈亮</h3>
                                杭州浙港制衣有限公司总经理，浙大企业家经理人同学会常务副会长。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image013.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">叶志前</h3>
                                杭州格林蓝德信息技术有限公司董事长，浙大企业家经理人同学会副会长。
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image015.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">庞颖</h3>
                                88届浙大计算机系校友，现为和茶馆总经理，杭州市茶楼业协会副会长，杭州和顺堂茶文化推广有限公司总经理

。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image017.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">魏任斌</h3>
                                浙江大学管理学院校友，原话机世界集团副总裁，现为杭州民建委员、浙江连锁经营协会常务理事，杭州市青年

企业家协会常务理事，杭州飞来投资管理有限公司董事长
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image019.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">蒋锋</h3>
                                杭州市教育局初教处处长
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/qyh.jpg" width="108" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">钱永红</h3>
                                杭大新闻系毕业，获博士学位。杭州市文化广电新闻出版局副局长，浙江大学新闻与社会发展研究所硕士生导师

。
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image021.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">俞锋华</h3>
                                省科技开发中心主任，长三角科技中介联盟副理事长，浙江省技术经纪人协会副会长
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image023.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">施建基</h3>
                                77届杭大中文系校友，加拿大烈焰能源有限公司监事会主席，浙江大学校友总会理事，北美浙大校友企业家联谊

会召集人
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/whg.jpg" width="108" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">王海光</h3>
                                原杭大哲学系校友，现为万科南都董事长
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/hjq.jpg" width="108" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">胡季强</h3>
                                82届浙大医学院校友，现为康恩贝集团有限公司董事长，浙江省企业家协会副会长，全国优秀青年企业家
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image025.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">汪兴</h3>
                                90届浙大计算机校友，浙江省耀江房地产开发有限公司总经理，浙江省耀江集团副总裁，海南海德实业股份有限

公司副董事长
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image026.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">潘水苗</h3>
                                89届浙大电机系校友，现为浙江万马电缆股份有限公司董事长
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/none.gif" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">吴晓农</h3>
                                浙大网新集团有限公司董事会秘书兼总裁助理。浙江大学政治系硕士。 1987年--1996年,浙江大学电机系

教师、分团委书记、党总支委员、 浙江大学团委常委。 1996年--1999年,浙江大学电机系党总支副书记、 浙江大学工会青工委员会副主席。 1999年

--2002年,浙江大学电气工程学院党委副书记。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/sll.jpg" width="108" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">孙莉莉</h3>
                                82届管理学院校友，杭州中纬实业有限公司董事长，浙江大学管理学院校友联谊会杭州分会常务副会长
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/none.gif" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">蔡德绍</h3>
                                原中共浙江大学管理学院党总支组织委员兼党支部书记，现为浙江大学管理学院校友联谊会杭州分会副会长兼秘书长，浙江省求是经济与管理科学研究院副院长
                            </td>
                        </tr>
                    </table>
                    <p class="txtc"><button class="btn" onclick="window.scroll(0,0)">回到顶部</button></p>
                    <?php endif; ?>
                </div>
            </div>
            
            <div id="zh_intro" class="item">
                <div class="pdlr10">
                    <?php if($this->passport()): ?>
                    <h2>校友总会老师</h2>
                    <table>
                        <tr>
                            <td style="padding:10px;" width="15%">
                                <img src="/static/images/subject/found/photo/image030.jpg" /><br />
                            </td>
                            <td valign="top" width="35%">
                                <h3 class="pos">张美凤</h3>
                                浙江大学校友总会秘书长，浙大对外联络办主任，浙大教育基金会秘书处主任。充满亲和力，是著名的“美凤姐

”。是全球各地浙江大学校友会的“办主任”。
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image038.jpg" width="100" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">吴晨</h3>
                                	浙江大学发展联络办公室副主任,浙江大学校友总会副秘书长。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image036.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">顾玉林</h3>
                                浙江大学教育基金会秘书处办公室主任，校友总会秘书处办公室副主任，发展联络办公室国内部主任。网名：玉

树临风。
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image032.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">包永平</h3>
                                发展联络办公室综合部主任，校友总会秘书处办公室副主任。按照家谱，包玉刚叫他叔叔。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/lxe.jpg" width="96" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">娄小娥</h3>
                                浙江大学发展联络办公室副主任，浙江大学校友总会副秘书长；浙江大学教育基金会副秘书长
                            </td>
                            <td style="padding:10px;" width="15%">
                                <img src="/static/images/subject/found/photo/image028.jpg" /><br />
                            </td>
                            <td valign="top" width="35%">
                                <h3 class="pos">杨捷</h3>
                                发展联络办、校友联络部。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image034.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">庄代波</h3>
                                发展联络办、校友联络部。
                            </td>
                        </tr>
                    </table>
                    <?php endif; ?>
                </div>
            </div>
                                
            <div id="cb_intro" class="item">
                <div class="pdlr10">
                    <?php if($this->passport()): ?>
                    <h2>筹备组成员简介</h2>
                    <table>
                        <tr>
                            <td style="padding:10px;" width="15%">
                                <img src="/static/images/subject/found/photo/image005.jpg" /><br />
                            </td>
                            <td valign="top" width="35%">
                                <h3 class="pos">陈鸿</h3>
                                浙江大学89年化工自动化本科毕业，92年工业自动化硕士毕业，03年中欧国际工商管理学院MBA毕业，和多位校友

合伙人一起创建恒生电子股份有限公司，公司于03年成功上市，已经成为中国IT业的领先企业。现任公司董事，从公司具体经营工作中抽身转而投入

较多精力负责筹建杭州浙江大学校友会，任筹备组组长，酒量不好但是贪杯。
                            </td>
                            <td style="padding:10px;" width="15%">
                                <img src="/static/images/subject/found/photo/image007.jpg" /><br />
                            </td>
                            <td valign="top" width="35%">
                                <h3 class="pos">刘巍</h3>
                                2005年浙江大学—香港理工大学国际房地产学系硕士毕业。天禄广告传媒有限公司总经理，旗下有汽车公司、媒

体、网吧、信息技术公司等。刘巍用一年时间将一个人的公司发展到一百人，在奢侈品媒体行业发展出一定的品牌影响力。现任杭州浙大校友会筹备

组副组长。想追求奢侈品的男士或女士请追随刘巍和天禄。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image009.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">赵巧雅</h3>
                                96届浙大电机系校友，现任杭州亚恺电子科技有限公司总经理。是北京校友会副秘书长张一春推荐参与校友会工

作的。杭州校友会志愿者部负责人。她特别喜欢谈她的儿子，讲她儿子的故事。
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image052.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">赵爱桔</h3>
                                97年浙江大学化工工艺本科毕业，05年入浙江大学攻读化学工程(制药工程方向)硕士研究生。现就职于浙江省食

品药品监督管理局，杭州浙大校友会(筹)副秘书长。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;" width="15%">
                                <img src="/static/images/subject/found/photo/image042.jpg" /><br />
                            </td>
                            <td valign="top" width="35%">
                                <h3 class="pos">宋常畏</h3>
                                03年浙大材化学院本科毕业，爱康健康管理公司销售经理，杭州浙江大学校友会副秘书长，负责校友会宣传工作

，是最积极的骨干之一。说话时底气十足，似乎每个女生都想追求他。
                            </td>
                            <td style="padding:10px;" width="15%">
                                <img src="/static/images/subject/found/photo/image044.jpg" /><br />
                            </td>
                            <td valign="top" width="35%">
                                <h3 class="pos">殷佳东</h3>
                                97年浙大管理系本科毕业，03年浙大管理学院MBA毕业。银联商务有限公司浙江分公司的核心骨干。他非常的聪明

、直率。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image046.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">方梓欣</h3>
                                00年浙江大学工学学士毕业，05年浙江大学管理学硕士毕业。在大雪纷飞一票难求的春运时期，他借助人脉居然

还能弄到多张卧铺票。走路飞快是他的一大特色。
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image048.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">王伟强</h3>
                                05年浙江大学国际经济与贸易本科毕业，现任恒生银行杭州分行优越理财经理，杭州浙大校友会的副秘书长。<br 

/>
                                户外活动爱好者，装备齐全，但鞋有点破了。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/image050.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">陈杰</h3>
                                05年浙江大学法律硕士毕业，浙江凯富律师事务所合伙人。杭州浙大校友会(筹)副秘书长。
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/none.gif" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">郑家林</h3>
                                浙江大学金融学专业毕业，现为长江证券杭州庆春路营业部总经理。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/none.gif" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">李艳</h3>
                                98级浙大卫生事业管理专业攻读本科，05级浙大社会医学专业攻读硕士。现为浙大恩氏基因技术有限公司副总经理，杭州浙大校友会(筹)母校联络部部长。
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/wlh.jpg" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">王莉华</h3>
                                07年浙大经贸英语专业毕业，现为浙江大学管理学院创新与发展研究中心许庆瑞院士项目秘书。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/none.gif" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">蔡海东</h3>
                                99级浙大材料与化学工程学院校友。
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/none.gif" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">葛海龙</h3>
                                96年入杭大读本科，00年读研。现就职于省委组织部，任杭州市志愿者协会副秘书长。平时热衷于社会活动，01年曾为校研会主席团成员。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/none.gif" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">周建军</h3>
                                浙江建林电子电气有限公司总经理，象棋高手。
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/none.gif" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">吴嘉庆</h3>
                                95届浙大计算机系校友，现为招行杭州分行信息技术部副总经理。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/none.gif" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">候鑫</h3>
                                99级信息科学与工程学院校友，88名誉站长
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/none.gif" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">林琳</h3>
                                99级法学专业校友，工作于浙江省劳动保障监察总队。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/lp.jpg" width="98" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">李平</h3>
                                95级材料与化学工程学院校友，现为杭州中化信息研究有限公司董事长。自主研发和运营了中国化工设备网、易紧通等行业B2B网站。
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/zhs.jpg" width="98" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">朱红胜</h3>
                                02级管理学院校友，现为飞来投资董事，营销中心总经理助理。
                            </td>
                        </tr>
                        <tr>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/none.gif" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">王锋</h3>
                                03年浙江大学控制系专业毕业，杭州盈高科技有限公司总经理。周杰伦最忠诚的fans。
                            </td>
                            <td style="padding:10px;">
                                <img src="/static/images/subject/found/photo/none.gif" /><br />
                            </td>
                            <td valign="top">
                                <h3 class="pos">林宇</h3>
                                05级就读浙大工商管理，擅长计算机相关工作，主要负责校友会网站设计
                            </td>
                        </tr>
                    </table>
                    <?php endif; ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
        <div id="footer" class="txtc">
        	<a href="/info/support/help">帮助</a>
			<a href="/info/support/about">关于</a>
			<a href="/info/support/contact_us">联系我们</a>
			<a href="/info/support/privacy_claim">隐私声明</a>
			<a href="http://www.zjuhz.com/old" target="_blank">旧版回顾</a>
			<a href="http://ourzju.uu1001.com" target="_blank">校友论坛</a>
			<a href="http://www.miibeian.gov.cn" target="_blank">浙ICP备06052510号</a>
			杭州浙江大学校友会(筹)&copy;2008
	        <script type="text/javascript" src="http://js.tongji.cn.yahoo.com/705170/ystat.js"></script><noscript><a href="http://tongji.cn.yahoo.com"><img src="http://img.tongji.cn.yahoo.com/705170/ystat.gif"/></a></noscript>
        </div>
    </div>
    
    <script type="text/javascript">
        function tab(section)
        {
            $('#content div.item').hide();
            $('#nav a').css('background','none');
            $('a.'+section).css('background','#EFE0CC');
            $('#'+section).fadeIn();
            $.cookie('found_tab',section);
            
            if(section == 'ls_intro' || section == 'zh_intro' || section == 'cb_intro')
            {
                <?php if(!$this->passport()): ?>
                    $('#signup').fadeIn();
                <?php endif; ?>
            }
            $('#loading').hide();
        }
        if($.cookie('found_tab') == null) tab('plan');
        else tab($.cookie('found_tab'));
    
        function relogin() {
            var formdata = $("#relogin_form").fastSerialize();
        
            $.post("/member/login/dologin/", formdata, function(msg) {
                if ("redirect" == msg) {
                    history.go(0);
                }
                else alert(msg);
            });
            return false;
        }
        
        function signup()
        {
            $('.btn').attr('disabled',true);
            $('#sign_tip').html('<img src="/static/images/loading1.gif" /> <span class="sub">报名ing...</span>');
            $.post('/group/subject/found',
                   $('#sign_form').fastSerialize(),
            function(data){
                if(data == 'success')
                {
                	<?php if($this->passport()): ?>
                    var email = $('#email').val();
                    var mobile = $('#mobile').val();
                    var address = $('#address').val();
                    var year = $('#year').val();
                    var major = $('#major').val();
                    $.post("/member/my/docontact",{'eMail':email, 'mobile':mobile, 'address':address});
                    $.post("/member/my/dobasic",{'year':year, 'major':major, 'college':<?= $this->passport('college') ?>, 'birthday':'<?= $this->passport('birthday') ?>'});
                    <?php endif; ?>
                    window.history.go(0);
                }
                else
                {
                    $('#sign_tip').html(data);
                    $('.btn').attr('disabled',false);
                    $('#sign_tip').children().fadeOut(3000);
                }
            });
            return false;
        }
        
        <?php if($this->uname && $this->pswd && !$this->passport()): ?>
        relogin();
        <?php endif; ?>
    </script>
</body>
</html>