<div id="main">
	<div class="sidebar">
		<div class="info_category">
			<h2>信息中心</h2>
			<dl>
				<?php if($this->categories): foreach ($this->categories as $cate): ?>
				<dd>
				<a href="?category=<?= $cate->category_id ?>"<?php if($this->categoryId == $cate->category_id) echo ' style="background:#D9E6F7"' ?>>
				<img border="0" src="/static/images/icon/<?= $cate->category_icon ?>.gif" />
				<?= $cate->category_name ?></a>
				</dd>
				<?php endforeach; endif; ?>
			</dl>
		</div>
	</div>
	
	<table class="sidebar entity_list" cellspacing="0">
		<tr>
			<th width="65%">标题 <small> <?= $this->numrows ?>篇 , <?= $this->numpages ?>页</small></th>
			<th width="20%">发布时间</th>
			<th width="15%">发布人</th>
		</tr>
		<?php if(!count($this->rows)): ?>
		<tr><td colspan="3">该类尚未发布任何信息</td></tr>
		<?php else: foreach ($this->rows as $k => $v): ?>
		<tr class="entity_row">
			<td style="font-size:14px">
				<?php if($v['entity_top'] == 1): ?>
				<img src="/static/images/bullet/red.gif" align="absmiddle" /> 
				<?php else : ?>
				<img src="/static/images/bullet/green.gif" align="absmiddle" /> 
				<?php endif; ?>
				<a href="/info/view/detail/id/<?= $v['entity_id'] ?>"><?= $v['entity_title'] ?></a>
				<?php if(time()-$v['entity_pub_time'] < (12*3600)): ?>
				<img src="/static/images/icon/new.gif" />
				<?php endif; ?>
			</td>
			<td style="font-size:10px"><?= Commons::date($v['entity_pub_time']) ?></td>
			<td style="font-size:10px"><?= $v['user_name'] ?></td>
		</tr>
		<?php endforeach; endif; ?>
		<tr>
		<td colspan="3" style="background:#fff; border:none;"><div class="pagination"><?= $this->pagination ?></div></td>
		</tr>
	</table>
	
	
</div>



<script>
$('.entity_row').mouseover(function(){ $('td',this).css('background','#fff') });
$('.entity_row').mouseout(function(){ $('td',this).css('background','#f5f5f5') });
</script>