<div id="main">
	<div class="sub_bar">
		<div class="info_category">
			<h2>信息中心</h2>
			<dl>
				<?php if($this->categories): foreach ($this->categories as $cate): ?>
				<dd>
				<a href="?category=<?php echo $cate->category_id ?>"<?php if($this->category_id == $cate->category_id) echo ' style="background:#D9E6F7"' ?>>
				<img border="0" src="/static/images/icon/<?php echo $cate->category_icon ?>.gif" />
				<?php echo $cate->category_name ?></a>
				</dd>
				<?php endforeach; endif; ?>
			</dl>
		</div>
	</div>
	
	<table class="sub_bar entity_list" cellspacing="0">
		<tr>
			<th width="70%">标题</th>
			<th width="20%">发布时间</th>
			<th width="10%">浏览</th>
		</tr>
		<?php if(!count($this->rows)): ?>
		<tr><td colspan="3">该类尚未发布任何信息</td></tr>
		<?php else: foreach ($this->rows as $row): ?>
		<tr class="entity_row">
			<td style="font-size:14px">
				<img src="/static/images/bullet/green.gif" align="absmiddle" /> 
				<a href="/info/index/view/id/"><?php echo $row->entity_title ?></a>
			</td>
			<td style="font-size:10px"><?php echo Commons::date($row->entity_pub_time) ?></td>
			<td style="font-size:10px"><?php echo $row->entity_view_num ?></td>
		</tr>
		<?php endforeach; endif; ?>
	</table>
</div>

<script>
$('.entity_row').mouseover(function(){ $('td',this).css('background','#f5f5f5') });
$('.entity_row').mouseout(function(){ $('td',this).css('background','#eee') });
</script>