<div class="sidebar">
<?= $this->render('dynamic/sort.phtml'); ?>
</div>

<div class="sidebar">
<?= $this->render('dynamic/notice.phtml'); ?>

<table class="help_set">

    <!-- 最新问题 -->
	<tr>
	<th class="txtl">最新问题</th>
	<th class="txtr" colspan="2"></th>
	</tr>
    <?php foreach ($this->latest as $value) { ?>
	<tr>
	<td class="cat"><a href="/help/sort/browse/sid/<?= $value['pid']; ?>/">[<?= $value['pName']; ?>]</a></td>
	<td>
	<a href="/help/question/detail/qid/<?= $value['qid']; ?>/"><?= $value['title']; ?></a> 
	<?php if (0 < $value['offer']) { ?><span class="f9"><img src="/static/images/icon/icn_offer.gif" title="积分悬赏"><?php echo $value['offer']; } ?></span>	
	</td>
	</tr>
    <?php } ?>

	<!-- 高分求助 -->
	<tr>
	<th class="txtl">高分求助</th>
	<th class="txtr" colspan="2"></th>
	</tr>
    <?php foreach ($this->offer as $value) { ?>
	<tr>
	<td class="cat"><a href="/help/sort/browse/sid/<?= $value['pid']; ?>/">[<?= $value['pName']; ?>]</a></td>
	<td>
	<a href="/help/question/detail/qid/<?= $value['qid']; ?>/"><?= $value['title']; ?></a> 
	<?php if (0 < $value['offer']) { ?><span class="f9"><img src="/static/images/icon/icn_offer.gif" title="积分悬赏"><?php echo $value['offer']; } ?></span>	
	</td>
	</tr>
    <?php } ?>

	<tr>
	<th class="txtl">被遗忘的</th>
	<th class="txtr" colspan="2"></th>
	</tr>
    <?php foreach ($this->forget as $value) { ?>
	<tr>
	<td class="cat"><a href="/help/sort/browse/sid/<?= $value['pid']; ?>/">[<?= $value['pName']; ?>]</a></td>
	<td>
	<a href="/help/question/detail/qid/<?= $value['qid']; ?>/"><?= $value['title']; ?></a> 
	<?php if (0 < $value['offer']) { ?><span class="f9"><img src="/static/images/icon/icn_offer.gif" title="积分悬赏"><?php echo $value['offer']; } ?></span>	
	</td>
	</tr>
    <?php } ?>

	<tr>
	<th class="txtl">最近解决</th>
	<th class="txtr" colspan="2"></th>
	</tr>
    <?php foreach ($this->solved as $value) { ?>
	<tr>
	<td class="cat"><a href="/help/sort/browse/sid/<?= $value['pid']; ?>/">[<?= $value['pName']; ?>]</a></td>
	<td>
	<a href="/help/question/detail/qid/<?= $value['qid']; ?>/"><?= $value['title']; ?></a> 
	<?php if (0 < $value['offer']) { ?><span class="f9"><img src="/static/images/icon/icn_offer.gif" title="积分悬赏"><?php echo $value['offer']; } ?></span>	
	</td>
	</tr>
    <?php } ?>
</table>
</div>

<div class="sidebar">
<?= $this->render('help.phtml'); ?>

<?= $this->render('dynamic/point.phtml'); ?>
</div>
