<h2>修改信息</h2>

<div id='man'>
  <form method="POST">
  <?php if($this->tips): ?>
  <p class="tips"><?php echo $this->tips ?></p>
  <?php  endif; if(!$this->categories): ?>
  <p class="tips">您目前没有权限增加信息</p>
  <?php else: ?>
  <p>
  所属分类 <select name="cate_id">
  <?php foreach ($this->categories as $row): ?>
  	<option value="<?php echo $row->category_id ?>"<?php if($this->row->category_id == $row->category_id) echo 'selected="selected"' ?>>
  	<?php echo $row->category_name ?>
  	</option>
  <?php endforeach; ?>
  </select>
  修改时间 <input type="text" name="pub_time" value="<?php if(!$this->row->entity_mod_time) echo Commons::date(); else echo Commons::date($this->row->entity_mod_time); ?>" size="40" />
  </p>
  <p>
  标题 <input type="text" name="title" value="<?php echo stripslashes($this->row->entity_title) ?>" size="80" />
  </p>
  <?php endif; ?>
  <textarea name="content" id="content" style="display:none;"><?php echo stripslashes($this->row->entity_content) ?></textarea>
  <iframe src="/static/editor/info/Edit/editor.htm?id=content&ReadCookie=0" frameBorder="0" marginHeight="0" marginWidth="0" scrolling="No" width="650" height="480"></iframe>
  <p style="text-align:center"><input type="submit" value="提交新信息" style="padding:5px 10px; font-size:14px; border:3px double #aaa; cursor:pointer; background:#ffc;" /></p>
  </form>
</div>