<?php
	echo "{$this->Doctype('XHTML1_TRANSITIONAL')}\n";
?>
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="zh-CN" />
<?php
	echo $this->headMeta();
?>
<script type="text/javascript" src="/static/scripts/jquery.js"></script>
<script type="text/javascript" src="/static/scripts/common.js"></script>
<?php
	echo $this->headScript();
	echo $this->headLink();
	echo $this->headStyle();
	echo $this->render("head.phtml");
?>
</head>

<body>
<div id="wrap">

<table class="rc">
<tr><td class="rc_tl"></td><td class="rc_tr"></td></tr>
</table>

<table id="header">
<tr>
<td id="logo" title="杭州浙江大学校友会欢迎您 - zjuhz.com" onClick="location.href='/'">
	<i>zjuhz.com</i>
	<p>杭州浙江大学校友会</p>
</td>
<td>
<table id="global_search">
	<tr>
	<td class="models">
	<?php
		echo $this->partial("partial/global-model.phtml", $this->request->getParams());
	?>
	</td>
	<td class="nav">
	<?php 
		// 显示用户当前的状态(登陆/登出/各便捷连接)
		echo $this->partial("partial/global-nav.phtml", $this->login);
	?>
	</td>
	</tr>
	<tr>
	<td class="search_form" colspan="2">
	<?php 
		// 不同模块显示不通的搜索条
		echo $this->render("search.phtml");
	?>
	</td>
	</tr>
</table>
</td>
</tr>
</table>
<?php 
	//Script主体内容
	echo $this->layout()->content;
	
	echo $this->partial("partial/global-footer.phtml");
?>
<table class="rc">
<tr><td class="rc_bl"></td><td class="rc_br"></td></tr>
</table>
</div>
</body>
</html>