<?php
	echo "{$this->Doctype('XHTML1_TRANSITIONAL')}\n";
?>
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="zh-CN" />
<?php
	echo $this->headMeta();
?>
<script type="text/javascript" src="/static/scripts/jquery.js"></script>
<script type="text/javascript" src="/static/scripts/common.js"></script>
<?php
	echo $this->headScript();
	echo $this->headLink();
	echo $this->headStyle();
	echo $this->render("head.phtml");
?>
</head>

<body>
<div id="wrap">

<table class="rc">
<tr><td class="rc_tl"></td><td class="rc_tr"></td></tr>
</table>

<table id="header">
<tr>
<td id="logo" title="杭州浙江大学校友会欢迎您 - zjuhz.com" onClick="location.href='/'">
	<i>zjuhz.com</i>
	<p>杭州浙江大学校友会</p>
</td>
<td>
<?= $this->render("top.phtml") ?>
</td>
</tr>
</table>
<?php 
	//Script主体内容
	echo $this->layout()->content;
	
	echo $this->partial("partial/global-footer.phtml");
?>
<table class="rc">
<tr><td class="rc_bl"></td><td class="rc_br"></td></tr>
</table>
</div>
</body>
</html>