<?= $this->headTitle('校友互助 - 杭州浙江大学校友会 [ zjuhz.com ]','append');$this->headTitle()->setSeparator(' - '); ?>

<!-- 当前位置 /////////////////////////////////// -->
<div id="help_position">
    <a href="/help/">校友互助</a> > <a href="/help/question/add/">我要提问</a></div>

<!-- 我要提问 //////////////////////////////////////////// -->
<div class="sidebar">
    <div id="topic" class="help_on">
        <h2>我要提问 </h2>
        <!-- 提问表单 ///////////////////////////////////////////// -->
	    <div id="question_add_form">
        <form method="post" name="frmQuestion" id="frmQuestion" autocomplete="off">

		    <table width="100%" border="0">
              <tr>
                <td>标题概要：</td>
                <td><input type="text" name="title" id="title" class="help_input_kuang" value="" maxlength="30" style="width:350px" /></td>
                <td>&nbsp;</td>
              </tr>
              <tr>
                <td>详细描述：<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /></td>
                <td><textarea name="content" id="content" class="question_add_textarea"></textarea>问题描述越详细，回答也会越准确！</td>
                <td>&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
              </tr>				  
              <tr>
                <td>问题标签：</td>
                <td><input type="text" name="tags" id="tags" class="help_input_kuang" value="" maxlength="36" style="width:350px" /><br>每个标签最多5个字，以英文空格间隔，最多允许6个标签。</td>
                <td>&nbsp;</td>
              </tr>				  
              <tr>
                <td>问题分类：</td>
                <td></td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td>积分悬赏：</td>
                <td><input type="text" name="offer" id="offer" class="help_input_kuang" value="" maxlength="4" style="width:60px" /> 我当前的积分是<strong>0</strong>分</td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td>匿名提问：</td>
                <td><input type="checkbox" name="anonym" id="anonym" value="checkbox" /> 匿名提问将隐藏提问人的真实姓名</td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td>验证码：</td>
                <td><input type="text" name="vcode" id="vcode" class="verify" value="" maxlength="4" />&nbsp;<span id="putVerifyImg"></span></td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td></td>
                <td><input type="submit" name="btnSubmit" id="btnSubmit" class="help_btn_medium" onClick="tinyMCE.triggerSave(false,false);" value="提交问题" /></td>
                <td></td>
              </tr>
              <tr>
                <td></td>
                <td><div id="ajaxhint"></div></td>
                <td></td>
              </tr>			  
            </table>
		<input type="hidden" name="isPutVerifyImg" id="isPutVerifyImg" value="show" />			
        </form>        
	    </div>
    </div>
</div>

<!--  ////////////////////////////////////////////// -->
<div class="sidebar">
<table class="rightside_dot">
<tr>
<th class="txtl" colspan="2">类似的问题</th>
</tr>
<tr>
<td><strong>·</strong><a href="/help/question/display/id/1/" target="_blank" class="dot">title</a></td>
<td></td>
</tr>
</table>
</div>