<div id="main">

<div class="sidebar" style="width:250px;">
<form method="post" onsubmit="return login()">
<div id="login_form">
<p class="account">
登陆帐号:<br />
<input tabindex="1" name="uname" type="text" class="login_input" onfocus="input_focus('login_input')" onblur="input_blur('login_input')" />
</p>
<p class="password">
密码: (<a href="">忘记了?</a>)<br />
<input tabindex="2" name="pswd" type="password" class="login_input" onfocus="input_focus('login_input')" onblur="input_blur('login_input')" />
</p>
<p>
<input name="rememberme" type="hidden" value="0" />
<label for="auto_login"><input tabindex="3" name="rememberme" id="auto_login" type="checkbox" value="1" /> 请记住我,下次自动登陆</label>
</p>
<br />
<table>
<tr>
<td><input tabindex="4" type="image" src="/static/images/btn/login.gif" /></td>
<td valign="middle"><a href="/member/register/" class="registry">我要注册</a></td>
</tr>
</table>
</div>
</form>
</div>

<script type="text/javascript">
function login()
{
	$.post('/member/login/dologin/',
			$("#login_form").fastSerialize(),
			function(data){
				if(data == 'redirect')
				location.href="/home/welcome/";
				else $.facebox('<img src="/static/images/icon/stop.gif" align="absmiddle" /> 登陆失败！')
			}
		);
	return false;
}
</script>
<!-- 宣传+快捷连接 -->
<div class="sidebar">
<div class="intro">
<p class="notice">
	<b>目标：</b>校友沟通、互助的平台和助手<br />
	<b>宗旨：</b>联络校友、帮助校友、回报母校
</p>

<h2>杭州浙大校友在这里可以:</h2>
<ul>
<li>拥有只属于浙大校友的互动空间</li>
<li>给予和得到来自校友的帮助</li>
<li>组建或参与校友的各种俱乐部</li>
<li>体验高质量的社交环境</li>
<li>自由安全地控制个人隐私</li>
</ul>
</div>
</div>

<!-- 专题区 -->
<div class="sidebar subject">
<h2>活动</h2>
<a href="">即将开放</a>
<h2>专题</h2>
<a href="">即将开放</a>
</div>

<?php 
if(!$this->cache->start('homepage')):
?>
<!-- 显示在首页的信息目录列 -->
<div class="sidebar" style="clear:left; width:172px;">
<div id="news_list">
<?php 
$cat_rows = $this->info_xmlrpc->call('rpcInfo.get_public_categories');
foreach ($cat_rows as $k => $v): ?>
<a href="" onmouseover="show_news(<?= $k+1 ?>)"><img src="/static/images/icon/<?= $v['category_icon'] ?>.gif" /><?= $v['category_name'] ?></a>
<?php endforeach; ?>
</div>
</div>

<!-- 相应的内容快照 -->
<div class="sidebar" style="width:667px; height:210px; margin-top:15px;">
<?php 
foreach ($cat_rows as $k => $v):
//获取相应文章快照
$art_rows = $this->info_xmlrpc->call('rpcInfo.get_arts_snapshot', array((int)$v['category_id']));
?>			
<table class="news_page" id="num_<?= $k+1 ?>">
<tr>
<td valign="top">							
<?php foreach ($art_rows as $k2 => $v): ?>
<a href="/info/view/detail/id/<?= $v['entity_id'] ?>" title="[<?= Commons::date($v['entity_pub_time']) ?>] <?= $v['entity_title'] ?>"><?= substr($v['entity_title'],0,80).'..' ?></a>
<?php endforeach; ?>
<a href="/info/?category=<?= $v['category_id'] ?>" class="more"></a>
</td>
<td width="253"><img src="/static/images/pics/<?= $k+1 ?>.jpg" /></td>
</tr>
</table>
<?php endforeach; $this->cache->end(); endif; ?>
</div>

<script type="text/javascript">show_news(1)</script>