<div class="span-24 last oneCol" style="padding-bottom:10px;">
	<p class="extInline2 mg10" style="line-height:150%">
		<?= Cmd::icon('emoticon_grin.png') ?>
		欢迎来到杭州浙江大学校友会网站。我们的
		<b>目标：</b>校友沟通、互助的平台和助手 
		<b>宗旨：</b>联络校友、帮助校友、回报母校
	</p>
	
	<div class="span-11">
		<form class="prepend-1" method="post" id="relogin_form" onsubmit="return relogin();">
			<table>
				<tr>
					<td class="txtr vm">账号：</td>
					<td><input class="text" name="uname" type="text" maxlength="16" value="<?= $this->uname; ?>" /></td>
				</tr>
				<tr>
					<td class="txtr vm">密码：</td>
					<td><input class="text" name="pswd" type="password" maxlength="16" value="<?= $this->pswd; ?>" /></td>
				</tr>
				<tr>
					<td class="txtr vm"></td>
					<td><label for="alive"><input id="alive" type="checkbox" <?= ($this->uname) ? 'checked="checked"':'' ?> value="0" name="alive" /> 下次自动登录</label></td>
				</tr>
				<tr>
					<td></td>
					<td><p class="txtr"><input style="width:100%" class="btn" id="btnLogin" type="submit" value="登 录" /></p></td>
				</tr>
			</table>
		</form>
	</div>
	
	<div class="span-6">
		<h3>杭州浙大校友在这里可以:</h3>
		<ul class="f14">
			<li><?= Cmd::icon('bullet_blue.png') ?> 拥有只属于浙大校友的互动空间</li>
			<li><?= Cmd::icon('bullet_blue.png') ?> 给予和得到来自校友的帮助</li>
			<li><?= Cmd::icon('bullet_blue.png') ?> 组建或参与校友的各种俱乐部</li>
			<li><?= Cmd::icon('bullet_blue.png') ?> 体验高质量的社交环境</li>
			<li><?= Cmd::icon('bullet_blue.png') ?> 自由安全地控制个人隐私</li>
		</ul>
	</div>
	
	<div class="prepend-1 span-4 last">

	</div>

</div>

<?php if(!$this->cache->start('homepage')): ?>
<div class="span-24 last">
	<div class="span-7 mgu10">
		<iframe frameborder="0" height="215" width="270" src="/ad.html"></iframe>
		<?= $this->render('items/notice.phtml'); ?>
		<?= $this->render('items/trends.phtml'); ?>
		<?= $this->render('items/zjuorg.phtml'); ?>
		<?= $this->render('items/teacher.phtml'); ?>
		<?= $this->render('items/dev.phtml'); ?>
	</div>
	<div class="span-10 mgu10">
		<?= $this->render('items/9-20.phtml'); ?>
		<div class="oneCol mgd10">
                    <h3 class="mglf10">群组活动</h3>
                    <?= $this->newevents(5) ?>
                </div>
		<?= $this->render('items/biz.phtml'); ?>
		<?= $this->render('items/groups.phtml'); ?>
	</div>
	<div class="span-7 mgu10 last">
		<?= $this->render('items/news.phtml'); ?>
		<?= $this->render('items/alma-mater.phtml'); ?>
		<?= $this->render('items/active.phtml'); ?>
		<?= $this->render('items/subject.phtml'); ?>
		<?= $this->render('items/links.phtml'); ?>
		<a target="_blank" href="http://www.zjuhz.com/group/topic/show?gid=18&tid=216"><img style="margin:5px;" src="/static/images/ads/ad_1.jpg" /></a>
	</div>
</div>
<?php $this->cache->end(); endif; ?>

<script type="text/javascript">
	<?php if($this->uname && $this->pswd): ?>
    relogin();
    <?php endif; ?>
	// 会员登录
	function relogin() {
		var formdata = $("#relogin_form").fastSerialize();
	
		$.post("/member/login/dologin/", formdata, function(msg) {
			if ("redirect" == msg) {
				history.go(0);
			}
			else alert(msg);
		});
		return false;
	}
	$('#f920').hide();
	$('#f920').slideDown(3000);
</script>