<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>校友中心-基础信息迷你名片</title>
<style>
#ucard { margin:10px;text-align:left; }
#ucard u{ text-decoration:none; border-bottom:1px solid #666; }
#ucard td { line-height:180%; }
</style>
</head>

<body>
<p style="padding:0; margin:0; text-align:left">
<img style="cursor:pointer;" src="/static/images/icon/close.gif" onclick="$('.cardContainer').remove()" />
</p>
<?php if($this->card) { ?>
<table id="ucard">
  <tr>
    <td><?= $this->face($this->card['uid']); ?></td>
    <td class="vm" style="padding:0 0 0 5px">
    性别：<u><?= $this->card['sex']; ?></u><br />
    最近上线：<u><?= date('m月d日', $this->card['lastLogin']); ?></u><br />
    入学年份：<u><?= (1900 < $this->card['year'] ? "{$this->card['year']}年" : ''); ?></u><br />
    所在院系：<u><?= (0 < $this->card['college'] ? $this->college($this->card['college']) : ''); ?></u><br />
    <a href="javascript:beFriendsWith(<?= $this->card['uid'] ?>)">加为好友</a> 
    <a href="/group/pm/member?uid=<?= $this->card['uid'] ?>">发站内信</a><br />
	
	<?php if($this->qq != null) : ?>
	<a href="tencent://Message/?Uin=<?= $this->qq ?>&websiteName=q-zone.qq.com&Menu=yes"><img border="0" SRC='http://wpa.qq.com/pa?p=1:<?= $this->qq ?>:5' /></a>
	<?php endif; ?>
    </td>
  </tr>
</table>
<table height="100%" border="0">
  <tr>
    <td>&nbsp;</td>
  </tr>
</table>
<?php } else { ?>
<p>抱歉，该校友暂未完善个人资料。</p>
<?php } ?>
</body>
</html>
<script type="text/javascript">
	function beFriendsWith(uid)
	{
		$.get('/group/member/befriendwith?uid='+uid,null,function(html){
			$.facebox(html);
		});
	}
</script>