<table class="global_search">
<tr>
<!-- 状态信息 /////////////////////////////////////////// -->
	<td class="nav">
	    <?php if ($this->passport()) { ?>
	    您好，<?= $this->passport('realName') ?>|
	    <?php if(false != DbModel::hasClass($this->passport('uid'))) :?>
		<a style="color:green" href="javascript:fastInvite()">邀请校友</a>|
		<a style="color:#A90A5E" target="_blank" href="/chat/">聊天室</a>|
	    <a href="/class/home">我的班级</a>|
	    <?php endif; ?><a href="/member/my/">我的账号</a>|
	    <!-- <a href="">站内信<?= ($this->passport('unRead') > 0) ? "({$this->passport('unRead')})" : ''; ?></a> |  -->
	    <a href="/member/logout/" onClick="return window.confirm('确实要退出吗？');">退出</a><?php }	else { ?><a href="/member/register/">注册</a>|<a href="/member/login/">登录</a><?php } ?>
	</td>
</tr>
</table>
<table class="global_search">
	<tr>
	<!-- 模块选择 /////////////////////////////////////////// -->
	<td class="models">
	<a href="/biz/">创业</a>
	<a href="/member/">校友</a>
	<a href="/info/">资讯</a>
	<a href="/help/">互助</a>
	<a href="/class/" class="on">班级</a>
	<a href="/group/">群组</a>
	<a href="/group/events/list">活动</a>
	</td>
	</tr>
	<tr>
	<td class="search_form" colspan="2">
	<!-- 搜索框 /////////////////////////////////////////// -->
	<form method="GET" action="/class/search">
	<input type="hidden" name="year" value="<?= $this->year ?>" />
	<input type="hidden" name="college" value="<?= $this->college ?>" />
<input class="input" name="for" type="text" onmouseover="this.style.borderColor='#666'" onmouseout="this.style.borderColor='#ccc'" onfocus="input_focus('input')" onblur="input_blur('input')" value="<?= $this->keywords ?>" />
<input class="btn" type="submit" value="搜索" /> 
</form>
	</td>
	</tr>
</table>