<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?= $this->render("head.phtml").$this->headLink().$this->headStyle().$this->render("company-head.phtml").$this->headScript(); ?>
</head>

<body>
<div id="wrap">

    <div id="header" style="background:none">
        <table id="passport" cellpadding="0" cellspacing="0" width="100%">
            <tr>
                <td style="text-align:left"><a href="/member/">校友</a> | <a href="/info/">资讯</a> | <a href="/help/">互助</a> | <a href="/class/">班级</a> | <a href="/company/"><b>企业</b></a> | <a href="#">群组</a> | <a href="#">活动</a> </td>
                <td style="text-align:right" class="pdr10"><?php if ($this->sessCommon->login) { ?>您好，<?= $this->sessCommon->login['realName']; ?>|<a href="/company/my/">个人管理</a>|<a href="/member/my/">我的账号</a><!--|<a href="">站内信<?= ($this->sessCommon->login['unRead'] > 0) ? "({$this->sessCommon->login['unRead']})" : ''; ?></a>-->|<a href="/company/">返回首页</a>|<a href="/member/logout/" onClick="return window.confirm('确实要退出吗？');">退出</a><?php } else { ?><a href="/member/register/">注册</a>|<a href="/member/login/">登录</a><?php } ?></td>
            </tr>
        </table>
	
        <div id="banner">
            <p class="floatLeft"><?= ('Y' === $this->dataCompany['face'] ? $this->Companyface($this->dataCid, 'large') : ''); ?></p>
            <h1><?= $this->dataCompany['name']; ?></h1>
            <p style="padding:0 0 0 30px;"><a href="http://www.zjuhz.com/company/detail/index/cid/<?= $this->dataCid; ?>/" title="<?= $this->dataCompany['name']; ?>">http://www.zjuhz.com/company/detail/index/cid/<?= $this->dataCid; ?>/</a></p>
        </div>
    </div>

    <div id="container">
        <?= $this->layout()->content; ?>
    </div>

    <?= $this->render("foot.phtml"); ?>

</div>
</body>

</html>