<table id="global_search">
	<tr>
	<!-- 模块选择 /////////////////////////////////////////// -->
	<td class="models">
	<a href="/info/">资讯</a>
	<a href="/help/" class="on">互助</a>
	<a href="/class/">班级</a>
	<a href="/member/">校友</a>
	<a href="/blog/">日志</a>
	<a href="/play/">活动</a>
	</td>
	<!-- 状态信息 /////////////////////////////////////////// -->
	<td class="nav">
    <?php if ($this->login) { ?>
		欢迎：<a href="/help/"><?= $this->login['realName'] ?></a>
		<a href="">站内信<?= ($this->login['unRead'] > 0) ? "({$this->login['unRead']})" : ''; ?></a>
		<a href="/member/login/dologout/" onClick="return window.confirm('确实要退出吗？');">退出</a>
	<?php }	else { ?>
		<a href="/member/register/">注册</a>
		<a href="/member/login/">登录</a>
	<?php } ?>
	</td>
	</tr>
	<tr>
	<td class="search_form" colspan="2">
	<!-- 搜索框 /////////////////////////////////////////// -->
	<form method="POST">
        <input class="input" type="text" onmouseover="this.style.borderColor='#666'" onmouseout="this.style.borderColor='#ccc'" onfocus="input_focus('input')" onblur="input_blur('input')" value="" name="keywords" id="keywords" />
        <input class="btn" type="submit" value="搜索" />
		<input class="btn" type="button" value="提问" onclick="goUrl('question_add');return false;" />
    </form>
	</td>
	</tr>
</table>