<?= $this->render('home/index.phtml'); ?>
<!-- 管理条目 ///////////////////////////////////// -->
<div class="sidebar" style="width:160px">
<p class="toolbar">
<a href="/class/home?c=<?= $this->class_id ?>"><img src="/static/images/icon/arrow_undo.gif" /> 返回</a>
</p>
</div>

<div class="sidebar class_show" style="width:500px; padding:0 10px;">
<h2 class="quiet"><img src="/static/images/icon/group.gif" /> 成员管理</h2>
<p class="quiet">
<a href="javascript:memberList(<?= $this->class_id ?>)">成员列表(<?= $this->class_base_info['class_member_num'] ?>)</a> | 
<a href="javascript:managerList(<?= $this->class_id ?>)">管理员(<?= count($this->class_base_info['class_managers']) ?>)</a> | 
<a href="javascript:applyList(<?= $this->class_id ?>)">申请加入(<?= DbModel::getClassJoinApplyNum($this->class_id) ?>)</a>
</p>
<span id="listInner"></span>
</div>

<script><?= Zend_Registry::get('sessClass')->default['managerMember'] ?></script>

<!-- 班级基本信息 ///////////////////////////////////////// -->
<?= $this->render('home/baseinfo.phtml'); ?>