<div class="sidebar">

<form method="POST">
<div class="box">
<p class="tip"><img src="/static/images/icon/info.gif" align="absmiddle" /> 为了保证班级的唯一性，请在创建前确定没有相同班级存在。</p>

<h2>*班级入学年份：</h2>
<p>
<select class="inputtxt" name="year">
<option value="">选择年份：</option>
<?php for ($i=1970;$i<=2008;$i++): ?>
<option value="<?= $i ?>"<?php if($this->year == $i):?>selected="selected"<?php endif; ?>><?= $i ?></option>
<?php endfor; ?>
</select>
<span class="err_tip"><?= $this->err_tip['入学年份'] ?></span>
</p>

<h2>*学院名称：</h2>
<p>
<select class="inputtxt" name="college">
<option value="">选择学院：</option>
<?php foreach (Zend_Registry::get('iniClass')->college->name->toArray() as $k => $v): ?>
<option value="<?= $v ?>"<?php if($this->college == $v):?>selected="selected"<?php endif; ?>><?= $v ?></option>
<?php endforeach; ?>
</select>
<span class="err_tip"><?= $this->err_tip['学院名称'] ?></span>
</p>
			
<h2>*班级名称 <small>命名规范:如“化工962”</small></h2>
<p>
<input type="text" name="name" class="inputtxt" size="40" maxlength="25" />
<input type="submit" class="btn" value="创建" />
<input type="button" class="btn" onclick="history.back()" value="取消" />
</p>

<p>
	<span class="err_tip"><?= $this->err_tip['class_name'] ?></span>
	<span class="suc_tip"><?= $this->suc_tip ?></span>
</p>
</div>
</form>


</div>