<?php if(!$this->comments):  ?>
	没有回复
	<?php else: foreach($this->comments as $comment): ?>
	<div>
		<p class='commentUnit'>
			<?php echo $this->card($comment['user_id'], $comment['comment_username']); ?>
			<small><?= Commons::date($comment['comment_time']) ?></small>
			<?php if($this->login['username'] == 'zjuhz'):  ?>
			<a href="javascript:deleteComment(<?= $comment['comment_id'] ?>)">删除</a>
			<?php endif; ?>
		</p>
		<p class='commentcont'>
			<?= stripslashes($comment['comment_content']) ?>
		</p>
	</div>
	<?php endforeach; endif; ?>
	<div class="pagination"><?= $this->pagination ?></div>
	<script type="text/javascript">
		ucardInit();
		function deleteComment(id)
		{
			var t = confirm('确定删除该回复？');
			if(t == true){
				$.post('/info/comment/delete', {comment_id:id}, function(html){
					if(html != '') $.facebox(html);
					else history.go(0);
				});
			}
		}
	</script>