<?php if(!$this->comments):  ?>
	没有评论
	<?php else: foreach($this->comments as $comment): ?>
	<div>
		<p class='commentUnit'>
			<?php echo $this->card($comment['user_id'], $comment['comment_username']); ?>
			<small><?= Commons::date($comment['comment_time']) ?></small>
		</p>
		<p class='commentcont'>
			<?= stripslashes($comment['comment_content']) ?>
		</p>
	</div>
	<?php endforeach; endif; ?>
	<div class="pagination"><?= $this->pagination ?></div>
	<script type="text/javascript">
		ucardInit();
	</script>