<?php

	/**
	 * 求是寻根江西段
	 */	
	$this->headTitle('浙江大学求是寻根江西段');

?>

<style type="text/css">
.head{ 
	background:url(/static/subjects/qiushixungen-jiangxi/images/head-bg.jpg) no-repeat center bottom;
	width:840px;
	height:107px;
	padding:0 10px;
}
.container{ width:840px; padding:0 10px; }
a.thickbox{ border:1px solid #ccc; padding:5px; margin:5px; display:block; }
a.thickbox:hover{ border:1px solid #666; }
</style>
<div class="head mu10"></div>
<div class="sidebar container mu10">
	<!-- 文章展示 -->
	<div class="">
		<p>文字资料整理中..</p>
	</div>
	
	<!-- 相片展示 -->
	<div class="album">
		
	</div>
</div>

<script type="text/javascript">
$(document).ready(function($) {
	album('qiushixungen-jiangxi',1);
});
</script>