<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title></title>
</head>

<body>
<div style="width:100%;height:100%;text-align:center;">
  <div style="margin:15px 20px 0 20px;font-size:14px;line-height:16px;color:#000000;">
  <?= $this->message; ?>
  </div>
</div>
</body>
</html>
