<h2>添加信息分类</h2>
<div id="man">
<?php if($this->tips): ?>
  <p class="tips"><?= $this->tips ?></p>
  <?php endif; ?>
	<form method="POST">
		<p>
			<a href="javascript:icon_selector(0)">选择图标</a>
			<input size="13" type="text" value="<?= $row->category_icon ?>" name="cate_icon" id="c0"" /> 
		</p>
		<p>
		分类名称 <input type="text" name="cate_name" size="40" />
		<input type="hidden" value="0" name="cate_pub" />
		<label for="cate_pub"><input type="checkbox" value="1" name="cate_pub" id="cate_pub" />在首页显示</a>
		<input type="submit" value="创建" />
		</p>
	</form>
</div>
<script type="text/javascript">
function icon_selector(cid)
{
	var str = '<div style="width:700px">';
	<?php 
		$iconDir = dir('../../public/static/images/icon/');
		while (false !== ($entry = $iconDir->read())): if(strstr($entry,'.gif')): 
	?>
		str += '<a style="margin:5px; border-bottom:1px solid #ccc;" href="javascript:icon_selected('+cid+',\'<?= str_replace('.gif','',$entry) ?>\')"><img src="/static/images/icon/<?= $entry ?>" /></a>';
	<?php endif; endwhile; ?>
		str += '</div>'; 
	$.facebox(str);
}
</script>