<h2>未发布信息列表</h2>

<div id='man'>
  <table class="tb">
  	<tr>
  		<th>信息标题</th>
  		<th>发布人</th>
  		<th>所属类</th>
  		<th>时间</th>
  		<th width="10%">操作</th>
  	</tr>
  	<?php if(!$this->rows): ?>
  	<tr>
  		<td colspan="5">目前没有任何信息</td>
  	</tr>
  	<?php else: foreach ($this->rows as $k => $v): ?>
  	<tr id="post_<?= $v['entity_id'] ?>">
  		<td><a href="/info/view/detail/id/<?= $v['entity_id'] ?>"><?= stripslashes($v['entity_title']) ?></a></td>
  		<td><?= $v['user_name'] ?></td>
  		<td><?= $v['category_name'] ?></td>
  		<td><?= Commons::date($v['entity_pub_time']) ?></td>
  		<td>
  		<input type="hidden" name="entity_id" value="<?= $v['entity_id'] ?>" />
  		<input onclick="entity_pub(<?= $v['entity_id'] ?>)" type="button" value="发布" />
  		</td>
  	</tr>
  	<?php endforeach; endif; ?>
  </table>
</div>