<?= $this->render('group-head.phtml'); ?>
<div class="span-24 last">
	<div class="extInline" style="padding:0;">
		<h3 class="mglf10">
			<a href="/group/">校友群组</a> &gt;
			<a href="/group/sort?id=<?= $this->groupInfo['sort_id'] ?>"><?= Cmd::sortName($this->groupInfo['sort_id'])?></a> &gt;
			<a href="/group/home?gid=<?= $this->gid ?>"><?= $this->groupInfo['name'] ?></a> &gt;
			<a href="/group/topic?gid=<?= $this->gid ?>">论坛</a>
		</h3>
	</div>
</div>

<div class="span-24 last">
	<div class="oneCol pd10">
		<table width="100%">
			<tr>
				<td class="txtl">
					<?php if(count($this->pages) > 0): ?>
					<div class="pagination"><?= $this->pagination ?></div>
					<?php endif; ?>
				</td>
				<td class="txtr">
					<button class="btn" onclick="location.href='/group/topic/new?gid=<?= $this->gid ?>'">发新主题</button> 
					<button class="btn" onclick="window.scroll(0,10000)">回复主题</button> 
					<?php if(Cmd::isGuest($this->gid)): ?>
					<button class="btn" onclick="location.href='/group/join/new?gid=<?= $this->gid ?>'">加入群组</button>
					<?php endif; ?>
				</td>
			</tr>
		</table>
		<?php if($this->page == 1): // 第一页显示主题内容 ?>
		<table class="table-topic mgu10" width="100%">
			<tr>
				<td rowspan="2" class="photo txtc">
					<?= ($this->topic['is_nickname'] == 0) ? Commons::getUserFace($this->topic['pub_user']):'' ?>
					<p class="txtc" id="topic_user_0">
						<?php if($this->topic['is_nickname']!=1): ?>
						<a onclick="location.href='/group/member/profile?uid=<?= $this->topic['pub_user'] ?>'" href="javascript:ucard(<?= $this->topic['pub_user'] ?>)"><?= $this->topic['pub_user_name'] ?></a>
						<?php else: ?>
						<?= $this->topic['pub_nickname'] ?>
						<?php endif; ?>
					</p>
				</td>
				<td class="title txtr">
					<span class="f12 hrefspan-8">
						<?php if(Cmd::isMyTopic($this->topic['topic_id']) || Cmd::isManager($this->gid)): ?>
						
						<a href="/group/topic/edit?gid=<?= $this->gid ?>&tid=<?= $this->topic['topic_id'] ?>"><?= Cmd::icon('page_white_edit.png') ?>
						编辑</a>
						<?php endif; ?>
						<a href="javascript:quote(0)">#回复该帖</a>
						<a href="javascript:window.scroll(0,0)">#返回顶部</a>
						<?= Commons::date($this->topic['pub_time']) ?>
					</span>
				</td>
			</tr>
			<tr>
				<td id="topic_content_0" class="content" style="word-break:break-all;">
					<h2 style="margin-top:-30px;"><?= $this->topic['title'] ?></h2>
					<?= stripslashes($this->topic['content']); ?>
					<?php if($this->topic['mod_time']): ?>
					<p class="quiet f12 txtr" style="margin-bottom:-25px">***主题在<?= Lp_Date::timespan($this->topic['mod_time']) ?>前做了修改***</p>
					<?php endif; ?>
				</td>
			</tr>
		</table>
		<?php endif; ?>
		
		<?php if(count($this->replies) == 0): //回复部分 ?>
		<div class="extInline">还没有人回复哦～还不赶快抢占沙发？</div>
		<?php else: foreach($this->replies as $reply): ?>
			<table class="table-topic mgu10" width="100%">
				<tr>
					<td rowspan="2" class="photo txtc">
						<?= ($this->topic['is_nickname'] == 0)?Commons::getUserFace($reply['user_id']):'' ?>
						<p class="txtc" id="topic_user_<?= $reply['reply_id'] ?>">
							<?php if($this->topic['is_nickname'] == 0): ?>
							<a onclick="location.href='/group/member/profile?uid=<?= $reply['user_id'] ?>'" href="javascript:ucard(<?= $reply['user_id'] ?>)"><?= $reply['realName'] ?></a>
							<?php else: ?>
							<?= $reply['nickname'] ?>
							<?php endif; ?>
						</p>
					</td>
					<td class="title">&nbsp;
						<b id="topic_title_<?= $reply['reply_id'] ?>"><?= $reply['title'] ?></b>
						<span class="f12 hrefspan-8 txtr" style="float:right">
							<?php if($reply['user_id'] == Cmd::myid()): ?>
							<a href="/group/topic/replyedit?gid=<?= $this->gid ?>&tid=<?= $this->tid ?>&rid=<?= $reply['reply_id'] ?>&p=<?= $this->page ?>">
							<?= Cmd::icon('page_white_edit.png') ?>编辑</a>
							<?php endif; ?>
							<a href="javascript:quote(<?= $reply['reply_id'] ?>)">#回复该帖</a>
							<a href="javascript:window.scroll(0,0)">#返回顶部</a>
							<?= Commons::date($reply['reply_time']) ?>
						</span>
					</td>
				</tr>
				<tr>
					<td id="topic_content_<?= $reply['reply_id'] ?>" class="content" style="word-break:break-all;">
						<?= stripslashes($reply['content']); ?>
					</td>
				</tr>
			</table>
		<?php endforeach; ?>
		<?php if(count($this->pages) > 0): ?>
				<div class="pagination"><?= $this->pagination ?></div>
		<?php endif; ?>
		<?php endif;　//回复部分结束 ?>
		
		<div class="mgu10">
		<?php if(Cmd::isGuest($this->gid)): ?>	
			<div class="extInline2 txtr">
				提醒：只有该群组成员才能回帖~<a href="/group/join/new?gid=<?= $this->gid ?>">加入群组</a>。
				如果您还没有登录，请先<a href="/member/login/">登录</a>
			</div>
		<?php else: ?>	
		<form id="reply_form" method="post" onsubmit="return doReply()">
		<p class="mglf10"><label>回复标题：
			<input type="text" name="title" class="text" value="" style="width:88%" /></label></p>
		<span id="upload_form"></span>
		<input type="hidden" name="content" />
		<input type="hidden" name="gid" value="<?= $this->gid ?>" />
		<input type="hidden" name="tid" value="<?= $this->tid ?>" />
		<input type="hidden" name="to" value="<?= $this->to_page ?>" />
		<?= $this->editor($this->gid, '100%', '300px'); ?>
		<p><input type="submit" class="btn" style="width:100%" value="回 复" /></p>
		</form>
		<span id="tip"></span>
		<?php endif; ?>
		</div>
	</div>
</div>



<script type="text/javascript">
	<?php if($this->hash != null): ?>
		window.location.hash = 'topic_content_<?= $this->hash ?>';
	<?php endif; ?>
	
	function doReply()
	{
		$('.btn').attr("disabled", true);
		var data = $('#reply_form').fastSerialize();
		data.push({name:"content", value:editor.data()});
		$.post('/group/reply/new', data, function(html){
			$('#tip').html(html);
			window.scroll(0,10000);
		});
		return false;
	}
	function quote(id)
	{
		KE_CUSTOM_STR('<div class="quote"><h3>引用：'+$('#topic_user_'+id).html()+'</h3>'+$('#topic_content_'+id).html()+'</div><br /><br />');
		window.scroll(0,10000);
	}
	$(document).ready(function(){
		var t = window.setTimeout(function(){
			$('.content img').each(function(){
				if($(this).width()>720)
				{
					$(this).width(720);
					$(this).wrap('<a target="_blank" href="'+$(this).attr('src')+'"></a>');
				}
				else
				{
					$(this).width('auto');
					$(this).height('auto');
				}
			});
		},2000);
	});
	$('#upload_form').load('/group/file/upload?gid=<?= $this->gid ?>');
</script>