<div class="span-5">
    <div class="sideBar">
        <?= $this->sortbar(); ?>
    </div>
</div>

<div class="span-12">
    <div class="oneCol pdd10">
        <h3 class="pd10">最近我的主题</h3>
        <?= $this->mytopic(5); ?>
    </div>
    <div class="oneCol mgu10">
        <h3 class="pd10">新事件 <?= Cmd::icon('new.png') ?></h3>
        <?= $this->newevent(5); ?>
    </div>
</div>

<div class="span-7 last">
    <div class="oneCol">
        <?= $this->newgroup(); ?>
    </div>
    
    <div class="oneCol mgu10 pdd10">
        <?= $this->hotgroup(); ?>
    </div>
    
    <div class="sideBar mgu10 pdd10">
        <?= $this->hottopic(); ?>
    </div>
    
    <div class="sideBar2 mgu10 pdd10">
        <?= $this->hotclick(); ?>
    </div>
    
    <div class="oneCol mgu10" style="overflow:hidden;">
        <?= $this->online(); ?>
    </div>
</div>
        
