<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link rel="stylesheet" type="text/css" href="/static/styles/group/screen.css" media="screen" />
<script type="text/javascript" src="/static/scripts/jquery.js"></script>
<script type="text/javascript" src="/static/scripts/jquery.pngFix.pack.js"></script>
<script type="text/javascript" src="/static/scripts/common.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="zh-CN" />
<?php $this->headTitle('互动群组_杭州浙江大学校友会')->setSeparator('_'); ?>
<?= $this->headTitle(); ?>
</head>

<body>
	<div id="header" class="container">
		<div class="span-11">
			<a href="/"><img src="/static/images/group/zjuhz.gif" alt="群组" /></a>
		</div>
		<div class="span-13 last">
			<div id="passport" class="hrefspan-8 push-1 last">
				<?php if ($this->passport()): ?>
				您好！<?= $this->passport('realName') ?> 
				<a style="color:green" href="javascript:fastInvite()">邀请校友</a> 
				<a href="/group/my">我的群组</a>
				<a href="/group/pm/box">站内信(<?= GroupPmModel::no_read_num(Cmd::myid()); ?>)</a> 
				<a href="/member/my/">我的账号</a>
				<a href="/member/logout/" onClick="return window.confirm('确实要退出吗？');">退出</a>
				<?php else: ?>
				<a href="/member/register/">注册</a>
				<a href="/member/login/">登录</a>
				<?php endif; ?>
			</div>
			<div class="global-nav span-13 last hrefspan-8">
				<a href="/biz/">创业</a>
				<a href="/member/">校友</a>
				<a href="/info/">资讯</a>
				<a href="/help/">互助</a>
				<a href="/class/">班级</a>
				<a href="/group/" class="here">群组</a>
				<a href="/group/events/list">活动</a>
			</div>
		</div>
		
			<?= $this->layout()->nav; ?>
		
	</div>
	<div id="container" class="container">
		<span id="top_tip"></span>
		<?= $this->layout()->sidebar; ?>
		<?= $this->layout()->content; ?>
	</div>
	
	<div id="footer" class="container txtc hrefspan-8 pd10">
		<hr />
		<a href="/info/support/help">帮助</a>
		<a href="/info/support/about">关于</a>
		<a href="/info/support/contact_us">联系我们</a>
		<a href="/info/support/privacy_claim">隐私声明</a>
		<a href="http://www.zjuhz.com/old" target="_blank">旧版回顾</a>
		<a href="http://ourzju.uu1001.com" target="_blank">校友论坛</a>
		<a href="http://www.miibeian.gov.cn" target="_blank">浙ICP备06052510号</a>
		杭州浙江大学校友会(筹)&copy;2008
		<script type="text/javascript" src="http://js.tongji.cn.yahoo.com/705170/ystat.js"></script><noscript><a href="http://tongji.cn.yahoo.com"><img src="http://img.tongji.cn.yahoo.com/705170/ystat.gif"/></a></noscript>
	</div>
	<hr class="space" />
	<script type="text/javascript">
		$(document).ready(function(){
			$('.btn').hover(
				function(){$(this).css('background','#FFFF99')},
				function(){$(this).css('background','#D4D0C8')}
			);
			$('img[src$="png"]').parent().pngFix(); 
			var controller = $('div.sub-nav').attr('rel');
			$('div.sub-nav a[href*="'+controller+'"]').addClass('here');
			$('input[type="text"]').focus(function(){
				$(this).css('border','1px solid #666');
			});
			$('input[type="text"]').blur(function(){
				$(this).css('border','1px solid #bbb');
			});
			$('#top_tip').load('/group/index/toptip?gid=<?= $this->gid ?>');
			$.get('/group/index/click?gid=<?= $this->gid ?>'); // 统计访问量
			$.get('/group/index/user_active'); // 在线时间更新
		});
		
		function notip()
		{
			$('#top_tip').load('/group/index/toptip?close=1',null,function(){
				$('#top_tip').remove();	
			});
		}
		ucardInit();
	</script>
</body>
</html>