<style>
#login{ padding:10px 40px; }
#login h2{ padding:0 15px; }
#login h2 small{ font-size:12px; font-weight:normal; float:right; margin-top:-20px; }
#register_form{ margin:20px; width:95% }
#register_form td{ padding:5px; }
</style>
<div id="ajaxloading"></div>
<div id="login">

    <form name="frmRegister" id="frmRegister" method="post" autocomplete="off">
    <h2 class="quiet"><img src="/static/images/icon/write.gif" /> 注册帐号 
    <small>已拥有帐号？请<a href="/member/">直接登录</a></small></h2>
    <hr />
    <table id="register_form">
    <tr>
    	<td>账号：</td>
    	<td><input name="uname" id="uname" tabindex="1" class="inputtxt" type="text" maxlength="16" value="" />
    		<input type="button" id="btnCheck" class="btn" style="height:22px" name="btnCheck" value="检查账号是否可用"> 
    		<span id="chkmsg" class="quiet">3-16位的字母、数字、下划线</span></td>
    </tr>
    <tr>
    	<td>密码：</td>
    	<td><input name="pswd" tabindex="2" class="inputtxt" type="password" maxlength="16" value="" onkeyup="EvalPwdStrength(document.forms[0],this.value);" /> 
    		<span class="quiet">6-16位的任意字符，不区分大小写。强度检测：</span></td>
    </tr>
    <tr>
    	<td colspan="2">
				    <table class="pwdChkTbl2" id="checkTD" cellSpacing="0" cellPadding="0" style="width:400px;">
				    <tr>
				      <td class="pwdChkCon0" id="idSM1" align="middle" width="25%">
					  <span style="font-size: 1px">&nbsp;</span>
					  <span id="idSMT1" style="display: none">不安全</span>
					  </td>
				      <td class="pwdChkCon0" id="idSM2" style="border-left: #fff 1px solid" align="middle" width="25%">
					  <span style="font-size: 1px">&nbsp;</span>
					  <span id="idSMT0" style="display: inline; font-weight: normal; COLOR: #666">未评级</span>
					  <span id="idSMT2" style="display: none">普通</span>
					  </td>
				      <td class="pwdChkCon0" id="idSM3" style="border-left: #fff 1px solid" align="middle" width="25%">
					  <span style="font-size: 1px">&nbsp;</span>
					  <span id="idSMT3"" style="display: none">安全</span>
					  </td>
				      <td class="pwdChkCon0" id="idSM4" style="border-left: #fff 1px solid" align=middle width="25%">
					  <span style="font-size: 1px">&nbsp;</span>
					  <span id="idSMT4"" style="display: none">最佳</span>
					  </td>
					</tr>
					</table>
    	</td>
    </tr>
    <tr>
    	<td>密码确认：</td>
    	<td><input name="repswd" tabindex="3" class="inputtxt" type="password" maxlength="16" value="" />
    		<span class="quiet">请再次输入密码以确认</span></td>
    </tr>
    <tr>
    	<td>真实姓名：</td>
    	<td><input name="rname" tabindex="4" class="inputtxt" type="text" maxlength="6" /> 
    	<span class="quiet">至少2字以上，且不能含有数字和符号</span></td>
    </tr>
    <tr>
    	<td>性别：</td>
    	<td><input name="sex" tabindex="5" type="radio" value="男" checked="checked" /> 男 <input type="radio" name="sex" value="女" /> 女 </td>
    </tr>
    <tr>
    	<td>验证码：</td>
    	<td><input type="text" class="inputtxt" name="vcode" id="vcode" tabindex="6" maxlength="4">
    	<span id="putVerifyImg"></span> <span class="quiet">请输入上图中的数字，点击图片可刷新</span></td>
    </tr>
    <tr>
    	<td colspan="2"><input type="submit" id="btnRegister" name="btnRegister" tabindex="7" value="同意以下服务条款，提交注册信息" class="btn" /></td>
    </tr>
    <tr>
    <td colspan="2"><div id="ajaxhint" style="width:300px"></div></td>
    </tr>
    <tr>
    	<td><input type="hidden" name="ikey" value="<?= $this->ikey; ?>" /></td>
		<td><input type="hidden" name="isPutVerifyImg" id="isPutVerifyImg" value="show" /></td>
    </tr>
    </table></form></div>