<div class="sidebar" style="padding:20px; border:1px solid #CDD8EF; background:#EFF7F7; width:750px; margin:16px;">
<?php if ($this->register) { ?>
<h2><img src="/static/images/icon/done.gif" />亲爱的<?= $this->register['realName']; ?>：您的账号已经注册成功，欢迎加入！</h2>
<hr />
<div class="sidebar">
<p class="pud5"><b class="quiet">我们目前提供以下服务，有需要改进的地方欢迎与我们联系：</b></p>
<ul class="quiet">
<li><a href="/class/">资讯</a></li>
<li><a href="/help/">互助</a></li>
<li><a href="/class/">班级</a></li>
</ul>
</div>

<?php if ($this->register['classes'] && 0 < $this->register['uid']) { ?><script language="javascript">$.post('/class/ajax/joinapplydirect/', {uid: <?= $this->register['uid']; ?>, realName: '<?= $this->register['realName']; ?>', sex: '<?= $this->register['sex']; ?>', class_id: '<?= $this->register['classes']; ?>'}, function(msg) {});</script><?php unset($_SESSION['member']['register']['classes']); } ?>

<?php } else { ?>
<h2><img src="/static/images/icon/stop.gif" />亲爱的校友：很遗憾，本次注册失败。</h2>
<hr />
<div class="sidebar">
<p class="pud5"><b class="quiet">导致失败的原因可能是：</b></p>
<ul class="quiet">
<li><b>您的真实姓名与邀请资料不相符。</b>(请与给您邀请码的那位校友联系，并让对方检查邀请资料)</li>
<li><b>您的邀请码已使用过。</b>(每个邀请码在注册成功后即失效，请确认您未使用过，或与给您邀请码的那位校友联系)</li>
<li><b>您没有邀请码。</b>(网站采名实名邀请制，您可向已注册的校友索取邀请码或与直接我们联系)</li>
<li><b>您填写的登录账号被占用。</b>(请注意在填写登录账号右侧的提示信息，若账号不可用并在注册页面更换)</li>
</ul>
<br />
<p class="pud5"><b class="quiet">仍未解决您的问题？请与我们联系，电话：0571-89988185</b></p>
</div>
<?php } ?>
</div>