<?= $this->render('home/index.phtml'); ?>
<!-- 管理条目 ///////////////////////////////////// -->
<div class="sidebar" style="width:160px">
<p class="toolbar">
<a href="/class/home?c=<?= $this->class_id ?>"><img src="/static/images/icon/arrow_undo.gif" /> 返回</a>
</p>
</div>

<div class="sidebar class_show" style="width:500px; margin:0 10px;">
<h2 class="quiet"><img src="/static/images/icon/user.gif" /> 邀请加入班级</h2>
<form id="invite_form" onsubmit="return inviteSearch();">
<p>
	<input name="class_id" type="hidden" value="<?= $this->class_id ?>" />
	输入名字 <input name="realname" type="text" class="inputtxt"> 
	<input type="submit" class="btn" value="查找" />
</p>
</form>
<span id="userList"></span>
</div>

<!-- 班级基本信息 ///////////////////////////////////////// -->
<?= $this->render('home/baseinfo.phtml'); ?>