<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="zh-CN" />
<?= $this->headMeta(); ?>
<script type="text/javascript" src="/static/scripts/jquery.js"></script>
<script type="text/javascript" src="/static/scripts/common.js"></script>
<script type="text/javascript" src="/static/scripts/popup.js"></script>
<script type="text/javascript" src="/static/scripts/biz/company.js"></script>