<div class="span-5">
    <div class="sideBar">
        <?= $this->sortbar(); ?>
    </div>
</div>

<div class="span-12">
        <?= $this->mytopic($this->passport('lastLogin'), 5); ?>
    <div class="oneCol mgu10">
        <?= $this->newevents(5); ?>
    </div>
    <div class="oneCol mgu10">
        <h3 class="pd10">新事件 <?= Cmd::icon('new.png') ?></h3>
        <?= $this->newevent(5); ?>
    </div>
    <div class="pd10" style="background:#f5f5f5; line-height:150%">
        <?= Cmd::icon('user_gray.png') ?>
        <a href="/group/sort?id=12">同行会</a> <?= $this->sortgroup(12,5); ?>
    </div>
    <div class="pd10" style="background:#eee; line-height:150%">
        <?= Cmd::icon('cup.png') ?>
        <a href="/group/sort?id=14">同乡会</a> <?= $this->sortgroup(14,5); ?>
    </div>
    <div class="pd10" style="background:#f5f5f5; line-height:150%">
        <?= Cmd::icon('coins.png') ?> 财富 
        <?= $this->sortgroup(21,5); ?> ,
        <?= $this->sortgroup(22,5); ?>
    </div>
    <div class="pd10" style="background:#eee; line-height:150%">
        <?= Cmd::icon('sport_soccer.png') ?> 体育 
        <?= $this->sortgroup(31,5); ?> ,
        <?= $this->sortgroup(32,5); ?>
    </div>
    <div class="pd10" style="background:#f5f5f5; line-height:150%">
        <?= Cmd::icon('heart.png') ?> 交友 
        <?= $this->sortgroup(51,5); ?>
    </div>
    <div class="pd10" style="background:#eee; line-height:150%">
        <?= Cmd::icon('folder.png') ?> 其他 
        <?= $this->sortgroup(99,5); ?>
    </div>
</div>

<div class="span-7 last">
    <div class="oneCol">
        <?= $this->newgroup(); ?>
    </div>
    
    <div class="oneCol mgu10 pdd10">
        <!-- 我的群组快速连接 -->
        <p class="f12 mglf10"><b>参与的群组</b>: 
        <?php if(Zend_Registry::get('sessGroup')->my) : foreach(Zend_Registry::get('sessGroup')->my as $val): ?>
        <a href="/group/home?gid=<?= $val['group_id'] ?>"><?= $val['name'] ?></a> - 
        <?php endforeach; endif; ?>
        </p>
    </div>
    
    <div class="oneCol mgu10 pdd10">
        <?= $this->hotgroup(); ?>
    </div>
    
    <div class="sideBar mgu10 pdd10">
        <?= $this->hottopic(); ?>
    </div>
    
    <div class="sideBar2 mgu10 pdd10">
        <?= $this->hotclick(); ?>
    </div>
    
    <div class="oneCol mgu10" style="overflow:hidden;">
        <?= $this->online(); ?>
    </div>
</div>
        
