<?php $active = 'class="on"' ?>
<a href="/info/" <?php echo $this->module == 'info'  ? $active : '' ?>>资讯</a>
<a href="/help/" <?php echo $this->module == 'help' ? $active : '' ?>>互助</a>
<a href="/class/" <?php echo $this->module == 'class' ? $active : '' ?>>班级</a>
<a href="/member/" <?php echo $this->module == 'member' ? $active : '' ?>>校友</a>
<a href="/blog/" <?php echo $this->module == 'blog' ? $active : '' ?>>日志</a>
<a href="/play/" <?php echo $this->module == 'play' ? $active : '' ?>>活动</a>