<div id="gb-box">
    <div class="gb-item">
		<div class="gb-title"><a href="">KFC</a> <small>08-06-13 07:20</small></div>
		<div class="gb-content">
			从浙大数学系毕业的校友，你如果去参会，可能很快就能出国际学术论文了。
			朱军副校长是统计学博士，所有他积极推动此项目。他总是积极鼓动企业在生物学上投资。他也是生物学博士。
			<div class="gb-reply">企业主回复：这是回复的内容...</div>
		</div>
	</div>
	
	<div class="gb-item">
		<div class="gb-title"><a href="">KFC</a> <small>08-06-13 07:20</small></div>
		<div class="gb-content">
			从浙大数学系毕业的校友，你如果去参会，可能很快就能出国际学术论文了。
			朱军副校长是统计学博士，所有他积极推动此项目。他总是积极鼓动企业在生物学上投资。他也是生物学博士。
			<div class="gb-reply">企业主回复：这是回复的内容...</div>
		</div>
	</div>
	
	<div class="pagination" style="clear:both;"><b>1</b><a href="/info/?category=1&amp;p=2">2</a><a href="/info/?category=1&amp;p=2">下页</a><a href="/info/?category=1&amp;p=2">最后页</a></div>
	
	<div class="gb-reply-box">
	<textarea style="width:80%; height:100px;"></textarea>
	<label style="width:80%" class="txtr pd10"><input type="submit" value="发表留言" class="buttonGreen" /></label>
	</div>
	
	</div>