<p class="err_message">您需要登录后才能继续刚才的操作。</p>
<form method="post" id="relogin_form" name="relogin_form" onsubmit="return relogin();">
<p>登录账号：<input class="inputtxt" id="uname" name="uname" type="text" maxlength="16" value="<?= $this->uname; ?>" /></p>
<p>登录密码：<input class="inputtxt" id="pswd" name="pswd" type="password" maxlength="16" value="<?= $this->uname; ?>" /></p>
<p>下次自动登录：<input id="alive" type="checkbox" <?= ($this->uname) ? 'checked="checked"':'' ?> value="0" name="alive" /></p>
<p></p>
<button class="btn" onclick="location.href='/member/register/'">注册账号</button>&nbsp;<input class="btn" id="btnLogin" name="btnLogin" type="submit" value="登录" />
</form>

<script type="text/javascript">
	<?php if($this->uname && $this->pswd): ?>
    relogin();
    <?php endif; ?>
	// 会员登录
	function relogin() {
		var formdata = $("#relogin_form").fastSerialize();
	
		$.post("/member/login/dologin/", formdata, function(msg) {
			if ("redirect" == msg) {
				history.go(0);
			}
			else alert(msg);
		});
	
		return false;
	}	
</script>