<div class="help_category">
<h2 class="fw14">问题分类</h2>
<p>
<a href="/help/sort/browse/sid/2/" class="M">教育/学业/考试</a>
<br />
<a href="/help/sort/browse/sid/26/">胎教</a>
<a href="/help/sort/browse/sid/27/">幼教</a>
<a href="/help/sort/browse/sid/28/">小学</a>
<a href="/help/sort/browse/sid/29/">初/高中</a>
<br />
<a href="/help/sort/browse/sid/30/">大学</a>
<a href="/help/sort/browse/sid/31/">硕/博士</a>
<a href="/help/sort/browse/sid/34/">职业培训</a>
<a href="/help/sort/browse/sid/2/">..</a>
</p>

<p>
<a href="/help/sort/browse/sid/3/" class="M">科研</a>
<br />
<a href="/help/sort/browse/sid/35/">研究方法/思路</a>
<a href="/help/sort/browse/sid/36/">资源共享</a>
</p>

<p>
<a href="/help/sort/browse/sid/4/" class="M">招聘/求职</a>
<br />
<a href="/help/sort/browse/sid/37/">职场心态</a>
<a href="/help/sort/browse/sid/38/">工作机会</a>
</p>

<p>
<a href="/help/sort/browse/sid/25/" class="M">我有烦恼</a>
<br />
<a href="/help/sort/browse/sid/118/">职场</a>
<a href="/help/sort/browse/sid/119/">恋爱</a>
<a href="/help/sort/browse/sid/120/">婚姻家庭</a>
<a href="/help/sort/browse/sid/121/">人际关系</a>
</p>

<p>
<a href="/help/sort/browse/sid/5/" class="M">电脑/网络</a>
<br />
<a href="/help/sort/browse/sid/39/">硬件</a>
<a href="/help/sort/browse/sid/40/">软件</a>
<a href="/help/sort/browse/sid/41/">互联网</a>
<a href="/help/sort/browse/sid/42/">杀毒</a>
</p>

<p>
<a href="/help/sort/browse/sid/6/" class="M">生活/时尚</a>
<br />
<a href="/help/sort/browse/sid/43/">生活百科</a>
<a href="/help/sort/browse/sid/44/">服装服饰</a>
<a href="/help/sort/browse/sid/46/">宠物</a>
<br />
<a href="/help/sort/browse/sid/45/">购物消费</a>
</p>

<p>
<a href="/help/sort/browse/sid/7/" class="M">电子数码</a>
<br />
<a href="/help/sort/browse/sid/47/">收音机</a>
<a href="/help/sort/browse/sid/49/">手机</a>
<a href="/help/sort/browse/sid/50/">数码相机</a>
<br />
<a href="/help/sort/browse/sid/48/">音乐播放器</a>
<a href="/help/sort/browse/sid/51/">DV</a>
</p>

<p>
<a href="/help/sort/browse/sid/8/" class="M">购车养车</a>
<br />
<a href="/help/sort/browse/sid/52/">汽车知识</a>
<a href="/help/sort/browse/sid/53/">购车常识</a>
<br />
<a href="/help/sort/browse/sid/54/">车辆养护</a>
</p>

<p>
<a href="/help/sort/browse/sid/9/" class="M">体育/运动</a>
<br />
<a href="/help/sort/browse/sid/55/">足球/篮球</a>
<a href="/help/sort/browse/sid/56/">羽毛球/乒乓球</a>
<br />
<a href="/help/sort/browse/sid/58/">健身</a>
<a href="/help/sort/browse/sid/59/">体育知识</a>
<a href="/help/sort/browse/sid/60/">运动保护</a>
<a href="/help/sort/browse/sid/9/">..</a>
</p>

<p>
<a href="/help/sort/browse/sid/10/" class="M">美容/减肥/化妆</a>
<br />
<a href="/help/sort/browse/sid/61/">美白/防晒</a>
<a href="/help/sort/browse/sid/62/">减肥</a>
<a href="/help/sort/browse/sid/63/">化妆品</a>
</p>

<p>
<a href="/help/sort/browse/sid/11/" class="M">美食/烹饪</a>
<br />
<a href="/help/sort/browse/sid/64/">烹饪常识</a>
<a href="/help/sort/browse/sid/65/">海鲜</a>
<a href="/help/sort/browse/sid/66/">酒类/饮品</a>
</p>

<p>
<a href="/help/sort/browse/sid/12/" class="M">商业/理财</a>
<br />
<a href="/help/sort/browse/sid/67/">个人理财</a>
<a href="/help/sort/browse/sid/68/">税务知识</a>
<br />
<a href="/help/sort/browse/sid/69/">财务知识</a>
<a href="/help/sort/browse/sid/70/">证券投资</a>
</p>

<p>
<a href="/help/sort/browse/sid/13/" class="M">健康/养生</a>
<br />
<a href="/help/sort/browse/sid/71/">保健常识</a>
<a href="/help/sort/browse/sid/72/">心理健康</a>
</p>

<p>
<a href="/help/sort/browse/sid/14/" class="M">医疗/疾病</a>
<br />
<a href="/help/sort/browse/sid/73/">外科</a>
<a href="/help/sort/browse/sid/74/">内科</a>
<a href="/help/sort/browse/sid/75/">心血管</a>
<br />
<a href="/help/sort/browse/sid/76/">妇/产科</a>
<a href="/help/sort/browse/sid/77/">儿科</a>
</p>

<p>
<a href="/help/sort/browse/sid/15/" class="M">外语/出国</a>
<br />
<a href="/help/sort/browse/sid/78/">英语</a>
<a href="/help/sort/browse/sid/79/">日语</a>
<a href="/help/sort/browse/sid/80/">德语</a>
<a href="/help/sort/browse/sid/81/">法语</a>
<br />
<a href="/help/sort/browse/sid/82/">其它语种</a>
<a href="/help/sort/browse/sid/83/">留学</a>
</p>

<p>
<a href="/help/sort/browse/sid/16/" class="M">交通/旅游</a>
<br />
<a href="/help/sort/browse/sid/84/">省内游</a>
<a href="/help/sort/browse/sid/85/">国内游</a>
<a href="/help/sort/browse/sid/87/">旅游常识</a>
<br />
<a href="/help/sort/browse/sid/86/">国外游</a>
<a href="/help/sort/browse/sid/88/">户外装备</a>
<a href="/help/sort/browse/sid/89/">驾驶驾照</a>
<a href="/help/sort/browse/sid/16/">..</a>
</p>

<p>
<a href="/help/sort/browse/sid/17/" class="M">人文学科</a>
<br />
<a href="/help/sort/browse/sid/93/">中国文学</a>
<a href="/help/sort/browse/sid/92/">哲学</a>
<a href="/help/sort/browse/sid/91/">政治学</a>
</p>

<p>
<a href="/help/sort/browse/sid/18/" class="M">理工学科</a>
<br />
<a href="/help/sort/browse/sid/94/">数学</a>
<a href="/help/sort/browse/sid/95/">物理学</a>
<a href="/help/sort/browse/sid/96/">建筑学</a>
</p>

<p>
<a href="/help/sort/browse/sid/19/" class="M">社会/文化</a>
<br />
<a href="/help/sort/browse/sid/97/">社会话题</a>
<a href="/help/sort/browse/sid/98/">节假日</a>
<a href="/help/sort/browse/sid/99/">民俗传统</a>
</p>

<p>
<a href="/help/sort/browse/sid/20/" class="M">艺术</a>
<br />
<a href="/help/sort/browse/sid/100/">书法/美术</a>
<a href="/help/sort/browse/sid/101/">器乐</a>
<a href="/help/sort/browse/sid/102/">诗词歌赋</a>
</p>

<p>
<a href="/help/sort/browse/sid/21/" class="M">音乐</a>
<br />
<a href="/help/sort/browse/sid/103/">流行音乐</a>
<a href="/help/sort/browse/sid/104/">严肃音乐</a>
<a href="/help/sort/browse/sid/105/">外国音乐</a>
<br />
<a href="/help/sort/browse/sid/106/">民族音乐</a>
<a href="/help/sort/browse/sid/107/">摇滚乐</a>
</p>

<p>
<a href="/help/sort/browse/sid/22/" class="M">游戏</a>
<br />
<a href="/help/sort/browse/sid/108/">网游</a>
<a href="/help/sort/browse/sid/109/">单机游戏</a>
<a href="/help/sort/browse/sid/110/">TV游戏/街机</a>
</p>

<p>
<a href="/help/sort/browse/sid/23/" class="M">休闲/爱好</a>
<br />
<a href="/help/sort/browse/sid/111/">摄影摄像</a>
<a href="/help/sort/browse/sid/112/">花鸟鱼虫</a>
<a href="/help/sort/browse/sid/113/">收藏</a>
</p>

<p>
<a href="/help/sort/browse/sid/24/" class="M">娱乐/明星</a>
<br />
<a href="/help/sort/browse/sid/114/">电影</a>
<a href="/help/sort/browse/sid/115/">电视</a>
<a href="/help/sort/browse/sid/116/">华人明星</a>
<a href="/help/sort/browse/sid/117/">国外明星</a>
</p>

</div>