<?= $this->render('group-head.phtml'); ?>
<div class="span-24 last">
	<?= $this->render('sidebar.phtml'); ?>
    <div class="span-19 last mgu10">
        <!-- 新图片 -->
        <div class="oneCol">
            <?php if($this->role == false): ?>
            <div class="notice mg10">抱歉，非本群组成员不能发布图片。<a href="/group/join/new?gid=<?= $this->gid ?>">申请加入</a></div>
            <?php else: ?>
            <h3 class="pd10">发布新图片</h3>
            <form style="margin-left:30px;" target="doUpload" name="pic_form" action="/group/album/upload?gid=<?= $this->gid ?>" method="post" enctype="multipart/form-data">
                <input type="hidden" name="batch" value="<?= Commons::getRandomStr(time(), 10); ?>" />
                <p id="album_tip"></p>
                <p>从您的电脑中选择图片:</p>
                <p>1. <input type="file" name="pic[]" value="" size="50" /></p>
                <p>2. <input type="file" name="pic[]" value="" size="50" /></p>
                <p>3. <input type="file" name="pic[]" value="" size="50" /></p>
                <p>4. <input type="file" name="pic[]" value="" size="50" /></p>
                <p>5. <input type="file" name="pic[]" value="" size="50" /></p>
                <p class="quiet">支持jpg、gif、png格式图片，每张限2M以内</p>
                <p>
                    <input class="btn" onclick="doupload()" type="submit" value="上传图片" /> &nbsp;
                    <input onclick="history.back()" class="btn" type="button" value="取消" />
                </p>
                <iframe id="doUpload" class="" name="doUpload"></iframe>
            </form>
            <?php endif; ?>
        </div>
    </div>
</div>
            
<script type="text/javascript">
    function setTip(html)
    {
        $('#album_tip').html(html);
    }
    function doupload()
    {
        setTip("<img src='/static/images/facebox/loading.gif' /> 图片上传中，请等待..");
    }
</script>