<?= $this->render('group-head.phtml'); ?>
<div class="span-24 last">
	<?= $this->render('sidebar.phtml'); ?>
    <div class="span-19 last mgu10">
        <!-- 设置图片信息 -->
        <div class="oneCol">
            <h3 class="pd10">填写图片信息</h3>
            <?= $this->tip; ?>
            <form method="post">
            <?php foreach($this->pics as $pic): ?>
                <div style="margin:10px 30px; background:#fff" class="extInline">
                    <table>
                        <tr>
                            <td style="vertical-align:top" class="pd10">
                                <input type="hidden" name="ablum_id[]" value="<?= $pic['album_id'] ?>" />
                                <img src="<?= $this->dir.'sample_'.$pic['file'] ?>" />
                            </td>
                            <td>
                                <p>标题 <input name="title[]" type="text" class="text" value="<?= $pic['title'] ?>" /></p>
                                <p>标签 <input name="tags[]" type="text" class="text" value="" /></p>
                                <p>
                                    <span style="vertical-align:top">描述</span>
                                    <textarea name="intro[]" class="text" style="width:400px; height:100px"></textarea>
                                </p>
                            </td>
                        </tr>
                    </table>
                </div>
            <?php endforeach; ?>
            <p class="extInline txtc" style="margin:10px 30px">
                <input type="submit" class="btn" value="保存" style="width:300px" />
                &nbsp;&nbsp;&nbsp; <a href="/group/album?gid=<?= $this->gid ?>">返回相册 </a>
            </p>
            </form>
        </div>
    </div>
</div>