<!-- 一些操作 //////////////////////////////////////// -->
<div class="sidebar class_sub_bar">
<form action="search" method="GET">
<p><b>入学年份：</b><br />
<select name="year" class="inputtxt" style="width:180px">
<option value="">不限制</option>
<?php for ($i=1970;$i<=2008;$i++): ?>
<option value="<?= $i ?>"<?php if($this->year == $i):?>selected="selected"<?php endif; ?>><?= $i ?></option>
<?php endfor; ?>
</select>
</p>

<p><b>院系名称：</b><br />
<select name="college" class="inputtxt" style="width:180px">
<option value="">所有学院</option>
<?php foreach ($this->college() as $v): ?>
<option value="<?= $v ?>"<?php if($this->college == $v):?>selected="selected"<?php endif; ?>><?= $v ?></option>
<?php endforeach; ?>
</select>
<input type="hidden" name="for" value="<?= $this->keywords ?>" />
</p>
<p><input type="submit" value="查找班级" class="btn" /></p>
</form>
<?= $this->render('index/mycorrelation.phtml'); ?>
<?= $this->render('index/myclass.phtml'); ?>
<?= $this->render('index/myapply.phtml'); ?>
<?= $this->render('index/myinvite.phtml'); ?>
</div>

<!-- 所有班级公开话题表格 ///////////////////////////////// -->
<table class="mz-table" cellpadding="0" cellspacing="0" width="620" style="margin-top:10px;">
<thead>
	<tr>
		<th class="top-left" colspan="2" width="50%">班级开放话题</th>
		<th width="20%">发布人(班级)</th>
		<th width="10%">回复</th>
		<th class="top-right" width="20%">最后回复</th>
	</tr>
</thead>
<tbody>
	<?php if($this->pub_topics): foreach($this->pub_topics as $k => $topic): ?>
	<tr<?php if($k%2==1) echo ' class="even"'; ?>>
		<td class="left" colspan="2"><a target="_blank" href="/class/topic/view?c=<?= $topic['class_id'].'&tid='.$topic['class_topic_id'] ?>"><?= $topic['class_topic_title'] ?></a></td>
		<td><a href="#<?= $topic['uid'] ?>"><?= $topic['topicAuthor'] ?></a> (<a href="/class/home?c=<?= $topic['class_id']?>"><?= $topic['class_name'] ?></a>)<br />
		<span class="f9"><?= Commons::date($topic['class_topic_pub_time']) ?></span></td>
		<td><?= $topic['class_topic_reply_num'] ?></td>
		<td class="right"><a href="#<?= $topic['replyUid'] ?>"><?= $topic['replyAuthor'] == '' ? '无':$topic['replyAuthor'] ?></a> <br /><span class="f9"><?= Commons::date($topic['class_topic_last_reply_time']) ?></span></td>
	</tr>
	<?php endforeach; else: ?>
	<tr>
		<td colspan="5">还没有任何开放的话题..</td>
	</tr>
	<?php endif; ?>
</tbody>
<tfoot>
	<tr>
		<td class="bottom-left" colspan="3"></td>
		<td class="bottom-right" colspan="2"></td>
	</tr>
</tfoot>
</table>
<div class="pagination"><?= $this->topic_pagination ?></div>

<!-- 网站内所有班级列表 /////////////////////////////////// -->
<div class="sidebar">
<table class="class_list">
<tr>
<th>入学年</th>
<th>学院</th>
<th>班级 (<?= $this->class_num ?>个)</th>
<th>创建人</th>
<th>&nbsp;</th>
</tr>
<?php if(count($this->class_rows) > 0):
foreach ($this->class_rows as $k => $v): ?>
<tr>
<td><a href="?year=<?= $v['class_year'] ?>"><?= $v['class_year'] ?></a></td>
<td><a href="?college=<?= urlencode($v['class_college']) ?>"><?= $v['class_college'] ?></a></td>
<td><a href="/class/home?c=<?= urlencode($v['class_id']) ?>"><?= $v['class_name'] ?></a></td>
<td><a href="/member/home?uid=<?= $v['class_charge'] ?>"><?= $v['realName'] ?></a> 
<a href="javascript:sendMessage(<?= $v['class_charge'] ?>)"><img src="/static/images/icon/email-s.gif" /></a></td>
<td><a href="javascript:classJoin(<?= $v['class_id'] ?>)">加入</a></td>
</tr>
<?php endforeach; else: ?>
<tr><td colspan="5">没有找到相关班级</td></tr>
<?php endif; ?>
</table>
<div class="pagination"><?= $this->class_pagination ?></div>
</div>

