<!-- 一些操作 //////////////////////////////////////// -->
<div class="sidebar class_sub_bar">
<form method="GET">
<p><b>入学年份：</b><br />
<select name="year" class="inputtxt" style="width:180px">
<option value="">不限制</option>
<?php for ($i=1970;$i<=2008;$i++): ?>
<option value="<?= $i ?>"<?php if($this->year == $i):?>selected="selected"<?php endif; ?>><?= $i ?></option>
<?php endfor; ?>
</select>
</p>

<p><b>院系名称：</b><br />
<select name="college" class="inputtxt" style="width:180px">
<option value="">所有学院</option>
<?php foreach (Zend_Registry::get('iniClass')->college->name->toArray() as $k => $v): ?>
<option value="<?= $v ?>"<?php if($this->college == $v):?>selected="selected"<?php endif; ?>><?= $v ?></option>
<?php endforeach; ?>
</select>
<input type="hidden" name="for" value="<?= $this->keywords ?>" />
</p>
<p><input type="submit" value="查找班级" class="btn" /></p>
</form>
<?= $this->render('index/myclass.phtml'); ?>
<?= $this->render('index/myapply.phtml'); ?>
<?= $this->render('index/myinvite.phtml'); ?>
</div>

<!-- 网站内所有班级列表 /////////////////////////////////// -->
<div class="sidebar">
<table class="class_list">
<tr>
<th>入学年</th>
<th>学院</th>
<th>班级 (<?= $this->class_num ?>个)</th>
<th>创建人</th>
<th>&nbsp;</th>
</tr>
<?php if(count($this->class_rows) > 0):
foreach ($this->class_rows as $k => $v): ?>
<tr>
<td><a href="?year=<?= $v['class_year'] ?>"><?= $v['class_year'] ?></a></td>
<td><a href="?college=<?= urlencode($v['class_college']) ?>"><?= $v['class_college'] ?></a></td>
<td><a href="/class/home?c=<?= urlencode($v['class_id']) ?>"><?= $v['class_name'] ?></a></td>
<td><a href="/member/home?uid=<?= $v['class_charge'] ?>"><?= $v['realName'] ?></a> 
<a href="javascript:sendMessage(<?= $v['class_charge'] ?>)"><img src="/static/images/icon/email-s.gif" /></a></td>
<td><a href="javascript:classJoin(<?= $v['class_id'] ?>)">加入</a></td>
</tr>
<?php endforeach; else: ?>
<tr><td colspan="5">没有找到相关班级</td></tr>
<?php endif; ?>
</table>
<div class="pagination"><?= $this->pagination ?></div>
</div>

