<?php 
$data = Zend_Registry::get('sessClass')->data;
if($data == null): ?>
<p style="border-top:1px solid #ccc; margin-top:10px">
<b>你目前还没自己的班级</b><br />
找不到自己的班级？那么您可以 <button onclick="location.href='/class/new'" class="btn">创建班级</button></p>
<?php else: ?>
<ul><b>我的班级：</b><br />
<?php foreach ($data as $k => $v): ?>
<li><a href="/class/home?c=<?= $k ?>"><?= $v['class_name'] ?></a></li>
<?php endforeach; ?>
</ul>
<?php endif; ?>