<div class="sidebar topic">
	<div class="author">
		<table width="100%">
		<tr>
			<td width="15%" class="txtc pu10" valign="top">
				<img src="/static/users/user_test/tiny_head.jpg" />
				<p class="f14"><a href=""><?= $this->topic['topicAuthor'] ?></a></p>
			</td>
			<!-- 话题内容 ////////////////////////// -->
			<td width="85%">
				<h2 class="f14"><?= stripslashes($this->topic['class_topic_title']) ?></h2>
				<p class="p8 bg-fblue quiet">
				发布: <?= Commons::date($this->topic['class_topic_pub_time']) ?>  
				<?php if($this->topic['class_topic_mod_time'] != null): ?>
				 / 最后修改: <?= Commons::date($this->topic['class_topic_mod_time']) ?> 
				<?php endif; if($this->topic['class_topic_author'] == $this->passport('uid')): ?>
				<a href="/class/topic/modify?c=<?= $this->class_id ?>&tid=<?= $this->topic_id ?>" style="background:url(/static/images/icon/pencil.gif) no-repeat left center; padding:10px 5px 5px 20px;">编辑</a>
				<?php endif; if(Cmd::isManager($this->class_id)): ?>
				<a href="javascript:fixTopic(<?= $this->class_id.','.$this->topic_id.','.$this->topic['class_topic_up'] ?>)" style="background:url(/static/images/icon/doc_up.gif) no-repeat left center; padding:10px 5px 5px 20px;">顶置</a>
				<a href="javascript:eliteTopic(<?= $this->class_id.','.$this->topic_id.','.$this->topic['class_topic_elite'] ?>)" style="background:url(/static/images/icon/doc_elite.gif) no-repeat left center; padding:10px 5px 5px 20px;">精华</a> 
				<a href="javascript:delTopic(<?= $this->class_id.','.$this->topic_id ?>)" style="background:url(/static/images/icon/cross.gif) no-repeat left center; padding:10px 5px 5px 20px;">删除</a>
				<?php endif; ?>
				</p>
				<div class="content">
					<?= stripslashes($this->topic['class_topic_content']) ?>
				</div>
			</td>
			<!-- 话题内容 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
		</tr>
		</table>
	</div>
	
	<script type="text/javascript">
		var params = window.location.search.substr(1).split("&");
		if(params[2] != null)
		{
			if(params[2] != 'p=1')
			{
				$('.author .content').hide();
				$('.author').css('cursor','pointer');

				$('.author').click(function(){
					if($('.author .content').is(':hidden'))
					$('.author .content').show();
					else $('.author .content').hide();
				});
			}
		}
	</script>
	
	<!-- 回复内容 /////////////////////////////////// -->
	<div class="pagination"><?= $this->pagination ?></div>
	<?php if($this->replies != null): foreach ($this->replies as $k => $v): ?>
	<div class="reply">
			<table width="100%">
			<tr>
				<td width="10%" class="txtc pu10" valign="top">
					<img src="/static/users/user_test/tiny_head.jpg" width="35" height="35" />
					<p class="f12"><a href=""><?= $v['realName'] ?></a></p>
				</td>
				<!-- 回复 ////////////////////////// -->
				<td width="90%">
					<h2 class="f12"><?= stripslashes($v['class_reply_title']) ?></h2>
					<p class="p8 bg-fblue quiet">
					<small class="f9 quiet"><?= Commons::date($v['class_reply_time']) ?></small>  回复：
					<?php if(Cmd::isManager($this->class_id)): ?>
					<a href="javascript:delReply(<?= $this->class_id.','.$this->topic_id.','.$v['class_reply_id'] ?>)" style="background:url(/static/images/icon/cross.gif) no-repeat left center; padding:10px 5px 5px 20px;">删除</a>
					<?php endif; ?>
					<a href="javascript:scroll(0,0)">#<?= (($this->page-1)*5)+($k+1) ?></a>
					</p>
					<div class="content">
						<?= stripslashes($v['class_reply_content']) ?>
					</div>
				</td>
				<!-- 回复 \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
			</tr>
			</table>
	</div>
	<?php endforeach; endif;  ?>
	<div class="pagination"><?= $this->pagination ?></div>
	<p class="p10 txtc">
	<button class="btn" onclick="topicReplyForm(<?= $this->class_id.','.$this->topic_id.','.$this->pages ?>)">我要回复这个话题</button>
	</p>
</div>