
		<div id="main">
			<div class="sub_bar" style="width:240px;">
				<form method="post">
				<div id="login_form">
					<p class="account">
						登陆帐号:<br />
						<input type="text" class="login_input" onfocus="search_focus('account')" onblur="search_blur('account')" />
					</p>
					<p class="password">
						密码: (<a href="">忘记了?</a>)<br />
						<input type="password" class="login_input" onfocus="search_focus('password')" onblur="search_blur('password')" />
					</p>
					<p>
						<input name="rememberme" type="hidden" value="0" />
						<label for="auto_login"><input name="rememberme" id="auto_login" type="checkbox" value="1" /> 请记住我,下次自动登陆</label>
					</p>
					<p>
						<table>
							<tr>
								<td><input type="image" src="/static/images/btn/login.gif" /></td>
								<td valign="middle"><a href="/member/register/" class="registry">我要注册</a></td>
							</tr>
						</table>
					</p>
				</div>
				</form>
			</div>
			
			
			<div class="sub_bar">
			  <div style="padding:30px 0 0 60px"><img src="/static/images/zju_maps.gif" border="0" usemap="#Map" />
				<map name="Map" id="Map">
				<area shape="poly" coords="1,3,0,23,23,23,23,44,42,58,59,49,60,31,80,21,77,2" href="#" />
				<area shape="poly" coords="77,121,22,121,21,144,82,143,93,131,110,126,111,97,81,97" href="#" />
				<area shape="poly" coords="58,179,86,179,93,187,152,184,151,205,86,204,69,210,51,202" href="#" />
				<area shape="poly" coords="264,86,292,86,298,101,376,99,374,123,300,120,263,115" href="#" />
				<area shape="poly" coords="209,55,210,76,155,77,150,94,120,97,116,76,149,57" href="#" />
			  	<area shape="poly" coords="241,140,184,138,180,124,158,120,146,127,146,152,179,157,241,159" href="#" />
				</map></div>
			</div>
		
			<div class="sub_bar" style="clear:left; width:172px;">
				<div id="news_list">
					<a href="" onmouseover="show_news(1)"><img src="/static/images/icon/radio.gif" />浙大动态</a>
					<a href="" onmouseover="show_news(2)"><img src="/static/images/icon/page_white_world.gif" />各地校友动态</a>
					<a href="" onmouseover="show_news(3)"><img src="/static/images/icon/anchor.gif" />杭州校友会动态</a>
					<a href="" onmouseover="show_news(4)"><img src="/static/images/icon/group.gif" />校友互助信息</a>
					<a href="" onmouseover="show_news(5)"><img src="/static/images/icon/rainbow.gif" />校友企业展示</a>
					<a href="" onmouseover="show_news(6)"><img src="/static/images/icon/talk.gif" />校友访谈</a>
				</div>
			</div>
			
			<div class="sub_bar" style="width:617px; height:210px; margin-top:15px;">
				<table class="news_page" id="num_1">
					<tr>
						<td valign="top">
							<a href="">浙大图书馆推出个性化服务</a>
							<a href="">浙大两项目分获NSFC/RS和NSFC/RSE..</a>
							<a href="">《大运河（杭州段）旅游规划》通过专..</a>
							<a href="">浙大“物理学基础科学研究和教学人才..</a>
							<a href="">浙大陈骝获Hannes Alfven 奖</a>
							<a href="" class="more"></a>
						</td>
						<td width="253"><img src="/static/images/pics/1.jpg" /></td>
					</tr>
				</table>
				<table class="news_page" id="num_2">
					<tr>
						<td valign="top">
							<a href="">朱敏校友荣获2007年度“风云浙商”称号</a>
							<a href="">奥运史上首位中国裁判</a>
							<a href="">从马家台门到三峡工程</a>
							<a href="">海军潜艇学院教授胡均川为潜艇铸“魂”</a>
							<a href="" class="more"></a>
						</td>
						<td width="253"><img src="/static/images/pics/2.jpg" /></td>
					</tr>
				</table>
				<table class="news_page" id="num_3">
					<tr>
						<td valign="top">
							<a href="">杭州浙江大学校友会（筹）校友资料..</a>
							<a href="">致杭州浙大校友</a>
							<a href="">征集筹备组成员QQ..</a>
							<a href="">让校友间、校友和浙大间更多地切身..</a>
							<a href="" class="more"></a>
						</td>
						<td width="253"><img src="/static/images/pics/3.jpg" /></td>
					</tr>
				</table>
				<table class="news_page" id="num_4">
					<tr>
						<td valign="top">
							<a href="">杭州浙江大学校友会（筹）校友资料..</a>
							<a href="">致杭州浙大校友</a>
							<a href="">征集筹备组成员QQ..</a>
							<a href="">让校友间、校友和浙大间更多地切身..</a>
							<a href="" class="more"></a>
						</td>
						<td width="253"><img src="/static/images/pics/4.jpg" /></td>
					</tr>
				</table>
				<table class="news_page" id="num_5">
					<tr>
						<td valign="top">
							<a href="">杭州浙江大学校友会（筹）校友资料..</a>
							<a href="">致杭州浙大校友</a>
							<a href="">征集筹备组成员QQ..</a>
							<a href="">让校友间、校友和浙大间更多地切身..</a>
							<a href="" class="more"></a>
						</td>
						<td width="253"><img src="/static/images/pics/5.jpg" /></td>
					</tr>
				</table>
				<table class="news_page" id="num_6">
					<tr>
						<td valign="top">
							<a href="">杭州浙江大学校友会（筹）校友资料..</a>
							<a href="">致杭州浙大校友</a>
							<a href="">征集筹备组成员QQ..</a>
							<a href="">让校友间、校友和浙大间更多地切身..</a>
							<a href="" class="more"></a>
						</td>
						<td width="253"><img src="/static/images/pics/1.jpg" /></td>
					</tr>
				</table>
			</div>
			
		</div>
		

<script type="text/javascript">show_news(1)</script>
