
		<div id="main">
			<div class="sidebar" style="width:240px;">
				<form method="post">
				<div id="login_form">
					<p class="account">
						登陆帐号:<br />
						<input type="text" class="login_input" onfocus="search_focus('account')" onblur="search_blur('account')" />
					</p>
					<p class="password">
						密码: (<a href="">忘记了?</a>)<br />
						<input type="password" class="login_input" onfocus="search_focus('password')" onblur="search_blur('password')" />
					</p>
					<p>
						<input name="rememberme" type="hidden" value="0" />
						<label for="auto_login"><input name="rememberme" id="auto_login" type="checkbox" value="1" /> 请记住我,下次自动登陆</label>
					</p>
					<p>
						<table>
							<tr>
								<td><input type="image" src="/static/images/btn/login.gif" /></td>
								<td valign="middle"><a href="/member/register/" class="registry">我要注册</a></td>
							</tr>
						</table>
					</p>
				</div>
				</form>
			</div>
			
			
			<div class="sidebar">
			  <div style="padding:30px 0 0 60px"><img src="/static/images/zju_maps.gif" border="0" usemap="#Map" />
				<map name="Map" id="Map">
				<area shape="poly" coords="1,3,0,23,23,23,23,44,42,58,59,49,60,31,80,21,77,2" href="#" />
				<area shape="poly" coords="77,121,22,121,21,144,82,143,93,131,110,126,111,97,81,97" href="#" />
				<area shape="poly" coords="58,179,86,179,93,187,152,184,151,205,86,204,69,210,51,202" href="#" />
				<area shape="poly" coords="264,86,292,86,298,101,376,99,374,123,300,120,263,115" href="#" />
				<area shape="poly" coords="209,55,210,76,155,77,150,94,120,97,116,76,149,57" href="#" />
			  	<area shape="poly" coords="241,140,184,138,180,124,158,120,146,127,146,152,179,157,241,159" href="#" />
				</map></div>
			</div>
		
<?php 
if(!$this->cache->start('homepage')):
?>
<!-- 显示在首页的信息目录列 -->
<div class="sidebar" style="clear:left; width:172px;">
<div id="news_list">
<?php 
$cat_rows = $this->info_xmlrpc->call('info.get_public_categories');
foreach ($cat_rows as $k => $v): ?>
<a href="" onmouseover="show_news(<?= $k+1 ?>)"><img src="/static/images/icon/<?= $v['category_icon'] ?>.gif" /><?= $v['category_name'] ?></a>
<?php endforeach; ?>
</div>
</div>

<!-- 相应的内容快照 -->
<div class="sidebar" style="width:667px; height:210px; margin-top:15px;">
<?php 
foreach ($cat_rows as $k => $v):
//获取相应文章快照
$art_rows = $this->info_xmlrpc->call('info.get_arts_snapshot', array($v['category_id']));
?>			
<table class="news_page" id="num_<?= $k+1 ?>">
<tr>
<td valign="top">							
<?php foreach ($art_rows as $k2 => $v): ?>
<a href="/info/view/id/<?= $v['entity_id'] ?>"><?= $v['entity_title'] ?></a>
<?php endforeach; ?>
<a href="/info/?category=<?= $v['category_id'] ?>" class="more"></a>
</td>
<td width="253"><img src="/static/images/pics/<?= $k+1 ?>.jpg" /></td>
</tr>
</table>
<?php endforeach; $this->cache->end(); endif; ?>
</div>

<script type="text/javascript">show_news(1)</script>
