<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="zh-CN" />
<?= $this->headMeta(); ?>
<link rel="stylesheet" type="text/css" href="/static/styles/facebox.css" media="screen" />
<script type="text/javascript" src="/static/scripts/jquery.js"></script>
<script type="text/javascript" src="/static/scripts/common.js"></script>
<script type="text/javascript" src="/static/scripts/popup.js"></script>
<script type="text/javascript" src="/static/scripts/biz/biz.js"></script>