<div id="main">

<table width="100%" style="margin:0 10px;">
	<tr>
		<td>
			<div style="width:600px;height:200px;" class="txtc">
				<div style="padding:20px;">
				<img src="/static/images/icon/success.gif" />
				<h3>您已经成功登陆！</h3><br />
				（个性化信息显示...待定）
				</div>
			</div>
		</td>
		<td>
			<!-- 专题区 -->
<div class="sidebar subject">
<h2 class='clearfloat'>活动</h2>
<a target="_blank" href="http://www.zju.zj.cn/Details/DongTaiDetail_532.html">“心系灾区，大爱无垠”——浙江大学企业家经理人高级研修班爱心捐款</a>
<h2>专题</h2>
<a target="_blank" href="http://www.zjuhz.com/info/view/detail/id/186">杭州校友会筹备工作一览<img src="/static/images/icon/new.gif" /></a>
<a href="/info/subject/index/of/qiushixungen-jiangxi">浙江大学求是寻根 - 江西段</a>
</div>
		</td>
	</tr>
</table>
		
<?php 
if(!$this->cache->start('homepage')):
?>
<!-- 显示在首页的信息目录列 -->
<div class="sidebar" style="clear:left; width:172px;">
<div id="news_list">
<?php 
$cat_rows = $this->info_xmlrpc->call('rpcInfo.get_public_categories');
foreach ($cat_rows as $k => $v): ?>
<a href="/info/?category=<?= $v['category_id'] ?>" onmouseover="show_news(<?= $k+1 ?>)"><img src="/static/images/icon/<?= $v['category_icon'] ?>.gif" /><?= $v['category_name'] ?></a>
<?php endforeach; ?>
</div>
</div>

<!-- 相应的内容快照 -->
<div class="sidebar" style="width:667px; height:210px; margin-top:15px;">
<?php 
foreach ($cat_rows as $k => $v):
//获取相应文章快照
$art_rows = $this->info_xmlrpc->call('rpcInfo.get_arts_snapshot', array((int)$v['category_id']));
?>			
<table class="news_page" id="num_<?= $k+1 ?>">
<tr>
<td valign="top">							
<?php foreach ($art_rows as $k2 => $v): ?>
<a href="/info/view/detail/id/<?= $v['entity_id'] ?>" title="[<?= Commons::date($v['entity_pub_time']) ?>] <?= $v['entity_title'] ?>"><?= substr($v['entity_title'],0,60).'..' ?></a>
<?php endforeach; ?>
</td>
<td width="253"><img src="/static/images/pics/<?= $k+1 ?>.jpg" /></td>
</tr>
</table>
<?php endforeach; $this->cache->end(); endif; ?>
</div>

<script type="text/javascript">show_news(1)</script>