<div class="span-24 last oneCol">	
	<div>
		<table>
			<tr>
				<td class="pd5"><?= Commons::getUserFace($this->passport('uid')) ?></td>
				<td class="vm f12">
						当前在线校友<strong id="online"></strong>人，
						截止今天本站已有资讯<strong><?= $this->info_xmlrpc->call('rpcInfo.howmany') ?></strong>条，
						校友企业<strong id="mybiz"></strong>家，<a href="/biz/my/company/type/join/">申请加入</a>。
					<br />
					您的班级：<span id="myclass"></span>; 
					<?php $groups = $this->Group->groupNews(); ?>
					<?php if($groups): echo '您的群组：'; foreach($groups as $g): ?>
					<a target="_blank" href="/group/home?gid=<?= $g['gid'] ?>"><?= $g['name'] ?></a> , 
					<?php endforeach; echo '有新内容'; endif; ?>
					<br />
					快速链接：
						<a href="/member/my/address/">通讯录</a>、
						<a href="/member/my/">我的资料</a>、
						<a href="/help/my/">我的互助</a>、
						<a href="/info/admin/">资讯投稿</a>、
						<a href="/group/my">我的群组</a>
				</td>
			</tr>
		</table>	
	</div>
</div>

<?php if(!$this->cache->start('homepage')): ?>
<div class="span-24 last">
	<a target="_blank" href="http://www.zjuhz.com/info/view/detail/id/708" style="position:relative; display:block; background:url(/static/images/home/gq_banner.gif); width:950px; height:125px;"></a>
	<div class="span-7 mgu10">
		<iframe frameborder="0" height="215" width="270" src="/ad.html"></iframe>
		<?= $this->render('items/notice.phtml'); ?>
		<?= $this->render('items/trends.phtml'); ?>
		<?= $this->render('items/zjuorg.phtml'); ?>
		<?= $this->render('items/dev.phtml'); ?>
		<?= $this->render('items/teacher.phtml'); ?>
	</div>
	<div class="span-10 mgu10">
		<?= $this->render('items/9-20.phtml'); ?>
                <div class="oneCol mgd10">
                    <h3 class="mglf10">群组活动</h3>
                    <?= $this->newevents(5) ?>
                </div>
		<?= $this->render('items/biz.phtml'); ?>
		<?= $this->render('items/groups.phtml'); ?>
	</div>
	<div class="span-7 mgu10 last">
		<?= $this->render('items/news.phtml'); ?>
		<?= $this->render('items/alma-mater.phtml'); ?>
		<?= $this->render('items/active.phtml'); ?>
		<?= $this->render('items/subject.phtml'); ?>
                <?= $this->render('items/links.phtml'); ?>
				<a target="_blank" href="http://www.zjuhz.com/group/topic/show?gid=18&tid=216"><img style="margin:5px;" src="/static/images/ads/ad_1.jpg" /></a>
	</div>
</div>
<?php $this->cache->end(); endif; ?>

<script type="text/javascript">
	$('#myclass').load('/class/ajax/myclass/?uid=<?= $this->passport('uid') ?>');
	$('#mybiz').load('http://www.zjuhz.com/biz/external/base/type/companies/');
	$('#online').load('http://www.zjuhz.com/member/external/olnum/');
</script>