<div class="span-24 last oneCol">
	<p class="success mg10" style="line-height:150%">
		<?= Cmd::icon('emoticon_grin.png') ?>
		<?= $this->passport('realName') ?> 校友欢迎您回来，您上一次登陆本站是在<?= Lp_Date::timespan($this->passport('lastLogin')) ?>之前 <small class="quiet f12">(注:下横线内的信息尚未关联)</small>
	</p>
	
	<div class="mglf10">
		<table>
			<tr>
				<td class="pd10"><?= Commons::getUserFace($this->passport('uid')) ?></td>
				<td class="vm f14 pdd10">
					<p>
						当前在线校友<strong id="online"></strong>人，
						截止今天本站已有资讯<strong><?= $this->info_xmlrpc->call('rpcInfo.howmany') ?></strong>条，
						校友企业<strong id="mybiz"></strong>家，<a href="/biz/my/company/type/join/">申请加入</a>。
					</p>
					<p>您的班级：<span id="myclass"></span>，您的群组：_____有了新内容。</p>
					<p>快速链接：
						<a href="/member/my/address/">通讯录</a>、
						<a href="/member/my/">我的资料</a>、
						<a href="/help/my/">我的互助</a>、
						<a href="/info/admin/">资讯投稿</a>
					</p>
				</td>
			</tr>
		</table>	
	</div>
</div>

<?php if(!$this->cache->start('homepage')): ?>
<div class="span-17 mgu10">
	<div class="span-7">
		<?= $this->render('items/notice.phtml'); ?>
		<?= $this->render('items/trends.phtml'); ?>
		<?= $this->render('items/zjuorg.phtml'); ?>
		<?= $this->render('items/teacher.phtml'); ?>
		<?= $this->render('items/dev.phtml'); ?>
	</div>
	<div class="span-10 last">
		<?= $this->render('items/biz.phtml'); ?>
		<?= $this->render('items/groups.phtml'); ?>
	</div>
</div>

<div class="span-7 mgu10 last">
	<?= $this->render('items/alma-mater.phtml'); ?>
	<?= $this->render('items/active.phtml'); ?>
	<?= $this->render('items/subject.phtml'); ?>
</div>
<?php $this->cache->end(); endif; ?>


<script>
	$('#myclass').load('/class/ajax/myclass/?uid=<?= $this->passport('uid') ?>');
	$('#mybiz').load('http://www.zjuhz.com/biz/external/base/type/companies/');
	$('#online').load('http://www.zjuhz.com/member/external/olnum/');
</script>