	<div class="span-24 last oneCol">	
	<div>
		<table>
			<tr>
				<td class="pd5"><?= Commons::getUserFace($this->passport('uid')) ?></td>
				<td class="vm f12">
						当前在线校友<strong id="online"></strong>人，
						截止今天本站已有资讯<strong><?= $this->info_xmlrpc->call('rpcInfo.howmany') ?></strong>条，
						校友企业<strong id="mybiz"></strong>家，<a href="/biz/my/company/type/join/">申请加入</a>。
					<br />
					您的班级：<span id="myclass"></span>; 
					<?php $groups = $this->Group->groupNews(); ?>
					<?php if($groups): echo '您的群组：'; foreach($groups as $g): ?>
					<a target="_blank" href="/group/home?gid=<?= $g['gid'] ?>"><?= $g['name'] ?></a> , 
					<?php endforeach; echo '有新内容'; endif; ?>
					<br />
					快速链接：
						<a href="/member/my/address/">通讯录</a>、
						<a href="/member/my/">我的资料</a>、
						<a href="/help/my/">我的互助</a>、
						<a href="/info/admin/">资讯投稿</a>、
						<a href="/group/my">我的群组</a>
				</td>
			</tr>
		</table>	
	</div>
</div>
    <div class="span-7 mgu10">
        <iframe frameborder="0" height="215" width="270" src="/ad.html"></iframe>
        <div class="sideBar list-1">
			<h3 class="tt mglf10"><img src="/static/images/group/icons/plugin.png" /> 特色群组</h3>
			<ul class="span-3 mglf10" style="float:left">
                <li><a class="lk-1" href="/group/home?gid=10">创业俱乐部</a></li>
                <li><a class="lk-1" href="/group/home?gid=2">金融俱乐部</a></li>
                <li><a class="lk-1" href="/group/home?gid=23">家长俱乐部</a></li>
                
            </ul>
            <ul class="span-3" style="float:left">
                <li><a class="lk-1" href="/group/home?gid=14">法律人俱乐部</a></li>
                <li><a class="lk-1" href="/group/home?gid=15">羽毛球爱好者</a></li>
                <li><a class="lk-1" href="/group/home?gid=21">期货交流空间</a></li>
            </ul>
        </div>
        <div class="sideBar list-1" style="clear:both">
			<h3 class="tt mglf10"><img src="/static/images/group/icons/chart_line.png" /> 校友企业</h3>
			<div id="cps" style="height:75px; overflow:hidden; margin-bottom:10px;">
                <ul class="mglf10">
                    <?php
                    $bizs = $this->Biz->get(8);
                    foreach($bizs as $b): ?>
                    <li><a class="lk-1" title="<?= $b['name'] ?>" href="/biz/detail/index/cid/<?= $b['cid'] ?>">
                        <?= $b['name'] ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
		<?= $this->render('items/subject.phtml'); ?>
		<?= $this->render('items/3x.phtml'); ?>
    </div>
    <div class="span-17 last">
    	<br />
        <?= $this->newevents(10) ?>
        <?= $this->render('items/v2_news.phtml'); ?>
        <?= $this->render('items/v2_topics.phtml'); ?>
    </div>


<script type="text/javascript">
$(document).ready(function(){
$.NiceJForms.build({
		imagesPath:"/static/styles/nicejform/images/default/"
	})
});
setInterval('AutoScroll("#cps")',5000);
	$('#myclass').load('/class/ajax/myclass/?uid=<?= $this->passport('uid') ?>');
	$('#mybiz').load('http://www.zjuhz.com/biz/external/base/type/companies/');
	$('#online').load('http://www.zjuhz.com/member/external/olnum/');
</script>