<!-- 互助分类 -->
<div class="sidebar">
<?= $this->render('sort.phtml'); ?>
</div>


<div class="sidebar">
<!-- 互助广播 -->
<?= $this->render('broadcast.phtml'); ?>

<table class="help_set_big">

    <!-- 路径////////////////////////////////////////// -->
	<tr>
	<td><?= $this->path; ?></td>
	</tr>

</table>

<?php if ($this->sort) { ?>
<!-- 分类集合 -->
<table class="help_set_big">

    <!-- 分类////////////////////////////////////////// -->
	<tr>
	<th colspan="4" class="txtl"><?= $this->sname; ?></th>
	</tr>

	<tr>
    <?php foreach ($this->sort as $key => $value) { ?>	
	<td><a href="/help/sort/browse/sid/<?= $value['sid']; ?>/sname/<?= urlencode($value['name']); ?>/path/<?= urlencode($this->path); ?>"><?= $value['name']; ?></td>
    <?php } ?>
	</tr>

</table>
<?php } ?>

<!-- 问题集合 -->
<table class="help_set_big">

    <!-- 问题////////////////////////////////////////// -->		
	<tr>
	<th class="txtl">全部问题</th>
	<th class="txtr" colspan="4"></th>
	</tr>
    <?php foreach ($this->browse as $value) { ?>
	<tr>
	<td>
	<a href="/help/question/detail/<?= $value['qid']; ?>/"><?= $value['title']; ?></a> 
	<?php if ($value['offer'] > 0 ) { ?><span class="f9"><img src="/static/images/icon/icn_offer.gif" title="积分悬赏"><?php echo $value['offer']; } ?></span></td>
	<td><?= $value['reply']; ?></td>
	<td><img src="/static/images/icon/icn_status_<?= $value['status']; ?>.gif"></td>
	<td><?= date('m-d H:i', strtotime($value['addTime'])); ?></td>
	</tr>
	</tr>
    <?php } ?>

</table>

<?= $this->paging; ?>
</div>
