<div class="help_category">
<h2 class="fw14">问题分类</h2>
<p>
<a href="" class="M">时尚生活</a>
<a href="">购物</a>
<a href="">旅行</a>
<a href="">美食</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">娱乐休闲</a>
<a href="">影视</a>
<a href="">明星</a>
<a href="">占卜</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">电脑网络</a>
<a href="">联网</a>
<a href="">硬件</a>
<a href="">软件</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">电子游戏</a>
<a href="">网络</a>
<a href="">单机</a>
<a href="">家用</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">健康医学</a>
<a href="">咨询</a>
<a href="">常识</a>
<a href="">健身</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">商业经济</a>
<a href="">房产</a>
<a href="">股票</a>
<a href="">外汇</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">体育运动</a>
<a href="">篮球</a>
<a href="">足球</a>
<a href="">奥运</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">职场人际</a>
<a href="">交际</a>
<a href="">求职</a>
<a href="">跳槽</a>
<a href="">..</a>
</p>

</div>