<style>
	.album img{ margin:10px; border:1px solid #ccc; padding:3px; }
</style>
	<div class="pd10">
		
		<p class="txtc"><img src="/static/subjects/qiushixungen-jiangxi/images/head-bg.jpg" /></p>
		<!-- 相片展示 -->
		<div class="album">
			
		</div>
		<div class="oneCol pd10">
			<p class="f14">“求是寻根——浙大校友探访西迁路”江西阶段的活动已经结束了。杭州校友会一共7名校友参加了此次寻根活动。</p>

			<p class="f14">
				从5月9日傍晚出发，至13日清晨回到杭州，短短的3天半时间，有太多太多的感受。概括起来，主要的收获有3点:<br />
	　　			首先，我们了解了浙大历史的一部分，被浙大西迁过程中艰苦办学的精神所深深感染；<br />
	　　			其次，我们了解到浙大要携手杭州市一起建设"和谐杭州浙大产业带”，母校身边的校友有机会全力参与这个产业带的建设，这是因为，从很大程度上，这会是“杭州浙大校友产业带”；<br />
	　　			最后，认识了母校充满激情的朱军副校长，以及企业家经理人同学会的老师和校友，今后可以和他们大量互动，共同营造好杭州校友的创业气氛，事业发展气氛。<br />
			</p>
	　　		<p class="f14">
				此行中，杭州校友会与探访团其他成员展开了良好的互动，表达了杭州校友会广交在杭校友、团结校友的意愿。希望通过此次活动，既寻到求是精神的“根”，又能寻到更多校友来参与我们，一起来为“杭州浙大校友会”这棵正在成长中的“小树”浇水施肥，让它快快生根发芽快快长大。细节请看照片。
			</p>
		</div>
	</div>
	
	


<script type="text/javascript">
$(document).ready(function($) {
	album('qiushixungen-jiangxi',1);
});
</script>