<form class="home_form" name="frmGroup" id="frmGroup" autocomplete="off">
<input type="text" class="inputtxt" name="gname" id="gname" maxlength="10" /> 
<input type="hidden" name="gid" id="gid" value="<?= $this->gid; ?>">
<input type="hidden" name="tmpgid" id="tmpgid" value="<?= $this->gid; ?>">
<input type="submit" class="btn" value="新建组" name="btnGroup" id="btnGroup" />
</form>

<table class="control_list">
<tr>
<th class="txtl" width="80%">组名</th>
<th class="txtl" width="20%">选项</th>
</tr>

<?php foreach ($this->groupList as $value) { ?>
<tr id="group<?= $value['gid']; ?>">
<td><div align="left"><a href=""><?= $value['gname']; ?></a></div></td>
<td><div align="left"><a href="#" onclick="dogroupmodiBefore('<?= $value['gid']; ?>','<?= $value['gname']; ?>');return false;" id="modi<?= $value['gid']; ?>">重命名</a> <a href="#" onClick="dogroupdelBefore('<?= $value['gid']; ?>');return false;" id="del">删除</a></div></td>
</tr>
<?php } ?>

</table>