<table>
  <tr>
    <td>
        <form class="home_form" name="frmFind" id="frmFind" autocomplete="off"><?php $this->group[0] = '所有组';ksort($this->group); echo $this->formSelect('gid', $this->gid, null, $this->group); ?>&nbsp;<?= $this->formSelect('field', $this->field, null, $this->find) ?>&nbsp;<input type="text" class="inputtxt" name="wd" id="wd" value="<?= $this->wd; ?>" />&nbsp;<input type="submit" class="btn" value="查找" /></form>
    </td>
    <td>
        <button class="btn" onclick="location.href='/member/my/address/'">显示全部</button>&nbsp;
	<button class="btn" onclick="location.href='/member/my/address/type/docard/'">新建名片</button>
    </td>
  </tr>
</table>

&nbsp;<img src="/static/images/icon/lightbulb.gif"> 在<strong> <?= ($this->group[$this->gid] ? $this->group[$this->gid] : '所有'); ?> </strong>组内<?= ($this->wd ? '<strong> '.$this->find[$this->field].' </strong>关键字<strong> '.$this->wd.' </strong>' : ''); ?>共找到<strong> <?= $this->total; ?> </strong>张名片

<?php if ($this->card) { ?>
<table class="control_list">
<tr>
<th class="txtl" width="27%">(状态) 姓名</th>
<th class="txtl" width="27%">已建立的联系信息</th>
<th class="txtl" width="25%">所属组</th>
<th class="txtl" width="21%">选项</th>
</tr>

<?php foreach ($this->card as $value) { ?>
<tr>
<td class="txtl">
<img src="/static/images/bullet/<?= $this->status[$value['status']]; ?>.gif"> <?php if ($value['iuid']) { ?><a title="<?= $value['iuid']; ?>"><?php } echo $value['cname']; if ($value['iuid']) { ?></a><?php } ?>
</td>

<td class="txtl">
<?php if (!empty($value['mobile'])) { ?><img src="/static/images/icon/phone.gif" alt="<?= $value['mobile']; ?>" />&nbsp;<?php  }; ?>

<?php if (!empty($value['eMail'])) { ?><a href="mailto:<?= $value['eMail']; ?>"><img src="/static/images/icon/email.gif" alt="邮件联系" /></a>&nbsp;<?php  }; ?>

<?php if (!empty($value['qq'])) { ?><a target=blank href=http://wpa.qq.com/msgrd?V=1&Uin=<?= $value['qq']; ?>&Site=zjuhz.com&Menu=yes><img src="/static/images/icon/qq.gif" alt="QQ联系" /></a>&nbsp;<?php  }; ?>

<?php if (!empty($value['msn'])) { ?><a href=msnim:chat?contact=<?= $value['msn']; ?>><img src="/static/images/icon/msn.gif" alt="MSN联系" /></a>&nbsp;<?php  }; ?>

<?php if (!empty($value['address'])) { ?><img src="/static/images/icon/building.gif" alt="<?= $value['address']; ?>" /><?php  }; ?>
</td>

<td class="txtl"><?= $value['gname']; ?></td>

<td class="txtl"><a href="/member/my/address/type/docard/cid/<?= $value['cid']; ?>/">查看</a>&nbsp;<a href="/member/my/address/type/docard/cid/<?= $value['cid']; ?>/">修改</a>&nbsp;<?php if (3 == $value['status'] || 1 == $value['status'] || 0 == $value['status']) { ?><a href="/member/my/address/type/doinvite/cid/<?= $value['cid']; ?>/">邀请</a><?php } else { ?><?php } ?></td>

</tr>
<?php } ?>

</table>
<?= $this->paging; ?>
<?php } ?>