<table>
  <tr>
	<td><form class="home_form" name="frmFind" id="frmFind" autocomplete="off"><select name="gid" id="gid"><option>所有组</option><?php foreach ($this->groupList as $value)  { ?><option value="<?= $value['gid']; ?>" <?= ($this->gid == $value['gid'] ? 'selected' : ''); ?>><?= $value['gname']; ?></option><?php } ?></select>&nbsp;<?= $this->formSelect('field', $this->field, null, $this->find) ?>&nbsp;<input type="text" class="inputtxt" name="wd" id="wd" value="<?= $this->wd; ?>" />&nbsp;<input type="submit" class="btn" value="查找" /></form></td>
	<td><button class="btn" onclick="location.href='/member/my/address/type/docard/'">新建名片</button></td>		
  </tr>
</table>

<?php if ($this->cardList) { ?>

<p class="tip"><img src="/static/images/icon/info.gif" align="absmiddle" />&nbsp;&nbsp;将名片与校友关联便可更方便地查看资料；关联分为邀请(若校友未注册)和直接输校友UID(已注册)。</p>

<table class="control_list">
<tr>
<th class="txtl" width="27%">(状态) 姓名</th>
<th class="txtl" width="27%">已建立的联系信息</th>
<th class="txtl" width="25%">所属组</th>
<th class="txtl" width="21%">选项</th>
</tr>

<?php foreach ($this->cardList as $value) { ?>
<tr>
<td class="txtl">
<img src="/static/images/bullet/<?= $this->status[$value['status']]; ?>.gif"> <?php if ($value['iuid']) { ?><a title="<?= $value['iuid']; ?>"><?php } echo $value['cname']; if ($value['iuid']) { ?></a><?php } ?>
</td>

<td class="txtl">
<?php if (!empty($value['mobile'])) { ?><img src="/static/images/icon/phone.gif" alt="<?= $value['mobile']; ?>" />&nbsp;<?php  }; ?>

<?php if (!empty($value['eMail'])) { ?><a href="mailto:<?= $value['eMail']; ?>"><img src="/static/images/icon/email.gif" alt="邮件联系" /></a>&nbsp;<?php  }; ?>

<?php if (!empty($value['qq'])) { ?><a target=blank href=http://wpa.qq.com/msgrd?V=1&Uin=<?= $value['qq']; ?>&Site=zjuhz.com&Menu=yes><img src="/static/images/icon/qq.gif" alt="QQ联系" /></a>&nbsp;<?php  }; ?>

<?php if (!empty($value['msn'])) { ?><a href=msnim:chat?contact=<?= $value['msn']; ?>><img src="/static/images/icon/msn.gif" alt="MSN联系" /></a>&nbsp;<?php  }; ?>

<?php if (!empty($value['address'])) { ?><img src="/static/images/icon/building.gif" alt="<?= $value['address']; ?>" /><?php  }; ?>
</td>

<td class="txtl"><?= $value['gname']; ?></td>

<td class="txtl"><a href="/member/my/address/type/docard/cid/<?= $value['cid']; ?>/">查看</a>&nbsp;<a href="/member/my/address/type/docard/cid/<?= $value['cid']; ?>/">修改</a>&nbsp;<?php if (3 == $value['status']) { ?><a href="#" onClick="javascript:copyToClipBoard('http://192.168.18.18/member/register/invite/ikey/<?= $value['cid']; ?>/', '邀请好友注册的链接已复制成功！您可在QQ/MSN/EMAIL等处粘贴给好友即可。\n您的好友通过此链接注册且填写的信息与您通讯录上的相符，注册才能成功。')">邀请</a><?php } else { ?><?php } ?></td>

</tr>
<?php } ?>

</table>
<?= $this->paging; ?>
<?php } ?>