<form class="home_form" name="frmCard" id="frmCard" autocomplete="off">
<table>
<tr>
<td align="right"><b>姓名：</b></td>
<td><input class="txt" type="text" name="cname" id="cname" maxlength="6" value="<?= $this->detail['cname']; ?>"></td>
<td><b>名片组：</b></td>
<td>
<select name="gid" id="gid">
<option>请选择</option>
<?php foreach ($this->group as $value)  { ?>
<option value="<?= $value['gid']; ?>" <?= ($this->detail['gid'] == $value['gid'] ? 'selected' : ''); ?>><?= $value['gname']; ?></option><?php } ?>
</select></td>
</tr>
<tr>
<td align="right"><b>手机：</b></td>
<td><input class="txt" type="text" name="mobile" id="mobile" maxlength="11" value="<?= $this->detail['mobile']; ?>" /></td>
<td><b>邮箱：</b></td>
<td><input class="txt" type="text" name="eMail" id="eMail" maxlength="50" value="<?= $this->detail['eMail']; ?>" /></td>
</tr>
<tr>
<td align="right"><b>QQ：</b></td>
<td><input class="txt" type="text" name="qq" id="qq" maxlength="15" value="<?= $this->detail['qq']; ?>" /></td>
<td><b>MSN：</b></td>
<td><input class="txt" type="text" name="msn" id="msn" maxlength="50" value="<?= $this->detail['msn']; ?>" /></td>
</tr>
<tr>
<td align="right"><b>地址：</b></td>
<td><input class="txt" type="text" name="address" id="address" maxlength="80" value="<?= $this->detail['address']; ?>" /></td>
<td><b>邮编：</b></td>
<td><input class="txt" type="text" name="postcode" id="postcode" maxlength="6" value="<?= $this->detail['postcode']; ?>" /></td>
</tr>
<tr>
<td align="right"><b>备注：</b></td>
<td colspan="3"><textarea name="memo" cols="55" rows="3" id="memo" class="txt"><?= $this->detail['memo']; ?></textarea></td>
</tr>
<tr>
<td align="right">&nbsp;</td>
<td colspan="3"><input type="submit" value="保存名片" class="btn" id="btnCard" name="btnCard" />&nbsp;<button class="btn" onclick="history.go(-1);">返回</button></td>
</tr>
<tr>
<td align="right">&nbsp;</td>
<td colspan="3"><div id="ajaxhint" style="width:300px"></div></td>
</tr>

</table>
<input type="hidden" id="cid" name="cid" value="<?= $this->cid; ?>" />
</form>