<div id="ajaxloading"></div>
<div class="sidebar">
<?= $this->render("card.phtml"); ?>

<?= $this->render("my/menu-left.phtml"); ?>
</div>

<div class="sidebar">
<?= $this->render("my/menu-top.phtml"); ?>
<div class="control_content">
<div class="control_tab">
<a href="/member/my/address/type/card/">名片管理</a>
<a href="/member/my/address/type/group/">组管理</a>
<!--<p style="float:right;margin-top:10px; color:#666"><img src="/static/images/bullet/red.gif" />未邀请<img src="/static/images/bullet/orange.gif" />已邀请未注册<img src="/static/images/bullet/green.gif" />已注册</p>-->
</div>

<div class="control_action">
<?php echo $this->render('my/address-'.$this->type.'.phtml'); ?>
</div>
</div>
</div>
<script language="javascript" type="text/javascript">var ctrl="<?= $this->ctrl; ?>";var type="<?= $this->type; ?>";</script>
