<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="zh-CN" />
<script type="text/javascript" src="/static/scripts/jquery.js"></script>
<script type="text/javascript" src="/static/scripts/common.js"></script>
<script type="text/javascript" src="/static/scripts/popup.js"></script>
<link href="/static/styles/global.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/static/styles/member.css" media="screen" rel="stylesheet" type="text/css" />
<title>名片新建/修改/查看 - 会员中心 - 杭州浙江大学校友会 - zjuhz.com</title>
<script type="text/javascript" src="/static/scripts/member/member.js"></script>
<script type="text/javascript" src="/static/scripts/member/my/address.js"></script>
</head>

<body>
<div id="wrap">

<?php echo $this->render('my/popup-'.$this->type.'.phtml'); ?>

</div>
</body>
</html>