<table>
  <tr>
	<td><button class="btn" onclick="location.href='/member/my/user/type/work/#new'">新增工作经验</button></td>		
  </tr>
</table>

<br />

<fieldset>
<legend class="f14">&nbsp;我的工作经验&nbsp;</legend>
<table class="control_list">
<tr>
<th class="txtl" width="50%">公司名称</th>
<th class="txtl" width="32%">工作时间</th>
<th class="txtl" width="18%">选项</th>
</tr>
<?php foreach ($this->work as $value) { ?>
<tr id="work<?= $value['wid']; ?>">
<td class="txtl"><?= $value['company']; ?></td>
<td class="txtl"><?= $value['startDate']; ?> 至 <?= $value['endDate']; ?></td>
<td class="txtl"><a href="/member/my/user/type/work/wid/<?= $value['wid']; ?>/"><img src="/static/images/icon/mini_icon_bbsarticle.gif" alt="修改">修改</a> <a href="#" onClick="doworkdelBefore('<?= $value['wid']; ?>');return false;" id="del"><img src="/static/images/icon/cross.gif" alt="删除">删除</a></td>
</tr>
<?php } ?>
</table>
</fieldset>

<br />

<fieldset>
<legend class="f14">&nbsp;<?= (!$this->detail ? '新增工作经验' : '修改工作经验'); ?>&nbsp;</legend>
<a name="new" id="new"></a>
<table id="new_work">
<tr>
<td align="right"><b>公司名称：</b><br /></td>
<td><input name="company" type="text" id="company" maxlength="50" size="33" class="inputtxt" tabindex="1" value="<?= $this->detail['company']; ?>" />&nbsp;</td>
</tr>
<tr>
<td align="right"><b>工作时间：</b><br /><br /></td>
<td>从&nbsp;<input name="startDate" type="text" id="startDate" size="12" maxlength="10" class="inputtxt" tabindex="2" value="<?= $this->detail['startDate']; ?>" />&nbsp;到&nbsp;<input name="endDate" type="text" id="endDate" size="12" maxlength="10" class="inputtxt" tabindex="3" value="<?= $this->detail['endDate']; ?>" />&nbsp;<br /><span class="quiet f12">请输入您在该公司工作的起止时间。格式应为：年-月-日，如1998-04-07。</span>&nbsp;</td>
</tr>
<tr>
<td align="right"><b>所处行业：</b><br /></td>
<td><select name="industry" id="industry" tabindex="4"><option>--请选择--</option><?php foreach ($this->industry() as $key => $value) { ?><option <?= ($key == $this->detail['industry'] ? 'selected' : ''); ?> value="<?= $key; ?>"><?= $value; ?></option><?php } ?></select>&nbsp;</td>
</tr>
<tr>
<td align="right"><b>公司性质：</b><br /></td>
<td><select name="property" id="property" tabindex="5"><option>--请选择--</option><?php foreach ($this->property() as $key => $value) { ?><option <?= ($key == $this->detail['property'] ? 'selected' : ''); ?> value="<?= $key; ?>"><?= $value; ?></option><?php } ?></select>&nbsp;</td>
</tr>
<tr>
<td align="right"><b>所在部门：</b><br /></td>
<td><input name="division" type="text" id="division" maxlength="30" size="33" class="inputtxt" tabindex="6" value="<?= $this->detail['division']; ?>" />&nbsp;</td>
</tr>
<tr>
<td align="right"><b>担当职位：</b><br /><br /><br /></td>
<td>职能分类：<select name="functional" id="functional" tabindex="7"><option>--请选择--</option><?php foreach ($this->functional() as $key => $value) { ?><option <?= ($key == $this->detail['functional'] ? 'selected' : ''); ?> value="<?= $key; ?>"><?= $value; ?></option><?php } ?></select>&nbsp;<br />职位名称：<input name="job" type="text" id="job" maxlength="20" size="46" class="inputtxt" tabindex="8" value="<?= $this->detail['job']; ?>" />&nbsp;<br /><span class="quiet f12">请输入职位具体名称，如：软件工程师 销售代表 文秘 英语翻译 证券分析师。</span>&nbsp;</td>
</tr>
<tr>
<td align="right"><b>工作描述：</b><br /><br /><br /><br /><br /><br /></td>
<td><textarea name="description" class="bigtxt" id="description"><?= $this->detail['description']; ?></textarea>
&nbsp;<br /><span class="quiet f12">请输入在该公司期间的职责范围、工作业绩、离职原因等内容。2000字以内。</span>&nbsp;</td>
</tr>
<tr>
<td>&nbsp;</td>
<td><input type="submit" value="保存修改" class="btn" name="btnUser" id="btnUser" /></td>
</tr>
<tr>
<td></td>
<td><div id="ajaxhint" style="width:300px"></div></td>
</tr>
</table>
<input type="hidden" id="wid" name="wid" value="<?= $this->wid; ?>">
<!--<script language="javascript" type="text/javascript">Calendar.setup({inputField : "startDate", button : "startDate"});</script>
<script language="javascript" type="text/javascript">Calendar.setup({inputField : "endDate", button : "endDate"});</script>-->
</fieldset>