<table>
<tr>
<td align="right"><b>通讯地址：</b></td>
<td><input name="qq" size="40" tabindex="1" value="" id="qq" class="txt" type="text"></td>
</tr>
<tr>
<td align="right"><b>个人网站：</b></td>
<td><input name="qq" size="40" tabindex="1" value="" id="qq" class="txt" type="text"></td>
</tr>
<tr>
<td align="right"><b>MSN：</b></td>
<td><input name="qq" size="40" tabindex="1" value="" id="qq" class="txt" type="text"></td>
</tr>
<tr>
<td align="right"><b>手机：</b></td>
<td><input name="qq" size="40" tabindex="1" value="" id="qq" class="txt" type="text"></td>
</tr>
<tr>
<td align="right"><b>电话：</b></td>
<td><input name="qq" size="40" tabindex="1" value="" id="qq" class="txt" type="text"></td>
</tr>
<tr>
<td></td><td><input type="submit" value="保存修改" class="btn" /></td>
</tr>
</table>
