<link href="/static/styles/global.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/static/styles/member.css" media="screen" rel="stylesheet" type="text/css" />
<?= $this->headTitle(' - 校友中心 - 杭州浙江大学校友会 - zjuhz.com','append'); ?>
<script type="text/javascript" src="/static/scripts/popup.js"></script>
<script type="text/javascript" src="/static/scripts/member/member.js"></script>