<?= $this->render('home/index.phtml'); ?>
<!-- 管理条目 ///////////////////////////////////// -->
<div class="sidebar" style="width:160px">
<p class="toolbar">
<a href="/class/home?c=<?= $this->class_id ?>"><img src="/static/images/icon/arrow_undo.gif" /> 返回</a>
</p>
</div>

<div class="sidebar class_show" style="width:500px; margin:0 10px;">
<h2 class="quiet"><img src="/static/images/icon/group.gif" /> 班级通讯录</h2>
<p class="quiet">
<a href="" class="focus">查看</a> | 
<a href="">我的信息</a> | 
<a href="">导出数据</a> | 
<a href="">导入数据</a> 
</p>
<div id="listInner"></div>
</div>

<!-- 班级基本信息 ///////////////////////////////////////// -->
<?= $this->render('home/baseinfo.phtml'); ?>