<div class="corner-box floatLeft">
			<b class="corner-box-title">申请注意事项</b>
			<ul style="padding-bottom:10px;">
				<li>所写内容必须真实</li>
				<li>我们一般是通过人工审核</li>
			</ul>
			<b class="corner-box-title">你已经申请的企业：</b>
			<ul>
				<li><a href="">企业1</a></li>
				<li><a href="">企业2</a></li>
			</ul>
			</div>
			
			<div class="floatLeft" style="padding-bottom:30px;">
			<h2>::新企业加入申请表::</h2>
			<form>
				<table class="table" style="margin:0 0 0 20px;" cellpadding="0" cellspacing="0">
				<tr>
					<td width="80" class="txtr">企业名称:</td>
					<td><input type="" />
					* </td>
				</tr>
				<tr>
					<td class="txtr">从事行业:</td>
					<td>
						<select>
              <option selected="selected" value="">--所有类别--</option>

              <option value="1">餐饮食品</option>
<option value="2">建筑、房地产</option>
<option value="3">旅游、观光</option>
<option value="4">商场百货</option>
<option value="5">生活服务</option>
<option value="6">电器通讯</option>
<option value="7">广告商展</option>
<option value="8">电脑IT、数码</option>

<option value="9">轻工制造</option>
<option value="10">交通运输</option>
<option value="11">机械、机电</option>
<option value="12">金融保险</option>
<option value="13">医疗保健</option>
<option value="14">传媒文化</option>
<option value="15">教育、培训</option>
<option value="16">专业服务</option>
<option value="17">娱乐健身</option>

<option value="18">能源化工</option>
<option value="19">环境保护</option>
<option value="20">农林牧渔</option>
<option value="43">其它类别</option>

            </select>
						*

					</td>
				</tr>
				<tr>
					<td class="txtr">所在地：</td>
				  <td><input type="" style="width:400px;" /></td>
				</tr>
				<tr>
					<td class="txtr">联系方式:</td>
					<td><input type="" style="width:400px;" /></td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td><input type="submit" value="提交申请" class="buttonGreen" /></td>
				</tr>
				</table>
				</form>
				</div>