	<div class="side-box floatRight">
			<div class="side-box-title">XX行业推荐企业</div>
			<ul>
				<li><a href=""><img src="images/upload/user/1/corporation/01.jpg" /><br />什么企业的名字</a></li>
				<li><img src="images/upload/user/1/corporation/02.jpg" /></li>
				<li><a href="">什么企业的名字</a></li>
				<li><img src="images/upload/user/1/corporation/03.jpg" /></li>
				<li><a href="">什么企业的名字</a></li>
				<li><a href=""><img src="images/upload/user/1/corporation/01.jpg" /><br />什么企业的名字</a></li>
				<li><img src="images/upload/user/1/corporation/02.jpg" /></li>
				<li><a href="">什么企业的名字</a></li>
				<li><img src="images/upload/user/1/corporation/03.jpg" /></li>
				<li><a href="">什么企业的名字</a></li>
			</ul>
		</div>
	
		<div class="mid-box-with-left">
			<div class="mid-box-intro">
			<a href="">校友企业展示平台</a> &raquo; xx行业 
				<input type="text" value="" /> 
				<input type="button" class="button" value="企业搜索" /> <input type="button" class="buttonGreen" value="申请加入" />
				<hr />
				<table class="table" width="100%" cellpadding="0" cellspacing="0">
				<tbody><tr>
				    
                <td width="33%"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  安全、防护</a> (1042) 
				</td>
				
                <td width="33%"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  包装、纸</a> (1604) 
				</td>
				
                <td width="33%"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  办公文教</a> (421) 
				</td>

				
              </tr>
		
          
                <tr><td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  电脑与软件</a> (384) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  电子电工</a> (1576) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  纺织、皮革</a> (308) 
				</td>

				
              </tr>
		
          
                <tr><td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  服装服饰</a> (469) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  机械设备</a> (2345) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  化工</a> (1270) 
				</td>

				
              </tr>
		
          
                <tr><td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  公共设施、环保</a> (346) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  家居用品</a> (647) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  家用电器</a> (396) 
				</td>

				
              </tr>
		
          
                <tr><td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  建筑、装饰</a> (1029) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  交通运输</a> (513) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  礼品、工艺品</a> (839) 
				</td>

				
              </tr>
		
          
                <tr><td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  能源、治金、矿产</a> (842) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  农林渔牧</a> (590) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  食品、饮料、烟酒</a> (472) 
				</td>

				
              </tr>
		
          
                <tr><td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  五金制品、工具</a> (785) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  通讯</a> (471) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  玩具</a> (116) 
				</td>

				
              </tr>
		
          
                <tr><td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  仪器、仪表</a> (565) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  印刷、出版</a> (351) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  运动、娱乐</a> (295) 
				</td>

				
              </tr>
		
          
                <tr><td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  医疗、保健</a> (417) 
				</td>
				
                <td align="left" valign="top"><img src="images/j.gif" width="8" height="7"> 
                  <a href="" target="_blank"> 
                  商业服务</a> (1541) 
				</td>
				
					
                  </tr></tbody>
				</table>
			</div>
			
			
			<table class="table" cellpadding="0" cellspacing="0" width="100%" style="margin-top:10px;">
				<thead>
					<tr>
						<th colspan="3" class="table-top-left" width="60%">XX行业最新加入公司</th>
						<th>经营模式&amp;产品<img src="/static/images/icon/paixu.gif"></th>
						<th class="table-top-right"></th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<td class="table-bottom-left"></td>
						<td colspan="3"></td>
						<td class="table-bottom-right"></td>
					</tr>
				</tfoot>
				<tbody>
					<tr>
						<td class="left lh150" colspan="3">
							<a href=""><img src="images/upload/user/1/corporation/01.jpg" class="floatLeft pd10" /></a>
									<a href=""><b>杭州友笑网络科技有限公司</b></a><br />
								杭州友笑网络科技有限公司是一家致力于校友社交的..
							
						</td>
						
						<td class="left lh150">
							模式: 自主开发<br />
							产品: zjuhz.com
						</td>
						
						<td class="right">留言咨询</td>
					</tr>
					<tr class="even">
						<td class="left lh150" colspan="3">
							<img src="images/upload/user/1/corporation/01.jpg" class="floatLeft pd10" />
									<b>杭州友笑网络科技有限公司</b><br />
								杭州友笑网络科技有限公司是一家致力于校友社交的..
							
						</td>
						
						<td class="left lh150">
							模式: 自主开发<br />
							产品: zjuhz.com
						</td>
						
						<td class="right">留言咨询</td>
					</tr>
					<tr>
						<td class="left lh150" colspan="3">
							<img src="images/upload/user/1/corporation/01.jpg" class="floatLeft pd10" />
									<b>杭州友笑网络科技有限公司</b><br />
								杭州友笑网络科技有限公司是一家致力于校友社交的..
							
						</td>
						
						<td class="left lh150">
							模式: 自主开发<br />
							产品: zjuhz.com
						</td>
						
						<td class="right">留言咨询</td>
					</tr>
					<tr class="even">
						<td class="left lh150" colspan="3">
							<img src="images/upload/user/1/corporation/01.jpg" class="floatLeft pd10" />
									<b>杭州友笑网络科技有限公司</b><br />
								杭州友笑网络科技有限公司是一家致力于校友社交的..
							
						</td>
						
						<td class="left lh150">
							模式: 自主开发<br />
							产品: zjuhz.com
						</td>
						
						<td class="right">留言咨询</td>
					</tr>
				</tbody>
			</table>
			
		</div>