<?= $this->render('group-head.phtml'); ?>
<div class="span-24 last">
	<?= $this->render('sidebar.phtml'); ?>
<div class="span-19 last mgu10">
    <div class="oneCol">
        <?= $this->invitetab($this->action_name, $this->gid)  // 邀请TAB连接 ?>
        <span id="tip"></span>
        <form id="groupForm" method="post" onsubmit="return false">
        <table class="mglf10" width="720" cellpadding="0" cellspacing="0">
            <tr style="font-weight:bold">
                <!--<th class="pd5"></th>-->
                <th class="txtc pd5">头像</th>
                <th class="txtc pd5">姓名</th>
                <th class="txtc pd5">性别</th>
                <th></th>
            </tr>
            <?php if($this->applies): foreach($this->applies as $uid): ?>
            <tr id="apply_<?= $uid ?>">
                <!--<td class="vm txtc"><input type="checkbox" /></td>-->
                <td class="pd5 txtc dashBorder" width="10%"><?= Commons::getUserFace($uid) ?></td>
                <td class="vm txtc dashBorder">
                    <a href="/member/profile?uid=<?= $uid ?>"><?= UserModel::fetch($uid, 'realName') ?></a>
                </td>
                <td class="vm txtc dashBorder"><?= UserModel::fetch($uid, 'sex') ?></td>
                <td class="vm txtc dashBorder">
                    <?php if(!UserModel::isInvited($this->gid, $uid)): ?>
                    <button onclick="doInvite(<?= $uid.','.$this->gid ?>)" class="btn">邀请</button>
                    <button onclick="doDel(<?= $uid.','.$this->gid ?>)" class="btn">删除</button>
                    <?php else: ?>
                    已经邀请
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; else: ?>
            <tr>
                <td colspan="5" class="pd5">目前没有想加入本群组的校友..</td>
            </tr>
            <?php endif; ?>
        </table>
        </form>
    </div>
</div>
</div>

<script type="text/javascript">
    function doDel(uid, gid)
    {
        $.post('/group/invite/apply?do=del', {uid:uid, gid:gid}, function(html){
            $('#apply_'+uid).fadeOut();
        });
    }
    
    function doInvite(uid, gid)
    {
        $.post('/group/invite/do', {uid:uid, gid:gid}, function(html){
            $('#tip').html(html);
            doDel(uid, gid);
        });
    }
</script>