<?= $this->render('group-head.phtml'); ?>
<div class="span-24 last">
	<?= $this->render('sidebar.phtml'); ?>
<div class="span-19 last mgu10">
    <div class="oneCol">
        <?= $this->invitetab($this->action_name, $this->gid)  // 邀请TAB连接 ?>
        <form id="search_form" method="post" class="mglf10" onsubmit="return doSearch()">
            <p class="txtc">姓名 <input name="name" type="text" class="text" /></p>
            <p class="txtc">
                <label for="male">男<input id="male" type="radio" name="sex" value="男" /></label> &nbsp;&nbsp;&nbsp;
                <label for="female">女<input id="female" type="radio" name="sex" value="女" /></label>
            </p>
            <p class="txtc">入学年份 <input type="text" name="year" class="text" /></p>
            <p class="txtc">所读学院 <select name="college">
				<option value="">--- 请选择学院 ---</option>
				<?php foreach($this->college as $k=>$v): ?>
				<option value="<?= $k ?>"><?= $v ?></option>
				<?php endforeach ?>
				</select></p>
            <p class="txtc">所在城市 
					<select name="province"></select>
					<select name="city"></select>
            </p>
            <p class="txtc">
                <input type="submit" value="进行搜索" class="btn" style="width:60%" />
            </p>
            <p class="txtc" id="search_tip"></p>
            <br />
            <br />
        </form>
    </div>
</div>
<script type="text/javascript" src="/static/scripts/PCASClass.js"></script>
<script type="text/javascript">
    new PCAS("province","city");
    function doSearch()
    {
        $.post('/group/invite/search?gid=<?= $this->gid ?>',
               $('#search_form').fastSerialize(),
               function(html){
            $('#search_tip').html(html);
        });
        return false;
    }
</script>