<form class="home_form">
<table>
<tr>
<td align="right"><b>姓名：</b></td>
<td><input class="txt" type="text"></td>
</tr>
<tr>
<td align="right"><b>所属分类：</b></td>
<td><select>
<option>大学同学</option>
<option>硕士同学</option>
<option>博士同学</option>
<option>其他校友</option>
<option>大学老师</option>
<option>硕士老师</option>
<option>博士老师</option>
</select></td>
</tr>
<tr>
<td align="right"><b>QQ：</b></td>
<td><input class="txt" type="text"></td>
</tr>
<tr>
<td align="right"><b>邮箱：</b></td>
<td><input class="txt" type="text"></td>
</tr>
<tr>
<td align="right"><b>MSN：</b></td>
<td><input class="txt" type="text"></td>
</tr>
<tr>
<td align="right"><b>手机：</b></td>
<td><input class="txt" type="text"></td>
</tr>
<tr>
<td></td><td><input type="submit" value="保存修改" class="btn" /></td>
</tr>
</table>
</form>