<div class="control_tab">
<a href="?sub=personal&tab=account">账号信息</a>
<a href="?sub=personal&tab=contact">通讯信息</a>
<a href="?sub=personal&tab=job">工作信息</a>
</div>

<div class="control_action">
<?= $this->render('index/home-data-personal-'.$this->tab.'.phtml'); ?>
</div>
<script>
$('.control_tab a').removeClass('focus');
$('.control_tab a[href="?sub=personal&tab=<?= $this->tab ?>"]').addClass('focus');
</script>