<form class="home_form">
                        <p>
							<b>QQ：</b>
							<input name="qq" size="40" tabindex="1" value="" id="qq" class="txt" type="text">
        				</p>
        				<p>
							<b>MSN：</b>

							<input name="msn" size="40" tabindex="2" value="" id="msn" class="txt" type="text">
							
        				</p>
        				<p>
							<b>手机：</b>
							<input name="cellPhone" size="40" tabindex="3" value="" id="cellPhone" class="txt" type="text">
        				</p>
        				<p>
							<b>电话：</b>

							<input name="fixPhone" size="40" tabindex="4" value="" id="fixPhone" class="txt" type="text">
        				</p>
        				<p>
							<b>个人网站：</b>
							<input name="homepage" size="40" tabindex="5" value="http://" id="homepage" class="txt" type="text">
        				</p>
        				<p>
        					<input type="submit" value="保存修改" class="btn" />
        				</p>
</form>