<!-- 左侧栏 //////////////////////////////////////// -->
<div class="sidebar">
<div class="member_card">
<table>
<tr>
<td><img src="/static/users/user_test/tiny_head.jpg" class="head" /></td>
<td>
<p>小王</p>
<p>积分 100</p>
</td>
</tr>
</table>
</div>

<div class="control_link">
<a href="?sub=base" class="focus">基本信息</a>
<a href="?sub=contact">联系方式</a>
<a href="?sub=personal">个人信息</a>
<a href="?sub=job">工作信息</a>
<a href="?sub=portrait">我的头像</a>
<a href="?sub=privacy">隐私控制</a>
</div>
</div>

<script>
$('.control_link a').removeClass('focus');
$('.control_link a[href="?sub=<?= $this->sub ?>"]').addClass('focus');
</script>

<!-- 中间部分 ////////////////////////////////////////// -->
<div class="sidebar">
<h2 class="control_nav">
资料 - <a href="/temp/index/home/">互助</a> - <a href="/temp/index/home/of/class">班级</a> - <a href="/temp/index/home/of/address_list">通讯录</a> - <a href="">相册</a> - <a href="">日志</a> - <a href="">活动</a>
</h2>
<div class="control_content">
<?php echo $this->render('index/home-data-'.$this->sub.'.phtml'); ?>
</div>

</div>