<div class="control_tab">
<a href="?sub=<?= $this->sub ?>&tab=wait">等待中的问题</a>
<a href="?sub=<?= $this->sub ?>&tab=close">结束的问题</a>
</div>

<div class="control_action">
<?= $this->render('index/home-help-'.$this->sub.'-'.$this->tab.'.phtml'); ?>
</div>
<script>
$('.control_tab a').removeClass('focus');
$('.control_tab a[href="?sub=<?= $this->sub ?>&tab=<?= $this->tab ?>"]').addClass('focus');
</script>