<table class="control_list">
<tr>
<th width="500">
<form>
<select class="txt">
<option>所有分类：</option>
<option>大学同学</option>
<option>硕士同学</option>
<option>博士同学</option>
<option>其他校友</option>
<option>大学老师</option>
<option>硕士老师</option>
<option>博士老师</option>
</select>
<select class="txt">
<option>所有信息：</option>
<option>名字</option>
<option>手机</option>
<option>邮箱</option>
<option>地址</option>
</select>
<input type="text" class="txt" value="目前已有 xx 条记录" onfocus="this.value=''" onblur="this.value='目前已有 xx 条记录'" /> 
<input type="submit" class="btn" value="查找" />
</form>
</th>
<th class="txtl">状态</th>
<th>操作</th>
</tr>
<tr>
<td>
<a href="javascript:address_detail(1)">某某某1</a>
<table class="address_detail n1">
<tr>
<td><img src="/static/images/icon/phone.gif" /></td>
<td>13588063022</td>
</tr>
<tr>
<td><img src="/static/images/icon/email.gif" /></td>
<td>linyupark@gmail.com</td>
</tr>
<tr>
<td><img src="/static/images/icon/qq.gif" /></td>
<td>178673235</td>
</tr>
<tr>
<td><img src="/static/images/icon/msn.gif" /></td>
<td>linyupark@msn.com</td>
</tr>
<tr>
<td><img src="/static/images/icon/building.gif" /></td>
<td>浙江省杭州市学院路130号（中宙大厦）718室</td>
</tr>
</table>
</td>
<td><img src="/static/images/bullet/orange.gif" /></td>
<td>
<a href="">修改</a>
<a href="">邀请</a>
</td>
</tr>


<tr>
<td>
<a href="javascript:address_detail(2)">某某某2</a>
<table class="address_detail n2">
<tr>
<td><img src="/static/images/icon/phone.gif" /></td>
<td>13588063022</td>
</tr>
<tr>
<td><img src="/static/images/icon/email.gif" /></td>
<td>linyupark@gmail.com</td>
</tr>
<tr>
<td><img src="/static/images/icon/qq.gif" /></td>
<td>178673235</td>
</tr>
<tr>
<td><img src="/static/images/icon/msn.gif" /></td>
<td>linyupark@msn.com</td>
</tr>
<tr>
<td><img src="/static/images/icon/building.gif" /></td>
<td>浙江省杭州市学院路130号（中宙大厦）718室</td>
</tr>
</table>
</td>
<td><img src="/static/images/bullet/orange.gif" /></td>
<td>
<a href="">修改</a>
<a href="">邀请</a>
</td>
</tr>
</table>

<script>
function address_detail(n)
{
	$('.n'+n).toggle();
}
$('.control_list tr').each(function(e){ if(e%2 == 0) $(this).children().each(function(){ $(this).css('background','#fff') }); });
//$('.address_detail tr').each(function(e){ if(e%2 == 0) $(this).children().each(function(){ $(this).css('background','#fff') }); });
</script>

<div class="pagination"><a href="">1</a><a href="">2</a><b>3</b></div>