<?= $this->render('group-head.phtml'); ?>
<div class="span-24 last">
	<?= $this->render('sidebar.phtml'); ?>
<div class="span-19 last mgu10">
    <div class="oneCol">
        <?= $this->invitetab($this->action_name, $this->gid)  // 邀请TAB连接 ?>
        <span id="tip"></span>
        <form id="groupForm" method="post" onsubmit="return false">
        <table class="mglf10" width="720" cellpadding="0" cellspacing="0">
            <tr style="font-weight:bold">
                <!--<th class="pd5"></th>-->
                <th class="txtc pd5">头像</th>
                <th class="txtc pd5">姓名</th>
                <th class="txtc pd5">性别</th>
                <th></th>
            </tr>
            <?php if($this->vogs): foreach($this->vogs as $v): ?>
            <tr>
                <!--<td class="vm txtc"><input type="checkbox" /></td>-->
                <td class="pd5 txtc dashBorder" width="10%"><?= Commons::getUserFace($v['uid']) ?></td>
                <td class="vm txtc dashBorder">
                    <a href="/group/member/profile?uid=<?= $v['uid'] ?>"><?= $v['realName'] ?></a>
                </td>
                <td class="vm txtc dashBorder"><?= $v['sex'] ?></td>
                <td class="vm txtc dashBorder">
                    <?php if(!UserModel::isInvited($this->gid, $v['uid'])): ?>
                    <button onclick="doInvite(<?= $v['uid'].','.$this->gid ?>)" class="btn">邀请</button>
                    <?php else: ?>
                    已经邀请
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; else: ?>
            <tr>
                <td colspan="5" class="pd5">目前没有无组人士..</td>
            </tr>
            <?php endif; ?>
        </table>
        </form>
        <p class="txtc">
            共找到<?= $this->vog_num ?>名，
            现在显示<?= $this->offset ?>到<?= ($this->offset+$this->pagesize-1) ?>
        </p>
        <p class="pagination mglf10">
            <?= $this->pagination ?>
        </p>
    </div>
</div>
</div>

<script type="text/javascript">
    function doInvite(uid, gid)
    {
        $.post('/group/invite/do', {uid:uid, gid:gid}, function(html){
            $('#tip').html(html);
        });
    }
</script>