<table>
	<tr>
		<td>
			<form class="home_form" name="frmFind" id="frmFind" autocomplete="off">
			<input type="button" class="btn" value="新建名片" name="btnInsert" id="btnInsert" onclick="javascript:docardBefore('<?= $this->cid; ?>');return false;" />
			</form>
		</td>
		<td>
			<form>
			<select class="inputtxt" name="gid" id="gid"><option>所有组</option><?php foreach ($this->groupList as $value)  { ?>
			<option value="<?= $value['gid']; ?>"><?= $value['gname']; ?></option><?php } ?></select>
			<select class="inputtxt" name="field" id="field"><option value="cname">按姓名</option><option value="mobile">按手机</option><option value="eMail">按邮箱</option><option value="qq">按QQ</option><option value="msn">按MSN</option><option value="address">按地址</option><option value="memo">按备注</option></select>
			<input type="text" class="inputtxt" value="" name="wd" id="wd" /> 
			<input type="submit" class="btn" value="查找" />
			</form>
		</td>
	</tr>
</table>

<?php if ($this->total > 0) { ?>
<table class="control_list">
<tr>
<th class="txtl" width="10%">姓名</th>
<th class="txtl" width="50%">已建立联络方式</th>
<th class="txtl" width="20%">所属组</th>
<th class="txtl" width="20%">选项</th>
</tr>

<?php foreach ($this->cardList as $value) { ?>
<tr>


<td class="txtl">
<a href="#" onclick="javascript:docardBefore('<?= $value['cid']; ?>');return false;"><?= $value['cname']; ?></a>
</td>

<td class="txtl">
<?php if (!empty($value['mobile'])) { ?><img src="/static/images/icon/phone.gif" alt="<?= $value['mobile']; ?>" />&nbsp;<?php  }; ?>
<?php if (!empty($value['eMail'])) { ?><a href="mailto:<?= $value['eMail']; ?>"><img src="/static/images/icon/email.gif" alt="向该好友发邮件" /></a>&nbsp;<?php  }; ?>
<?php if (!empty($value['qq'])) { ?><a target=blank href=http://wpa.qq.com/msgrd?V=1&Uin=<?= $value['qq']; ?>&Site=zjuhz.com&Menu=yes><img src="/static/images/icon/qq.gif" alt="与该好友QQ联系" /></a>&nbsp;<?php  }; ?>
<?php if (!empty($value['msn'])) { ?><a href=msnim:chat?contact=<?= $value['msn']; ?>><img src="/static/images/icon/msn.gif" alt="与该好友MSN联系" /></a>&nbsp;<?php  }; ?>
<?php if (!empty($value['address'])) { ?><img src="/static/images/icon/building.gif" alt="<?= $value['address']; ?>" /><?php  }; ?>
</td>

<td class="txtl">
<?= $value['gname']; ?>
</td>

<td class="txtl">
<a href="#" onclick="javascript:docardBefore('<?= $value['cid']; ?>');return false;">修改</a>&nbsp;&nbsp;<a href="#" onclick="javascript:doinviteBefore('<?= $value['cid']; ?>');return false;">邀请</a>
</td>

</tr>
<?php } ?>

</table>
<?= $this->paging; ?>
<?php } ?>