<table>
<tr>
<td align="right"><b>手机：</b><br /><br /></td>
<td><input tabindex="1" value="<?= $this->sessCommon->login['mobile']; ?>" class="txt" type="text" id="mobile" name="mobile" maxlength="11"> <br /><span class="quiet f12">以13或15开头号码，如13812345678。</span></td>
</tr>
<tr>
<td align="right"><b>电话：</b><br /><br /></td>
<td><input tabindex="1" value="<?= $this->sessCommon->login['phone']; ?>" class="txt" type="text" id="phone" name="phone" maxlength="13"> <br /><span class="quiet f12">小灵通号码也可，格式应为：区号-号码，如0571-12345678。</span></td>
</tr>
<tr>
<td align="right"><b>电子邮箱：</b></td>
<td><input tabindex="2" value="<?= $this->sessCommon->login['eMail']; ?>" class="txt" type="text" id="eMail" name="eMail" maxlength="50"></td>
</tr>
<tr>
<td align="right"><b>QQ：</b></td>
<td><input tabindex="3" value="<?= $this->sessCommon->login['qq']; ?>" class="txt" type="text" id="qq" name="qq" maxlength="15"></td>
</tr>
<tr>
<td align="right"><b>MSN：</b></td>
<td><input tabindex="4" value="<?= $this->sessCommon->login['msn']; ?>" class="txt" type="text" id="msn" name="msn" maxlength="50"></td>
</tr>
<tr>
<td align="right"><b>联系地址：</b></td>
<td><input tabindex="5" value="<?= $this->sessCommon->login['address']; ?>" class="txt" type="text" id="address" name="address" maxlength="80"></td>
</tr>
<tr>
<td align="right"><b>邮政编码：</b></td>
<td><input tabindex="6" value="<?= $this->sessCommon->login['postcode']; ?>" class="txt" type="text" id="postcode" name="postcode" maxlength="6"></td>
</tr>
<tr>
<td align="right"><b>其它方式：</b><br /><br /><br /></td>
<td><textarea name="other" cols="30" class="txt" id="other" tabindex="7"><?= $this->sessCommon->login['other']; ?>
</textarea> <br /><span class="quiet f12">在此可输入其它联系方式，如Skype/新浪UC/其它手机号码/其它电话号码等。</span></td>
</tr>
<tr>
<td></td><td><input type="submit" value="保存修改" class="btn" id="btnUser" name="btnUser" /></td>
</tr>
<tr>
<td></td>
<td><div id="ajaxhint" style="width:300px"></div></td>
</tr>
</table>
