<table>
<tr>
<td align="right"><b>我的头像：</b><br /><br /><br /></td>
<td><span id="userFace"><?= $this->face($this->sessCommon->login['uid']); ?></span> <a href="#" id="showUpload" class="btn">更改头像</a> <a target="_blank" href="http://www.zjuhz.com/info/view/detail/id/149">照片处理帮助</a><span id="previewImage"></span></td>
</tr>
<tr id="doUpload" style="display:none">

<script type="text/javascript">
		var swfu;

		window.onload = function () {
			swfu = new SWFUpload({
				upload_url: "/member/my/doface/", 
				file_post_name: "fileData", 

				file_size_limit : "31", 
				file_types : "*.jpg", 
				file_types_description : "JPG Files", 
				file_upload_limit : "0", 
				file_queue_limit : "1", 

				swfupload_loaded_handler : swfUploadLoaded,

				file_queued_handler : fileQueued, 
				file_queue_error_handler : fileQueueError, 
				file_dialog_complete_handler : fileDialogComplete, 

				upload_progress_handler : uploadProgress, 
				upload_error_handler : uploadError, 
				upload_success_handler : uploadSuccess, 
				upload_complete_handler : uploadComplete, 

				flash_url : "/static/swfs/swfupload_f9.swf", 

				swfupload_element_id : "flashUI", 
				degraded_element_id : "degradedUI", 

				custom_settings : {
					progress_target : "fsUploadProgress",
					upload_successful : false
				},

				debug: false
			});
		};
</script>

<td></td>
<td><div id="flashUI" style="display: none;"><input type="text" id="fileName" readonly class="inputtxt" size="32" />&nbsp;<input id="btnBrowse" type="button" value="选择头像..." onclick="fileBrowse.apply(swfu)" />&nbsp;<input type="button" value=" 上 传 " id="btnUpload" /><br /><span class="quiet f12">* 头像必须是jpg格式的图片文件，大小在30KB以内，建议图片尺寸200*200。</span></div><div id="fsUploadProgress"></div><div id="degradedUI"><span class="f12">* <a href="/member/my/face/">点击这里立即上传我的新头像 >>></a></span></div></td>
</tr>
<tr>
<td align="right"><b>登录账号：</b></td>
<td><?= $this->sessCommon->login['username']; ?></td>
</tr>
<tr>
<td align="right"><b>真实姓名：</b></td>
<td><?= $this->sessCommon->login['realName']; ?></td>
</tr>
<tr>
<td align="right"><b>性别：</b></td>
<td><?= $this->sessCommon->login['sex']; ?></td>
</tr>
<tr>
<td align="right"><b>入学信息：</b></td>
<td><select name="year" id="year" tabindex="7"><option>入学年份</option><?php for ($i=1970;$i<=2008;$i++) { ?><option <?= ($i == $this->sessCommon->login['year'] ? 'selected' : ''); ?> value="<?= $i; ?>"><?= $i; ?>年</option><?php } ?></select>&nbsp;<select name="college" id="college" tabindex="8"><option>院系名称</option><?php foreach ($this->college() as $key => $value) { ?><option <?= ($key == $this->sessCommon->login['college'] ? 'selected' : ''); ?> value="<?= $key; ?>"><?= $value; ?></option><?php } ?></select>&nbsp;<br /></td>
</tr>
<tr>
<td align="right"><b>所学专业：</b><br /><br /></td>
<td><input name="major" id="major" tabindex="9" class="inputtxt" type="text" size="37" maxlength="30" value="<?= $this->sessCommon->login['major']; ?>" />&nbsp;<br /><span class="quiet f12">输入当时的专业名称(应与入学年份、院系名称相对应，不用含班级名称)。</span><br /></td>
</tr>
<tr>
<td align="right"><b>曾用名：</b><br /><br /></td>
<td><input type="text" class="txt" name="everName" id="everName" maxlength="10" value="<?= $this->sessCommon->login['everName']; ?>" /> <br /><span class="quiet f12">输入您曾经使用过的名字以便校友找到您。</span></td>
</tr>
<?= $this->calendar(); ?>
<tr>
<td align="right"><b>出生日期：</b><br /><br /></td>
<td><input type="text" class="txt" name="birthday" id="birthday" maxlength="10" value="<?= $this->sessCommon->login['birthday']; ?>" /> <a href="#" id="calendar">显示日历</a> <br /><span class="quiet f12">格式应为：年-月-日，如1998-04-07。</span></td>
</tr>
<?= $this->pcas(); ?>
<tr>
<td align="right"><b>我的家乡：</b><br /><br /></td>
<td><select name="hometown_p" id="hometown_p"></select>&nbsp;<select name="hometown_c" id="hometown_c"></select>&nbsp;<select name="hometown_a" id="hometown_a"></select> <br /><span class="quiet f12">可选择至最后县/市/区一层，我们会帮您找到同乡校友。</span></td>
</tr>
<tr>
<td align="right"><b>当前所在地：</b><br /><br /></td>
<td><select name="location_p" id="location_p"></select>&nbsp;<select name="location_c" id="location_c"></select>&nbsp;<select name="location_a" id="location_a"></select> <br /><span class="quiet f12">想知道哪些校友与您当前在同一个地点吗？</span></td>
</tr>
<tr>
<td></td>
<td><input type="submit" value="保存修改" class="btn" name="btnUser" id="btnUser" /></td>
</tr>
<tr>
<td></td>
<td><div id="ajaxhint" style="width:300px"></div></td>
</tr>
</table>
<script language="javascript" type="text/javascript">Calendar.setup({inputField : "birthday", button : "calendar"});</script>
<script language="javascript" type="text/javascript">new PCAS("hometown_p","hometown_c","hometown_a","<?= $this->sessCommon->login['hometown_p']; ?>","<?= $this->sessCommon->login['hometown_c']; ?>","<?= $this->sessCommon->login['hometown_a']; ?>");</script>
<script language="javascript" type="text/javascript">new PCAS("location_p","location_c","location_a","<?= $this->sessCommon->login['location_p']; ?>","<?= $this->sessCommon->login['location_c']; ?>","<?= $this->sessCommon->login['location_a']; ?>");</script>
