    <table>
      <tr>
        <td style="vertical-align:top;"><div class="menu-box">
            <ul>
              <li><span style="font-size:14px;">相关链接</span></li>
              <li><a href="">自定义链接1</a>
                <ul>
                  <li><a href="">asdasdasd</a></li>
                </ul>
              </li>
              <li><a href="">自定义链接2</a></li>
              <li><a href="">自定义链接3</a></li>
              <li><a href="">自定义链接4</a></li>
            </ul>
          </div>
          <div class="corner-box" style="width:170px;">
            <h2 class="corner-box-title">最新留言</h2>
            <p><a href="">KFC</a> <small>08-06-07</small>: <br />
              您好，我想问一下xxxxxxxxxxxx</p>
            <br />
            <p class="floatRight"><a href="">进入留言本..</a></p>
          </div></td>
        <td class="pd10"><div class="mid-box-right">
            <h2 class="mid-box-right-title">公司简介</h2>
            <div class="mid-box-right-content"> <img src="images/upload/user/1/company/intro.jpg" /> 上海美亚企业（集团）有限公司（以下简称“美亚集团”）是一个集策略投资和经营管理为一体的综合型投资管理公司，公司成立于2000年，注册资金为一亿元人民币。目前旗下有上海美亚音像连锁经营有限公司、上海美亚二十一世纪商业发展有限公司、上海美亚在线宽频网络有限公司、上海美亚文化传播有限公司、五洲宽频电视传播有限公司、上海美亚信息工程技术有限公司、上海长乐花苑餐饮娱乐有限公司、北京飞帆影视制作有限公司。美亚集团通过投资控股及参与日常经营管理实现对各子公司的管理，并且通过集团化经营，发挥整体优势，合理统筹，掌控全局。 </div>
          </div>
          <table class="detail" cellspacing="0" cellpadding="0" width="737">
            <tr>
              <th colspan="4">详细介绍</th>
            </tr>
            <tr>
              <td width="72" bgcolor="#F0F3E5"><strong>主营产品<br />
                或服务：</strong></td>
              <td width="285">跳泡;C7灯泡;T20指示泡;G40;小夜灯泡;普通照明灯泡;火焰泡;花泡;圣诞灯;节日灯 </td>
              <td width="76" bgcolor="#F0F3E5"><strong>主营行业：</strong></td>
              <td width="280">灯具配附件 工艺装饰灯具 道路照明灯 室内照明灯具 白炽灯 应急指示灯具 其他灯具配附件 其他室内照明灯具</td>
            </tr>
            <tr>
              <td bgcolor="#F0F3E5"><strong>人才招聘：</strong></td>
              <td><strong>网络工程师 </strong><br />
                1.维护公司网络的安全；<br />
                2.负责公司服务器、办公电话、传真机、监控广播系统等网络设备的软、硬件维护和管理<br />
                3.负责系统测试、数据备份、应用程序改动、软件更新、终端维护工作；<br />
                4.局域网的维护工作；<br />
                5.维护网络安全，定期杀毒工作；<br />
                6.网站建设工作及网站相关软件的开发工作. <br />
                <br />
                <strong>任职资格：</strong><br />
                1、大专以上学历，计算机专业；<br />
                2、5年以上网络监控与管理经验，其中2年以上ERP或数据库管理和维护工作经验；<br />
                3、熟悉网络综合布线系统和交换机、路由器、防火墙的配置和维护，具有丰富的电脑维修经验；<br />
                4、善于沟通，耐心指导，虚心讲解，处理突发事件能力强；<br />
                5、具有CCIE、CCNP等网络技术资格证书及有外贸公司网管工作经验者优先。</td>
              <td bgcolor="#F0F3E5"><strong>联系方式：</strong></td>
              <td> 办公地址：<br />
                邮政编码：<br />
                电话：<br />
                传真： <br />
                网址：<br />
                邮箱： <br />
                手机： </td>
            </tr>
            <tr>
              <td bgcolor="#F0F3E5"><strong>合作需求：</strong></td>
              <td colspan="3"></td>
            </tr>
          </table></td>
      </tr>
    </table>