<div class="corner-box floatLeft">
    <b class="corner-box-title">企业标志</b>
    <ul style="padding-bottom:10px;">
        <li>正在完善企业标志</li>
    </ul>
</div>

<div class="floatLeft" style="padding-bottom:30px;">
  <h2>修改企业标志LOGO</h2>

  <table class="table" style="margin:0 0 0 20px;" width="650px" cellpadding="0" cellspacing="0">
      <tr>
        <td width="100">&nbsp;</td>
        <td width="400"><?= $this->Companyface($this->dataCompany['cid']); ?> <span id="previewImage"></span></td>
        <td width="150">&nbsp;</td>
      </tr>
      <tr>
	    <td>&nbsp;</td>
	    <td><input type="file" name="fileData" onkeypress="return false;" id="fileData" size="40" onchange="document.getElementById('previewImage').innerHTML = '&nbsp;&nbsp;&nbsp;=>&nbsp;&nbsp;&nbsp;<img src=\''+this.value+'\' width=54 height=54>';"></td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td colspan="2"><input type="submit" id="btnLogo" value=" 提 交 修 改 " class="buttonGreen" disabled />&nbsp;<a target="_blank" href="http://www.zjuhz.com/info/view/detail/id/149">照片处理帮助</a> <img id="loading" src="/static/images/loading1.gif" style="display:none;"><table width="100%" border="0"><tr><td colspan="2"><img src="/static/images/icon/lightbulb.gif">&nbsp;&nbsp;<span class="quiet f12">标志LOGO必须是jpg格式的图片文件，大小在50KB以内，建议图片尺寸200*200。</span></td></tr></table></td>
      </tr>
  </table>

</div>
