<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
<meta http-equiv="Content-Language" content="zh-CN" >
<title>信息提示 - 杭州浙江大学校友会 - zjuhz.com</title>
<meta name="keywords" content="">
<meta name="description" content="">
<link rel="stylesheet" type="text/css" href="/static/styles/common.css">
<link rel="stylesheet" type="text/css" href="/static/styles/member.css">
</head>

<body>
<div id="ajaxloading"></div>
<div id="login">
    <div><a href="/" id="logo"><b>zjuhz.com</b><p>杭州浙江大学校友会</p></a></div>

    <div class="reg_tit"><a href="/member/">会员中心</a> >> 信息提示</div>	
	<div class="zc">
	<ul>	
      <li class="msg" style="margin-top:10px;"><span class="reg_tda"></span></li>
      <li><span class="reg_tda"></span></li>
      <li><span class="reg_tda"></span></li>
	  <li><span class="reg_tda"><p align="center"><?php echo $this->message; ?></p></span></li>

      <li></li>
	</ul>
	</div>
	
</div>
<br /><br />
<div id="footer">
  <p><a href="">帮助</a> | <a href="">关于</a> | <a href="">客服</a> | <a href="">隐私声明</a></p>
  <p><span style="float:right; margin-top:-23px;">杭州浙江大学校友会(筹) &copy; 2008 
  <a href="http://www.miibeian.gov.cn" target="_blank">浙ICP备06052510号</a></span></p>
</div>
</body>

</html>
