<div class="sidebar" style="padding:20px; border:1px solid #CDD8EF; background:#EFF7F7; width:750px; margin:30px;">
<h2><img src="/static/images/icon/stop.gif" /> <?= $this->message; ?></h2>
<hr />
<div class="sidebar">
<p class="pud5"><b class="quiet">本站尚处于开发阶段，目前支持以下应用，有需要改进的地方欢迎与我们联系</b></p>
<ul class="quiet">
<li><a href="/class">班级</a></li>
<li><a href="/help">互助</a></li>
</ul>
</div>
</div>