<form id="comment_form" onsubmit="return postComment()">
<input type="hidden" name="entity_id" value="<?= $this->entity_id ?>" />
<h2 class="quiet f14">提交评论</h2>
<span id="result"></span>
<p><textarea class="inputtxt" name="content" style="width:500px;height:180px;"></textarea></p>
<p class="pud10 txtr"><input type="submit" class="btn" value="提交评论" /></p>
</form>

<script type="text/javascript">
	function postComment()
	{
		$.post('/info/comment/post', $('#comment_form').fastSerialize(), function(html){
			$.facebox(html);
			commentView(<?= $this->entity_id ?>,1);
		});
		return false;
	}
</script>