<div class="mg10">
<h3 style="border-bottom:1px dashed #ccc; margin-bottom:5px;"><?= Cmd::icon('heart.png') ?> 衷心鸣谢</h3>
<a target="_blank" href="http://www.chinayaojiang.com/cpzx/wdy/index.asp"><img src="/static/images/3x/yjwdy.gif" /></a>
<a target="_blank" href="http://v2.zjuhz.com/addon_partners/?cid=5"><img src="/static/images/3x/jsyh.gif" /></a>
<a target="_blank" href="http://www.bankcomm.com/"><img src="/static/images/3x/jtyh.gif" /></a>
</div>