<div class="mgu10">     
        <ul class="mglf10">
            <h3 class="quiet"><?= Cmd::icon('bricks.png') ?> 网站开发进度</h3>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组自定义标志</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 我的群组增加好友列表</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 完成群组搜索邀请</li>
            <li><?= Cmd::icon('bug_delete.png') ?> 群组主题回复无效</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 成员可退出群组</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组个人资料补充</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组短信、好友转发</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组个人资料开通</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组在线校友统计</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组互访记录</li>
        </ul>
    </div>