<div class="mgu10">     
        <ul class="mglf10">
            <h3 class="quiet"><?= Cmd::icon('bricks.png') ?> 网站改动</h3>
            <li><?= Cmd::icon('plugin_add.png') ?> 活动赞助企业展示系统</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组管理员开放编辑帖子权限</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 加入热心度系统</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 企业产品介绍加入富文本编辑器</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组话题可选择使用昵称</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组邀请增加“兴趣”、“职业”搜索</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 校友个人信息登录时同步群组个人数据</li>
            <li><?= Cmd::icon('bug_delete.png') ?> 修正群组邀请提示BUG</li>
        </ul>
    </div>