<!-- 需要做一些判断来显示当前的位置 -->
<div id="menu-box">
<a href="?m=admininfo" <?= $this->mtab == 'admininfo' ? 'class="here"':'' ?>>企业资料</a>
<a href="">招聘信息</a>
<a href="">留言管理</a>
<a href="">图片管理</a>
</div>
<div id="menu-box-sub">
<a href="?m=admininfo&s=index" <?= $this->stab == 'index' ? 'class="here"':'' ?>>企业介绍</a>
<a href="?m=admininfo&s=links" <?= $this->stab == 'links' ? 'class="here"':'' ?>>自定义链接</a>
<a href="">联系方式</a>
</div>