<div id="menu-box">
    <a href="/company/manage/company/" <?= 'company' == $this->action ? 'class="here"' : '' ?>>企业资料</a>
    <a href="/company/detail/index/cid/<?= $this->dataCompany['cid'] ;?>/" target="_blank">浏览我的企业</a>
</div>

<div id="menu-box-sub">
    <?php if('company' == $this->action): ?>
        <a href="/company/manage/company/type/basic/" <?= 'basic' == $this->type ? 'class="here"' : '' ?>>基础信息</a>
        <a href="/company/manage/company/type/contact/" <?= 'contact' == $this->type ? 'class="here"' : '' ?>>联系方式</a>
        <a href="/company/manage/company/type/biz/" <?= 'biz' == $this->type ? 'class="here"' : '' ?>>商务供求</a>
        <a href="/company/manage/company/type/logo/" <?= 'logo' == $this->type ? 'class="here"' : '' ?>>企业标志</a>
    <?php endif; ?>
</div>