<div id="menu-box">
	<a href="?m=mycompany" <?= $this->mtab == 'mycompany' ? 'class="here"':'' ?>>我的企业</a>
	<a href="?m=myfav" <?= $this->mtab == 'myfav' ? 'class="here"':'' ?>>我的收藏</a>
	<a href="?m=myword" <?= $this->mtab == 'myword' ? 'class="here"':'' ?>>我的留言</a>
</div>
<div id="menu-box-sub">
	<?php if($this->mtab == 'mycompany'): ?>
	<a href="?m=mycompany&s=index" <?= $this->stab == 'index' ? 'class="here"':'' ?>>申请新企业</a>
	<a href="?m=mycompany&s=wait" <?= $this->stab == 'wait' ? 'class="here"':'' ?>>待审核企业</a>
	<a href="?m=mycompany&s=done" <?= $this->stab == 'done' ? 'class="here"':'' ?>>已审核企业</a>
	<?php endif; ?>
</div>