<div class="span-5">
    <div class="sideBar">
        <?= $this->sortbar() ?>
    </div>
</div>

<div class="span-19 last">
    <div class="oneCol pdd10" style="overflow:hidden">
        <div class="extInline mg10 f14">
            <a href="/group/my/">我的群组</a> &gt; 
            <strong class="f14">我的好友</strong>
            共<span style="color:red"><?= count($this->friends) ?></span>人
        </div>
        
        <?php if(!$this->friends) : ?>
        <p class="mglf10">您还没有任何好友</p>
        <?php else: ?>
        <table>
        <?php foreach($this->friends as $k => $f): ?>
        <?php if($k%7 == 0) echo '<tr>'; ?>
                <td class="txtc pd10" style="line-height:220%" id="f_<?= $f ?>">
                    <a href="/group/member/profile?uid=<?= $f ?>"><?= Commons::getUserFace($f) ?></a><br />
                    <a href="/group/member/profile?uid=<?= $f ?>"><?= UserModel::fetch($f, 'realName') ?></a><br />
                    <a href="/group/pm/member?uid=<?= $f ?>"><?= Cmd::icon('email_go.png') ?></a>
                    <a href="javascript:remove(<?= $f ?>)"><?= Cmd::icon('cross.png') ?></a>
                </td>
        <?php if($k%7 == 6 || $k == (count($this->friends)-1)) echo '</tr>'; ?>
        <?php endforeach; ?>
        </table>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript">
    function remove(uid)
    {
        var c = confirm('确实要删除?');
        if(c == true)
        $.get('/group/member/removefriend?uid='+uid,null,function(html){
            if(html=='')
            $('#f_'+uid).fadeOut();
            else alert(html);
        });
    }
</script>