<div id="ajaxloading"></div>

<div id="help_position"><a href="/help/" title="首页">首页</a> > <?= $this->path; ?></div>
<div class="sidebar">
<div id="topic" <?php switch($this->question['status']) { case 0: ?>class="help_on"<?php break; case 1: ?>class="help_ok"<?php break; case 2: ?>class="help_on"<?php break; case 3: ?>class="help_on"<?php } ?>>
<h2>
<?php switch($this->question['status']) { case 0: ?>待解决的问题<?php break; case 1: ?>已解决的问题<?php break; case 2: ?>已关闭的问题<?php break; case 3: ?>已超时的问题<?php } ?>
</h2>
<p class="toolbar">
<a href="javascript:collection_insert(<?= $this->question['qid']; ?>);" class="collection" id="collection" title="收藏该问题">收藏</a>
<!--<a href="#" class="report">检举</a>-->
</p>
<table width="100%">
<tr><td><span class="coin"><?= $this->question['offer']; ?></span>&nbsp;&nbsp;<span class="tt"><?= $this->question['title']; ?></span></td></tr>
<tr><td class="info"><span>提问人：<?php echo (($this->question['anonym'] == 'N') ? $this->question['realName'] : '匿名'); ?>&nbsp;&nbsp;&nbsp;&nbsp;提问时间：<?= date('Y-m-d H:i', strtotime($this->question['addTime'])); ?></span></td></tr>
<tr><td class="info"><span>标&nbsp;&nbsp;&nbsp;签：<?= $this->question['tags']; ?></span>
</td>
</tr>
<tr>
<td class="txt">

<div class="content">
<?=  str_replace('\"', '"', $this->question['content']); ?><br />
<?php if ($this->question['append']) { ?>
<div class="memo">
<p>提问人的补充：</p>
<?= $this->question['append']; ?>
</div>
<?php } ?>
</div>
<?php if ($this->sessCommon->login['uid'] != $this->question['uid']) { ?>
<!--<input type="button" value="我来回答" class="topic_btn" />-->
<?php } if ($this->sessCommon->login['uid'] == $this->question['uid']) { ?>
<!--<input type="button" value="问题补充" class="topic_btn" />
<input type="button" value="无满意答案" class="topic_btn" />-->
<?php } ?>
</td>
</tr>
</table>
<?php $i=0; foreach($this->geneal as $value) { ?>
<input type="hidden" name="sort<?= $i; ?>" id="sort<?= $i; ?>" value="<?= $value['sid']; ?>">
<?php $i++; } ?>
</div>

<br />
<div <?php if ($this->sessCommon->login['uid'] != $this->question['uid'] || 0 < $this->total) { ?>id="reply"<?php } ?>>
<!-- 答案集合 -->
<?php if ($this->total > 0) { ?>
<h2>回答(共<?= $this->question['reply']; ?>条)</h2>
<?php foreach ($this->reply as $value) { ?>

<?php if (1 == $value['status']) { ?>
<!-- 答案 -->
<div class="accepted">
	<h3>满意答案</h3>
	<p class="info"><span><?php echo (($value['anonym'] == 'N') ? $value['realName'] : '匿名'); ?>&nbsp;&nbsp;&nbsp;&nbsp;回答时间：<?= date('Y-m-d H:i', strtotime($value['addTime'])); ?></span></p>
	<div class="content">
	<?=  str_replace('\"', '"', $value['content']); ?>
	</div>
</div>
<?php } else { ?>
<!-- 普通回答 -->
<div class="other">
	<p class="info"><span><?php echo (($value['anonym'] == 'N') ? $value['realName'] : '匿名'); ?>&nbsp;&nbsp;&nbsp;&nbsp;回答时间：<?= date('Y-m-d H:i', strtotime($value['addTime'])); ?></span></p>
	<p class="toolbar">
	<!--<a href="" class="report">检举</a>-->
	<?php if ($this->sessCommon->login['uid'] == $this->question['uid'] && 0 == $this->question['status']) { ?>
	<a class="accept" title="采纳为答案" href="javascript:question_accept(<?= $value['qid']; ?>, <?= $value['rid']; ?>, <?= $value['uid']; ?>);">采纳</a>
	<?php } ?>
	</p>	
	<div class="content">
	<?=  str_replace('\"', '"', $value['content']); ?>
	</div>
</div>
<?php } ?>

<?php } ?>
<?= $this->paging; ?>
<br />
<?php } ?>

<?php if ($this->sessCommon->login['uid'] != $this->question['uid'] && 0 == $this->question['status']) { ?>
<!-- 回答面板 -->
<h2>我来回答</h2><a name="reply" id="reply"></a>
<div id="reply_form">
<?php if ($this->sessCommon->login['uid'] != $this->question['uid']) { ?>
<form method="post" name="myform" id="myform" autocomplete="off">
<input tabindex="2" type="hidden" name="content" id="content" value="" /><?= $this->kindEditor('100%','120px'); ?>
匿名回答：<label for="anonym_y"><input id="anonym_y" tabindex="1" type="radio" name="anonym" value="Y" />是</label> <label for="anonym_n"><input id="anonym_n" tabindex="2" name="anonym" type="radio" value="N" checked="checked" />否</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;验证码：<input tabindex="3" type="text" name="vcode" id="vcode" class="verify" value="" maxlength="4" />&nbsp;<span id="putVerifyImg"></span><input tabindex="4" type="submit" class="reply_btn" name="btnReply" id="btnReply" value="提交回答" /><br />
<br />
<div id="ajaxhint" style="width:242px"></div>
<input type="hidden" name="isPutVerifyImg" id="isPutVerifyImg" value="show" />
<input type="hidden" name="qid" id="qid" value="<?= $this->question['qid']; ?>" />
</form>
</div>
<? } } ?>
</div>
</div>
<!-- 积分排行 -->
<div class="sidebar"><?= $this->render('dynamic/point.phtml'); ?></div>
