<div id="ajaxloading"></div>
<!-- 当前路径 -->
<div id="help_position"><a href="/help/" title="首页">首页</a> > <?= $this->path; ?></div>
<div class="sidebar">
<div id="topic" class="help_on">
<h2>
<?php switch($this->detail['status']) { case 0: ?>待解决的问题<?php break; case 1: ?>已解决的问题<?php break; case 2: ?>已关闭的问题<?php break; case 3: ?>已超时的问题<?php } ?>
</h2>
<p class="toolbar">
<a href="#" class="collection">收藏</a>
<!--<a href="#" class="report">检举</a>-->
</p>
<table width="100%">
<tr><td><span class="coin"><?=  $this->detail['offer']; ?></span>&nbsp;&nbsp;<span class="tt"><?=  $this->detail['title']; ?></span></td></tr>
<tr><td class="info"><span>提问人：<?php echo (($this->detail['anonym'] == 'N') ? $this->detail['realName'] : '匿名'); ?>&nbsp;&nbsp;&nbsp;&nbsp;提问时间：<?= date('Y-m-d H:i', strtotime($this->detail['addTime'])); ?></span></td></tr>
<tr><td class="info"><span>标&nbsp;&nbsp;&nbsp;签：<?= $this->detail['tags']; ?></span>
</td>
</tr>
<tr>
<td class="txt">

<div class="content">
<?=  str_replace('\"', '"', $this->detail['content']); ?><br />
<?php if ($this->detail['append']) { ?>
<div class="memo">
<p>提问人的补充：</p>
<?=  $this->detail['append']; ?>
</div>
<?php } ?>
</div>
<?php if ($this->sessCommon->login['uid'] != $this->detail['uid']) { ?>
<!--<input type="button" value="我来回答" class="topic_btn" />-->
<?php } if ($this->sessCommon->login['uid'] == $this->detail['uid']) { ?>
<!--<input type="button" value="问题补充" class="topic_btn" />
<input type="button" value="无满意答案" class="topic_btn" />-->
<?php } ?>
</td>
</tr>
</table>
<?php $i=0; foreach($this->geneal as $value) { ?>
<input type="hidden" name="sort<?= $i; ?>" id="sort<?= $i; ?>" value="<?= $value['sid']; ?>">
<?php $i++; } ?>
</div>

<!-- 答案集合 -->
<div <?php if ($this->sessCommon->login['uid'] != $this->detail['uid']) { ?>id="reply"<?php } ?>>
<?php if ($this->total > 0) { ?>
<h2>回答(共<?= $this->detail['reply']; ?>条)</h2>
<?php foreach ($this->reply as $value) { ?>
<div class="r1 content">
<?=  str_replace('\"', '"', $value['content']); ?>
<p class="info"><span><?php echo (($value['anonym'] == 'N') ? $value['realName'] : '匿名'); ?>&nbsp;&nbsp;&nbsp;&nbsp;回答时间：<?= date('Y-m-d H:i', strtotime($value['addTime'])); ?></span></p>
<p class="toolbar">
<!--<a href="" class="report">检举</a>-->
<?php if ($this->sessCommon->login['uid'] == $this->detail['uid']) { ?>
<a class="accept" title="采纳为答案" onclick="javascript:question_accept(<?= $value['qid']; ?>, <?= $value['rid']; ?>, <?= $value['uid']; ?>);">采纳</a>
<?php } ?>
</p>
</div>
<?php } ?>
<?= $this->paging; ?>
<br />
<?php } ?>

<!-- 回答面板 -->
<?php if ($this->sessCommon->login['uid'] != $this->detail['uid']) { ?>
<h2>我来回答</h2><a name="reply" id="reply"></a>
<?php } ?>
<div id="reply_form">
<?php if ($this->sessCommon->login['uid'] != $this->detail['uid']) { ?>
<form method="post" name="myform" id="myform" autocomplete="off">
<textarea name="content" id="content" ></textarea>
<br />匿名回答：
<input tabindex="1" type="radio" name="anonym" value="Y" />是 
<input tabindex="2" name="anonym" type="radio" value="N" checked="checked" />否
<br />
验&nbsp;证&nbsp;码：&nbsp;&nbsp;&nbsp;<input tabindex="3" type="text" name="vcode" id="vcode" class="verify" value="" maxlength="4" />&nbsp;<span id="putVerifyImg"></span><input type="submit" class="reply_btn" name="btnReply" id="btnReply" onClick="tinyMCE.triggerSave(false,false);" value="提交回答" /><br />
<br />
<div id="ajaxhint" style="width:250px"></div>
<input type="hidden" name="isPutVerifyImg" id="isPutVerifyImg" value="show" />
<input type="hidden" name="qid" id="qid" value="<?= $this->detail['qid']; ?>" />
</form>
<?php } ?>
</div>
</div>
</div>
<!-- 积分排行 -->
<div class="sidebar"><?= $this->render('dynamic/point.phtml'); ?></div>
