<div id="ajaxloading"></div>
<div id="help_position"><a href="/help/">校友互助</a> > <a href="/help/question/insert/">我要提问</a></div>

<div class="sidebar">
    <div id="topic" class="help_on">
        <h2>我要提问 </h2>

	    <div id="question_insert_form">
        <form method="post" name="myform" id="myform" autocomplete="off">
		    <table width="100%" border="0">
              <tr>
                <td>问题标题：</td>
                <td><input tabindex="1" type="text" name="title" id="title" class="help_input_kuang" value="<?= $this->title; ?>" maxlength="25" style="width:350px" /></td>
                <td>&nbsp;</td>
              </tr>
              <tr>
                <td>详细描述：<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /></td>
                <td><input tabindex="2" type="hidden" name="content" id="content" value="" /><?= $this->kindeditor('100%','200px'); ?>问题描述越详细，回答也会越准确！</td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td>问题标签：<br /><br /></td>
                <td><input  tabindex="3" type="text" name="tags" id="tags" class="help_input_kuang" value="" maxlength="30" style="width:350px" /><br>标签间请以<b>半角空格</b>间隔，每个标签2个字以上。</td>
                <td>&nbsp;</td>
              </tr>				  
              <tr>
                <td>问题分类：<br /><br /><br /><br /><br /><br /><br /><br /></td>
                <td>
                  <TABLE cellSpacing=0 cellPadding=0 border=0>
		              <TBODY>
		                  <TR>
		                      <TD><select tabindex="4" name="sort0" id="sort0"></select></TD>
		                      <TD width=10></TD>
		                      <TD><select tabindex="5" name="sort1" id="sort1"></select></TD>
		                      <TD width=10></TD>
		                      <TD><!--<select tabindex="6" name="sort2" id="sort2"></select>--></TD>
			              </TR>
		              </TBODY>
		          </TABLE>
				  将您的问题归入恰当的分类有助于获得更多的解答。			
		        </td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td>积分悬赏：</td>
                <td><input tabindex="7" type="text" name="offer" id="offer" class="help_input_kuang" value="" maxlength="3" style="width:60px" /> 我的可用分有<strong><?= $this->sessHelp->login['point']; ?></strong>分</td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td>是否匿名：</td>
                <td><label for="anonym_y"><input id="anonym_y" tabindex="8" type="radio" name="anonym" value="Y" />
                  是</label>
                    <label for="anonym_n"><input id="anonym_n" name="anonym" type="radio" value="N" checked="checked" />
                    否</label></td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td>验&nbsp;&nbsp;证&nbsp;码：</td>
                <td><input tabindex="9" type="text" name="vcode" id="vcode" class="verify" value="" maxlength="4" />&nbsp;<span id="putVerifyImg"></span></td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td></td>
                <td><input tabindex="10" type="submit" name="btnQuestion" id="btnQuestion" class="help_btn_medium" value="提交问题" /></td>
                <td></td>
              </tr>
              <tr>
                <td></td>
                <td><div id="ajaxhint" style="width:300px"></div></td>
                <td></td>
              </tr>			  
            </table>
            <input type="hidden" name="sortId" id="sortId" value="0">
		    <input type="hidden" name="isPutVerifyImg" id="isPutVerifyImg" value="show" />			
        </form>        
	    </div>
    </div>
</div>

<div class="sidebar">
    <table class="rightside_dot">
        <tr>
            <th class="txtl" colspan="2">类似的问题</th>
        </tr>
        <tr>
            <td><strong>·</strong><a href="/help/question/display/id/1/" target="_blank" class="dot"></a></td>
            <td></td>
        </tr>
    </table>
</div>
