<div id="ajaxloading"></div>
<!-- 当前位置 -->
<div id="help_position"><a href="/help/">校友互助</a> > <a href="/help/question/insert/">我要提问</a></div>

<!-- 我要提问 -->
<div class="sidebar">
    <div id="topic" class="help_on">
        <h2>我要提问 </h2>
        <!-- 提问表单 -->
	    <div id="question_insert_form">
        <form method="post" name="myform" id="myform" autocomplete="off">
		    <table width="100%" border="0">
              <tr>
                <td>问题标题：</td>
                <td><input tabindex="1" type="text" name="title" id="title" class="help_input_kuang" value="<?= $this->title; ?>" maxlength="25" style="width:350px" /></td>
                <td>&nbsp;</td>
              </tr>
              <tr>
                <td>详细描述：</td>
                <td id="tinymce_textarea"><textarea tabindex="2" name="content" id="content" class="question_insert_textarea"></textarea>问题描述越详细，回答也会越准确！</td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td>问题标签：</td>
                <td><input  tabindex="3" type="text" name="tags" id="tags" class="help_input_kuang" value="" maxlength="30" style="width:350px" /><br>每个标签2个字以上，标签间请以半角空格间隔。</td>
                <td>&nbsp;</td>
              </tr>				  
              <tr>
                <td>问题分类：</td>
                <td>
                  <TABLE cellSpacing=0 cellPadding=0 border=0>
		              <TBODY>
		                  <TR>
		                      <TD><select tabindex="4" name="sort0" id="sort0"></select></TD>
		                      <TD width=10></TD>
		                      <TD><select tabindex="5" name="sort1" id="sort1"></select></TD>
		                      <TD width=10></TD>
		                      <TD><select tabindex="6" name="sort2" id="sort2"></select></TD>
			              </TR>
		              </TBODY>
		          </TABLE>			
		        </td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td>积分悬赏：</td>
                <td><input tabindex="7" type="text" name="offer" id="offer" class="help_input_kuang" value="" maxlength="3" style="width:60px" /> 我的可用分有<strong><?= $this->sessHelp->login['point']; ?></strong>分</td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td>是否匿名：</td>
                <td><input tabindex="8" type="radio" name="anonym" value="Y" />
                  是
                    <input tabindex="9" name="anonym" type="radio" value="N" checked="checked" />
                    否</td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td>验证码：</td>
                <td><input tabindex="10" type="text" name="vcode" id="vcode" class="verify" value="" maxlength="4" />&nbsp;<span id="putVerifyImg"></span></td>
                <td>&nbsp;</td>
              </tr>			  
              <tr>
                <td></td>
                <td><input tabindex="11" type="submit" name="btnSubmit" id="btnSubmit" class="help_btn_medium" onClick="tinyMCE.triggerSave(false,false);" value="提交问题" /></td>
                <td></td>
              </tr>
              <tr>
                <td></td>
                <td><div id="ajaxhint" style="width:300px"></div></td>
                <td></td>
              </tr>			  
            </table>
            <INPUT type="hidden" name="sortId" id="sortId" value="0">
		    <input type="hidden" name="isPutVerifyImg" id="isPutVerifyImg" value="show" />			
        </form>        
	    </div>
    </div>
</div>

<!-- 类似问题 -->
<div class="sidebar">
    <table class="rightside_dot">
        <tr>
            <th class="txtl" colspan="2">类似的问题</th>
        </tr>
        <tr>
            <td><strong>·</strong><a href="/help/question/display/id/1/" target="_blank" class="dot">title</a></td>
            <td></td>
        </tr>
    </table>
</div>
