<!-- 班级切换 /////////////////////////////////////////// -->
<p class="class_tab">
<b style="color:#666;">我的班级</b> &raquo;
<?php 
if(count(Zend_Registry::get('sessClass')->data) >0):
foreach (Zend_Registry::get('sessClass')->data as $k => $v): ?>
<a href="/class/home?c=<?=$k?>"><?=$v['class_name']?></a> | 
<?php endforeach; endif; ?>
<a href="/class/new/">创建新班级</a>
</p>
<script>$('.class_tab a[href="/class/home?c=<?= $this->class_base_info['class_id'] ?>"]').addClass('on')</script>

