<?php $class_id = $this->class_base_info['class_id']; ?>

<div class="sidebar" style="width:160px">
<!-- 管理条目 ///////////////////////////////////// -->
<p class="toolbar">
<a href="/class/invite?c=<?= $class_id ?>"><img src="/static/images/icon/user.gif" /> 邀请加入</a>
<a href="/class/topic/list?c=<?= $class_id ?>"><img src="/static/images/icon/comments.gif" /> 班级话题</a>
<a href="/class/album/list?c=<?= $class_id ?>"><img src="/static/images/icon/picture.gif" /> 班级相册</a>
<!--<a href="#"><img src="/static/images/icon/sport_tennis.gif" /> 班级活动</a>-->
<a href="#"><img src="/static/images/icon/email.gif" /> 群发邮件</a>
<a href="/class/addressbook?c=<?= $class_id ?>"><img src="/static/images/icon/book.gif" /> 班级通讯录</a>
<a href="#"><img src="/static/images/icon/lock.gif" /> 隐私控制</a>
<a href="/class/manage/member?c=<?= $class_id ?>"><img src="/static/images/icon/group.gif" /> 成员管理 
<?= ApplyModel::fetchNum($class_id) > 0 ? '<img src="/static/images/icon/new.gif" />' : '' ?></a>
</p>
</div>

<!-- 信息显示区 //////////////////////////////////////  -->
<div class="sidebar class_show" style="width:500px; margin:0 10px">

<?php if($this->class_base_info['class_member_num'] <= 5): // 小于5人的班级允许修改名称?>
<script type="text/javascript">
	$('.class_tab a:contains("<?= $this->class_base_info['class_name'] ?>")').replaceWith('<input id="targetClass" onblur="this.value=\'<?= $this->class_base_info['class_name'] ?>\'" onkeydown="if(event.keyCode==13)changeClassname(<?= $class_id ?>)" onclick="this.value=\'修改班级名\';this.select()" class="inputtxt" type="text" value="<?= $this->class_base_info['class_name'] ?>" />');
</script>
<?php endif; ?>


<h2 class="quiet clearfloat"><img src="/static/images/icon/layers.gif" /> 班级黑板报</h2>
<div id="class_notice" style="cursor:pointer" onmouseover="this.style.borderStyle='dashed'" onmouseout="this.style.borderStyle='solid'" onclick="modClassNotice(<?= $class_id ?>,0)">
<?= stripcslashes($this->class_base_info['class_notice']) == '' ? '点我开始编辑黑板报' : stripcslashes($this->class_base_info['class_notice']); ?>
</div>


<h2 class="quiet clearfloat"><img src="/static/images/icon/picture.gif" /> 最新照片</h2>
<div id="class_picture">
	<?php if($this->albums): foreach($this->albums as $album): ?>
	<a title="发布人:<?= $album['realName'].' | 描述:'.$album['class_album_description'] ?>" href="/static/classes/<?= $class_id ?>/album/<?= $album['class_album_filename'] ?>" class="thickbox">
		<img src="/static/classes/<?= $class_id ?>/album/<?= $album['class_album_filename'] ?>" height="80" />
	</a>
	<?php endforeach; else: ?>
	无
	<?php endif; ?>
</div>

<!-- 班级对应身份所开放的最新话题列 -->
<h2 class="clearfloat"><img src="/static/images/icon/comments.gif" /> <a href="/class/topic/list?c=<?= $class_id ?>">最新话题</a></h2>
	<div id="class_topic">
		<?php 
		if(count($this->topics) > 0)
		foreach ($this->topics as $key => $val)
		{
			echo '<li>['.date('m-d H:i',$val['class_topic_pub_time']).'] <a href="/class/topic/view?c='.$class_id.'&tid='.$val['class_topic_id'].'">'.stripslashes($val['class_topic_title']).'</a></li>';
		}
		?>
	</div>
	
</div>