<div class="sidebar" style="width:160px">
<!-- 管理条目 ///////////////////////////////////// -->
<p class="toolbar">
<a href="/member/my/address/"><img src="/static/images/icon/user.gif" /> 邀请加入</a>
<a href="/class/topic/list?c=<?= $this->class_base_info['class_id'] ?>"><img src="/static/images/icon/comments.gif" /> 班级话题</a>
<a href="#"><img src="/static/images/icon/email.gif" /> 群发邮件</a>
<a href="/class/addressbook?c=<?= $this->class_base_info['class_id'] ?>"><img src="/static/images/icon/book.gif" /> 班级通讯录</a>
<a href="#"><img src="/static/images/icon/lock.gif" /> 隐私控制</a>
<a href="/class/manage/member?c=<?= $this->class_base_info['class_id'] ?>"><img src="/static/images/icon/group.gif" /> 成员管理 
<?= DbModel::getClassJoinApplyNum($this->class_base_info['class_id']) > 0 ? '<img src="/static/images/icon/new.gif" />' : '' ?></a>
</p>
</div>

<!-- 信息显示区 //////////////////////////////////////  -->
<div class="sidebar class_show" style="width:500px; margin:0 10px">
<h2 class="quiet"><img src="/static/images/icon/layers.gif" /> 班级黑板报</h2>
<div id="class_notice" style="cursor:pointer" onmouseover="this.style.borderStyle='dashed'" onmouseout="this.style.borderStyle='solid'" onclick="modClassNotice(<?= $this->class_base_info['class_id'] ?>,0)">
<?= stripcslashes($this->class_base_info['class_notice']) == '' ? '点我开始编辑黑板报' : stripcslashes($this->class_base_info['class_notice']); ?>
</div>


<h2 class="quiet"><img src="/static/images/icon/picture.gif" /> 班级相册</h2>
<div id="class_picture">尚未开放..</div>

<!-- 班级话题 /////////////////////////////// -->


<!-- 班级活动 /////////////////////////////// -->
<div id="class_activity" class="hide">
</div>
</div>