<div class="sidebar" style="width:160px">
<!-- 管理条目 ///////////////////////////////////// -->
<p class="toolbar">
<a href="javascript:classJoin(<?= $this->class_base_info['class_id'] ?>)"><img src="/static/images/icon/table.gif" /> 申请加入</a>
</p>
</div>

<!-- 信息显示区 //////////////////////////////////////  -->
<div class="sidebar class_show" style="width:500px; margin:0 10px">
<h2 class="quiet"><img src="/static/images/icon/layers.gif" /> 班级黑板报</h2>
<div id="class_notice">
<?= stripcslashes($this->class_base_info['class_notice']) == '' ? '这个管理员很懒,黑板报都没出..' : stripcslashes($this->class_base_info['class_notice']); ?>
</div>


<h2 class="quiet"><img src="/static/images/icon/picture.gif" /> 班级相册</h2>
<div id="class_picture">尚未开放..</div>

<h2 class="quiet"><img src="/static/images/icon/comments.gif" /> 班级讨论</h2>
<div id="class_comments"></div>
</div>