<div class="sidebar" style="width:160px">
<!-- 管理条目 ///////////////////////////////////// -->
<p class="toolbar">
<a href="javascript:classJoin(<?= $this->class_base_info['class_id'] ?>)"><img src="/static/images/icon/table.gif" /> 申请加入</a>
</p>
</div>

<!-- 信息显示区 //////////////////////////////////////  -->
<div class="sidebar class_show" style="width:500px; margin:0 10px">
<h2 class="quiet clearfloat"><img src="/static/images/icon/layers.gif" /> 班级黑板报</h2>
<div id="class_notice">
<?= stripcslashes($this->class_base_info['class_notice']) == '' ? '这个管理员很懒,黑板报都没出..' : stripcslashes($this->class_base_info['class_notice']); ?>
</div>


<h2 class="quiet clearfloat"><img src="/static/images/icon/picture.gif" /> 最新照片</h2>
<div id="class_picture">
	<?php if($this->albums): foreach($this->albums as $album): ?>
	<a title="发布人:<?= $album['realName'].' | 描述:'.$album['class_album_description'] ?>" href="/static/classes/<?= $class_id ?>/album/<?= $album['class_album_filename'] ?>" class="thickbox">
		<img src="/static/classes/<?= $class_id ?>/album/<?= $album['class_album_filename'] ?>" height="80" />
	</a>
	<?php endforeach; else: ?>
	无
	<?php endif; ?>
</div>

<!-- 班级对应身份所开放的最新话题列 -->
<h2 class="clearfloat"><img src="/static/images/icon/comments.gif" /> 最新开放话题</h2>
	<div id="class_topic">
		<?php 
		if(count($this->topics) > 0)
		foreach ($this->topics as $key => $val)
		{
			echo '<li>['.date('m-d H:i',$val['class_topic_pub_time']).'] <a href="/class/topic/view?c='.$this->class_base_info['class_id'].'&tid='.$val['class_topic_id'].'">'.stripslashes($val['class_topic_title']).'</a></li>';
		}
		?>
	</div>
</div>