<script type="text/javascript" src="/static/scripts/thickbox-compressed.js"></script>
<link rel="stylesheet" type="text/css" href="/static/styles/thickbox.css" media="screen" />
<style>
    .p-list th{
        background:#eee; padding:5px; border-bottom:1px solid #ccc;
    }
    .p-list td{
        padding:3px;
        border-bottom:1px dashed #eee;
    }
</style>
<div class="corner-box floatLeft">
    <b class="corner-box-title">产品管理</b>
    <ul style="padding-bottom:10px;">
        <li>修改产品图片介绍</li>
    </ul>
</div>
        
<div class="floatLeft" style="padding-bottom:30px;">
  <h2>产品展示</h2>
    <table class="p-list" width="720" cellpadding="0" cellspacing="0">
        <tr>
            <th>分类</th>
            <th>名称</th>
            <th>介绍</th>
            <th></th>
        </tr>
            <?php if(count($this->prods) == 0): ?>
            <tr>
            <td colspan="4">没有产品可管理</td>
            </tr>
            <?php else: foreach($this->prods as $p): ?>
            <tr id="p_<?= $p['pid'] ?>">
            <td><?= $p['sort'] ?></td>
            <td>
                <?= $p['name'] ?>
                <a class="thickbox" href="/static/bizs/<?= $this->cid.'/'.$p['img'] ?>"><img src="/static/images/group/icons/picture.png" /></a>
            </td>
            <td class="f12">
                <?= stripslashes($p['intro']) ?>
                <input type="hidden" name="pid" value="<?= $p['pid'] ?>" />
                <input type="hidden" name="img" value="<?= $p['img'] ?>" />
            </td>
            <td>
                <button onclick="mod(<?= $p['pid'] ?>)">修改</button>
                <button onclick="del(<?= $p['pid'] ?>)">删除</button>
            </td>
            </tr>
            <?php endforeach; endif; ?>
    </table>
    <div class="pagination"><?= $this->pagination ?></div>
</div>
<script>
    function mod(pid)
    {
        $.get('/biz/manage/domodify?pid='+pid,function(data){
            $.facebox(data);
        });
    }
    
    function del(pid)
    {
        var c = confirm('确定删除?');
        if(c == true)
        {
            $.post('/biz/manage/dodelete', $('#p_'+pid).fastSerialize(), function(html){
            if(html == 'success')
                $('#p_'+pid).children().fadeOut('slow');
            });
        }
    }
</script>