<div class="corner-box floatLeft">
    <b class="corner-box-title">企业资料</b>
	<ul style="padding-bottom:10px;">
	  <li>正在完善基础信息</li>	  
	</ul>
</div>

<div class="floatLeft" style="padding-bottom:30px;">
  <h2>修改企业基础信息</h2>
  <form name="frmBasic" id="frmBasic" autocomplete="off">
    <table class="table" style="margin:0 0 0 20px;" width="650px" cellpadding="0" cellspacing="0">
	  <tr>
		<td width="80" class="txtr">企业名称：</td>
		<td><?= $this->dataCompany['name'] ;?></td>
	  </tr>
	  <tr>
		<td class="txtr">创&nbsp;办&nbsp;&nbsp;人：</td>
		<td><?= $this->sessCommon->login['realName']; ?></td>
	  </tr>
	  <tr>
		<td class="txtr">所处行业：</td>
		<td><select name="industry" id="industry" tabindex="1"><option>--请选择--</option><?php foreach ($this->industry() as $key => $value) { ?><option <?= ($key == $this->dataCompany['industry'] ? 'selected' : ''); ?> value="<?= $key; ?>"><?= $value; ?></option><?php } ?></select></td>
	  </tr>
	  <tr>
		<td class="txtr">企业性质：</td>
		<td><select name="property" id="property" tabindex="2"><option>--请选择--</option><?php foreach ($this->property() as $key => $value) { ?><option <?= ($key == $this->dataCompany['property'] ? 'selected' : ''); ?> value="<?= $key; ?>"><?= $value; ?></option><?php } ?></select></td>
	  </tr>
      <?= $this->pcas(); ?>
	  <tr>
		<td class="txtr">所在城市：</td>
		<td><select tabindex="3" name="province" id="province"></select>&nbsp;<select tabindex="4" name="city" id="city"></select><br /></td>
	  </tr>
	  <tr>
		<td class="txtr">企业简介：<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /></td>
		<td><textarea name="content" cols="70" rows="15" id="content"><?= $this->dataCompany['intro'] ;?></textarea>
		<p><span class="quiet f12">请详细介绍贵企业的发展历史、基本概况、行业优势等，50-1000字。</span></p></td>
	  </tr>	  
	  <tr>
		<td>&nbsp;</td>
		<td><input type="submit" id="btnBasic" tabindex="5" value=" 提 交 修 改 " class="buttonGreen" /></td>
	  </tr>
	  <tr>
		<td>&nbsp;</td>
		<td><div id="ajaxhint" style="width:300px"></div></td>
	  </tr>
	</table>
  </form>
</div>

<script language="javascript" type="text/javascript">new PCAS("province","city","<?= $this->dataCompany['province']; ?>","<?= $this->dataCompany['city']; ?>");</script>