    <div class="side-box floatLeft">
	    <div class="side-box-title">企业推荐</div>
        <ul>
		    <?php foreach ($this->recmd as $key => $value) { ?>
            <li><a href="/biz/detail/index/cid/<?= $value['cid']; ?>/" target="_blank"><?= $this->Companyface($value['cid']); ?><br /><?= $value['name']; ?></a></li>
			<?php } ?>
        </ul>
    </div>
	<div class="side-box floatRight">	
	    <div class="side-box-title">行业分类</div>
        <ul>
            <?php foreach ($this->industry as $key => $value) { ?>
            <li><a href="/biz/index/industry/iid/<?= $key; ?>/"><?= $this->industry($key); ?> (<?= ($this->industry[$key] ? $this->industry[$key] : 0); ?>)</a></li>
            <?php } ?>
        </ul>
    </div>

    <div class="mid-box">
	    <div class="mid-box-intro">这里为校友创办的企业提供一个形象展示、产品/服务推广、英才猎聘的平台。无论企业规模大小和员工多寡，它都寄托了校友自主创业的一番雄心壮志。相信，只要每天都在朝着目标而努力，世界终有一天会被你改变！<input type="button" class="buttonGreen" value="申请展示我的企业" onclick="window.location.href='/biz/my/company/type/join/'" /></div>
        <h2 class="mid-box-title"><!--企业信息 <input type="text" value="" /><input type="button" class="button" value="企业搜索" />--></h2>
        <table class="table" cellpadding="0" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th class="table-top-left" width="100%">新加入的企业(已收录<?= $this->companies; ?>家校友企业)</th>
            </tr>
            </thead>
            <tfoot>
                <tr>
                    <td></td>
                </tr>
            </tfoot>
            <tbody>            
            <?php foreach ($this->list as $key => $value) { ?>
            <tr>
                <td class="left" style="border-right:1px solid #D7D7D7"><a href="/biz/detail/index/cid/<?= $value['cid']; ?>/" target="_blank" class="f15"><strong><?= $value['name']; ?></strong></a><p style="padding-top:8px"><span class="quiet f13">行业：<?= $this->industry($value['industry']); ?>&nbsp;&nbsp;性质：<?= $this->property($value['property']); ?>&nbsp;&nbsp;地区：<?= $value['province']; ?>&nbsp;<?= $value['city']; ?></span></p><p style="padding-top:5px"><?= Commons::utfSubStr(strip_tags($value['intro']), 250); ?>...</p><hr /></td>
            </tr>
            <?php } ?>
            </tbody>
		</table>

        <table class="table" cellpadding="0" cellspacing="0">
            <tr>
                <td><?= $this->paging; ?></td>				
            </tr>
		</table>
        <!--<div class="corner-box floatLeft" style="width:252px; margin-right:10px;">
		    <h2 class="corner-box-title"><img src="/static/images/biz/sub-4.gif" class="floatLeft pdr10" /> 菜鸟创业指南</h2>
		    <ul style=" padding-left:20px;"><li><a href=""></a></li></ul>
        </div>
        <div class="corner-box floatLeft" style="width:252px;">
		    <h2 class="corner-box-title"><img src="/static/images/biz/sub-5.gif" class="floatLeft pdr10" /> 创业互助</h2>
            <ul style=" padding-left:20px;"><li><a href=""></a></li></ul>
		</div>
        <div class="corner-box floatLeft" style="width:252px; margin-right:10px;">
            <h2 class="corner-box-title"><img src="/static/images/biz/sub-7.gif" class="floatLeft pdr10" /> 创业知识库</h2>
			<ul style=" padding-left:20px;"><li><a href=""></a></li></ul>
	    </div>
		<div class="corner-box floatLeft" style="width:252px;">
		    <h2 class="corner-box-title"><img src="/static/images/biz/sub-8.gif" class="floatLeft pdr10" /> 创业知识库</h2>
			<ul style=" padding-left:20px;"><li><a href=""></a></li></ul>
		</div>-->
    </div>