    <div class="side-box floatRight">
        <div class="side-box-title">行业企业推荐</div>
        <ul>
            <?php foreach ($this->recmd as $key => $value) { ?>
            <li><a href="/biz/detail/index/cid/<?= $value['cid']; ?>/" target="_blank"><?= $this->Companyface($value['cid']); ?><br /><?= $value['name']; ?></a></li>
	        <?php } ?>
        </ul>
    </div>

    <div class="mid-box-with-left">
        <div class="mid-box-intro">
		    您的位置：<a href="/biz/">校友企业</a> » <strong><?= $this->iname; ?></strong> » <hr />
            <!--<input type="text" value="" /><input type="button" class="button" value="企业搜索" /> <input type="button" class="buttonGreen" value="申请加入" /><hr />-->
			<table class="table" width="100%" cellpadding="0" cellspacing="0">
                <tbody>
                <?php foreach ($this->industry as $key => $value) { $i++; if (1 == $i % 3) { echo '<tr>'; } ?>
                    <td width="33%"><?php if ($this->iid != $key) { ?><a href="/biz/index/industry/iid/<?= $key; ?>/"><?php } ?><?= $this->industry($key); ?> (<?= ($this->industry[$key] ? $this->industry[$key] : 0); ?>)<?php if ($this->iid == $key) { ?></a></td><?php } ?>
                <?php if (0 == $i % 3) { echo '</tr>'; } } ?>
                </tbody>
          </table>
        </div>

		<table class="table" cellpadding="0" cellspacing="0" width="100%" style="margin-top:10px;">
		    <thead>
            <tr>
                <th width="100%" class="table-top-left">行业内新加入的企业</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td></td>
            </tr>
            </tfoot>
            <tbody>
			<?php foreach ($this->list as $key => $value) { ?>
            <tr>
                <td class="left" style="border-right:1px solid #D7D7D7"><a href="/biz/detail/index/cid/<?= $value['cid']; ?>/" target="_blank" class="f15"><strong><?= $value['name']; ?></strong></a><p style="padding-top:8px"><span class="quiet f13">行业：<?= $this->industry($value['industry']); ?>&nbsp;&nbsp;性质：<?= $this->property($value['property']); ?>&nbsp;&nbsp;地区：<?= $value['province']; ?>&nbsp;<?= $value['city']; ?></span></p><p style="padding-top:5px"><?= Commons::utfSubStr(strip_tags($value['intro']), 250); ?>...</p><hr /></td>
            </tr>
			<?php } ?>
            </tbody>
        </table>
    </div>