    <div class="side-box floatRight">
      <div class="side-box-title">XX行业推荐企业</div>
      <ul>
        <li><a href=""><img src="images/upload/user/1/corporation/01.jpg" /><br />
          什么企业的名字</a></li>
        <li><img src="images/upload/user/1/corporation/02.jpg" /></li>
        <li><a href="">什么企业的名字</a></li>
        <li><img src="images/upload/user/1/corporation/03.jpg" /></li>
        <li><a href="">什么企业的名字</a></li>
        <li><a href=""><img src="images/upload/user/1/corporation/01.jpg" /><br />
          什么企业的名字</a></li>
        <li><img src="images/upload/user/1/corporation/02.jpg" /></li>
        <li><a href="">什么企业的名字</a></li>
        <li><img src="images/upload/user/1/corporation/03.jpg" /></li>
        <li><a href="">什么企业的名字</a></li>
      </ul>
    </div>
    <div class="mid-box-with-left">
      <h2 class="mid-box-title">查找企业
        <input type="text" value="网络科技" />
        <input type="button" class="button" value="搜索" />
      </h2>
      <div class="pagination"><b>1</b><a href="/class/?year=&amp;college=&amp;p=2">2</a><a href="/class/?year=&amp;college=&amp;p=3">3</a><a href="/class/?year=&amp;college=&amp;p=4">4</a><a href="/class/?year=&amp;college=&amp;p=5">5</a><a href="/class/?year=&amp;college=&amp;p=2">下页</a><a href="/class/?year=&amp;college=&amp;p=5">最后页</a></div>
      <table class="table" cellpadding="0" cellspacing="0" width="100%" style="margin-top:10px;">
        <thead>
          <tr>
            <th colspan="3" class="table-top-left" width="60%">找到与“关键字”相关的xx家企业：</th>
            <th>经营模式&amp;产品</th>
            <th class="table-top-right"></th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <td class="table-bottom-left"></td>
            <td colspan="3"></td>
            <td class="table-bottom-right"></td>
          </tr>
        </tfoot>
        <tbody>
          <tr>
            <td class="left lh150" colspan="3"><a href=""><img src="images/upload/user/1/corporation/01.jpg" class="floatLeft pd10" /></a> <a href=""><b>杭州友笑网络科技有限公司</b></a><br />
              杭州友笑网络科技有限公司是一家致力于校友社交的.. </td>
            <td class="left lh150"> 模式: 自主开发<br />
              产品: zjuhz.com </td>
            <td class="right">留言咨询</td>
          </tr>
          <tr class="even">
            <td class="left lh150" colspan="3"><img src="images/upload/user/1/corporation/01.jpg" class="floatLeft pd10" /> <b>杭州友笑网络科技有限公司</b><br />
              杭州友笑网络科技有限公司是一家致力于校友社交的.. </td>
            <td class="left lh150"> 模式: 自主开发<br />
              产品: zjuhz.com </td>
            <td class="right">留言咨询</td>
          </tr>
          <tr>
            <td class="left lh150" colspan="3"><img src="images/upload/user/1/corporation/01.jpg" class="floatLeft pd10" /> <b>杭州友笑网络科技有限公司</b><br />
              杭州友笑网络科技有限公司是一家致力于校友社交的.. </td>
            <td class="left lh150"> 模式: 自主开发<br />
              产品: zjuhz.com </td>
            <td class="right">留言咨询</td>
          </tr>
          <tr class="even">
            <td class="left lh150" colspan="3"><img src="images/upload/user/1/corporation/01.jpg" class="floatLeft pd10" /> <b>杭州友笑网络科技有限公司</b><br />
              杭州友笑网络科技有限公司是一家致力于校友社交的.. </td>
            <td class="left lh150"> 模式: 自主开发<br />
              产品: zjuhz.com </td>
            <td class="right">留言咨询</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="pagination"><b>1</b><a href="/class/?year=&amp;college=&amp;p=2">2</a><a href="/class/?year=&amp;college=&amp;p=3">3</a><a href="/class/?year=&amp;college=&amp;p=4">4</a><a href="/class/?year=&amp;college=&amp;p=5">5</a><a href="/class/?year=&amp;college=&amp;p=2">下页</a><a href="/class/?year=&amp;college=&amp;p=5">最后页</a></div>