<?= $this->render('home/index.phtml'); ?>
<!-- 管理条目 ///////////////////////////////////// -->
<div class="sidebar" style="width:160px">
<p class="toolbar">
<a href="/class/home?c=<?= $this->class_id ?>"><img src="/static/images/icon/arrow_undo.gif" /> 返回</a>
<a href="/class/album/public?c=<?= $this->class_id ?>"><img src="/static/images/icon/add.gif" /> 发布新照片</a>
</p>
</div>

<!-- 班级话题详细列表 ///////////////////////// -->
<div class="sidebar cont_list">
<table id="class_topics" width="100%">
<tr>
<th colspan="4" class="txtl quiet">
<img src="/static/images/icon/picture.gif" /> <b>班级相册</b>
<select onchange="">
	<option value="">全部照片</option>
	<option value="未分类">未分类</option>
</select>
<th class="txtr"><a href="/class/album/public?c=<?= $this->class_id ?>" style="background:url(/static/images/icon/add.gif) no-repeat left center; padding-left:18px;">新照片</a></th>
</tr>
<tr class="quiet">
	<td width="50%">主题</td>
	<td>作者</td>
	<td class="txtc">回复</td>
	<td class="txtc">阅读</td>
	<td class="txtc">最后回复</td>
</tr>

</table>
</div>