<div class="oneCol span-24 last">
    <table width="100%">
            <tr>
                <td class="pd10" width="5%"><?= Cmd::groupIcon($this->gid) ?></td>
                <td class="vm f14 txtl hrefspan-8">
                    <a href="/group/home?gid=<?= $this->gid ?>">
                        <strong><?= $this->groupInfo['name'] ?></strong>
                    </a>
                    <a href="/group/home/name/of/<?= $this->groupInfo['url'] ?>">
                        http://www.zjuhz.com/group/home/name/of/<?= $this->groupInfo['url'] ?>
                    </a>
                    <p class="f12">
                        <?= stripcslashes($this->escape($this->groupInfo['intro'])) ?>
                    </p>
                </td>
            </tr>
    </table>
</div>