<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="imagetoolbar" content="no" />
<title><?php echo $this->header_title ?> - 浙江大学校友会 - zjuhz.com</title>
<script type="text/javascript" src="/static/scripts/jquery.js"></script>
<script type="text/javascript" src="/static/scripts/temp.js"></script>
<link rel="stylesheet" type="text/css" href="/static/styles/temp.css" media="screen" />
</head>

<body>
	<div id="wrap">
	
		<div id="header">
			<a href="/" id="logo">
				<b>zjuhz.com</b>
				<p>杭州浙江大学校友会</p>
			</a>
			
			<?= $this->render('global-nav.phtml') ?>
			<form id="help_search">
			<input type="text" size="40" class="help_key" />
			<input type="button" value="搜索" class="help_btn" />
			<input type="button" value="求助" class="help_btn" />
			</form>
			
		</div>
		
		<div id="main">
		
		</div>