<?php 

// 分配title
$this->headTitle($this->escape($this->entity['entity_title']));
// 分配 meta 关键字
$this->headMeta()->appendName('keywords', $this->escape($this->entity['entity_tag']));
?>

<div id="global_pos">
<img src="/static/images/icon/newspaper.gif" />
<a href="/info/">信息资讯</a> / 
<a href="/info/?category=<?= $this->escape($this->entity['category_id']) ?>"><?= $this->escape($this->entity['category_name']) ?></a> / 
<?= $this->escape($this->entity['entity_title']) ?> 
</div>

<div class="sidebar">

<!-- 标题 ////////////////////////////////////////////// -->
<?php if(!$this->entity): ?>
<h2 class="entity_none">您所请求的信息不存在!</h2>
<?php else: ?>
<h2 class="print entity_title">
<?= $this->escape($this->entity['entity_title']) ?>
</h2>


<!-- 主体 ////////////////////////////////////////////// -->
<div class="print entity">
<?= stripslashes($this->entity['entity_content']) ?>
</div>

<!-- 同类上下篇 ////////////////////////////////////////////// -->
<table width="100%">
<tr>
<?php if($this->sibling['previous']): ?>
<td class="sibling_previous"><img src="/static/images/icon/previous.gif" /> 
<a href="/info/view/detail/id/<?= $this->escape($this->sibling['previous']['entity_id']) ?>">
<?= $this->escape($this->sibling['previous']['entity_title']) ?></a>
</td>
<?php endif; ?>

<?php if($this->sibling['next']): ?>
<td class="sibling_next">
<a href="/info/view/detail/id/<?= $this->escape($this->sibling['next']['entity_id']) ?>">
<?= $this->escape($this->sibling['next']['entity_title']) ?></a> 
<img src="/static/images/icon/next.gif" /> 
</td>
<?php endif; ?>
</tr>
</table>

<!-- 工具栏 ////////////////////////////////////////////// -->
<p class="toolbar">
已被阅读(<?= $this->entity['entity_view_num'] ?>)&nbsp;&nbsp;&nbsp;
<?php if($this->tag): ?>本文标签: 
<?php foreach ($this->tag as $k => $v): ?>
<a href="/info/search/key/<?= urlencode($this->escape($v)) ?>"><?= $this->escape($v) ?></a>
<?php endforeach; endif; ?>&nbsp;&nbsp;&nbsp;
<a href="/info/comment/">发表评论(23)</a>&nbsp;&nbsp;&nbsp;
<img src="/static/images/icon/top.gif" style="cursor:pointer" onclick="javascript:scroll(0,0)" align="absmiddle" />&nbsp;&nbsp;&nbsp;
<img style="cursor: pointer;" src="/static/images/icon/printer.gif" alt="打印" onclick="window.print()" align="absmiddle">
</p>


<!-- 相关文章 ////////////////////////////////////////////// -->
<table class="similarity">
<tr><th colspan="2">:: 相关文章 ::</th></tr>
<?php if(!$this->similarity): ?>
<tr><td colspan="2">没有找到</td></tr>
<?php else: foreach ($this->similarity as $k2 => $v2): ?>
<tr>
<td><a href="/info/view/detail/id/<?= $v2['entity_id'] ?>"><?= $this->escape($v2['entity_title']) ?></a></td>
<td><?= Commons::date($v2['entity_pub_time']) ?></td>
</tr>
<?php endforeach; endif; ?>
</table>

<?php endif; ?>
</div>
