<?php 

// 分配title
$this->headTitle($this->escape($this->entity['entity_title']));
// 分配 meta 关键字
$this->headMeta()->appendName('keywords', $this->escape($this->entity['entity_tag']));
?>
<div class="extInline" style="margin:0;">
	<a href="/info/">信息资讯</a> &gt; 
	<a href="/info/?category=<?= $this->escape($this->entity['category_id']) ?>"><?= $this->escape($this->entity['category_name']) ?></a> &gt;  
	<?= $this->escape($this->entity['entity_title']) ?> 
</div>

<!-- 标题 ////////////////////////////////////////////// -->
<?php if(!$this->entity): ?>
<h2 class="txtc">您所请求的信息不存在!</h2>
<?php else: ?>
<h2 class="print txtc">
<?= $this->escape($this->entity['entity_title']) ?>
</h2>

<!-- 同类上下篇 ////////////////////////////////////////////// -->
<table width="100%">
<tr>
<?php if($this->sibling['previous']): ?>
<td width="50%" class="txtl"><img src="/static/images/icon/previous.gif" /> 
<a href="/info/view/detail/id/<?= $this->escape($this->sibling['previous']['entity_id']) ?>">
<?= $this->escape($this->sibling['previous']['entity_title']) ?></a>
</td>
<?php endif; ?>

<?php if($this->sibling['next']): ?>
<td width="50%" class="txtr">
<a href="/info/view/detail/id/<?= $this->escape($this->sibling['next']['entity_id']) ?>">
<?= $this->escape($this->sibling['next']['entity_title']) ?></a> 
<img src="/static/images/icon/next.gif" /> 
</td>
<?php endif; ?>
</tr>
</table>

<p class="txtc quiet">
    已被阅读(<?= $this->entity['entity_view_num'] ?>)&nbsp;&nbsp;&nbsp;
    <?php if($this->role == 'member'): ?>
    发布人:<?= $this->entity['realName'] ?>(<?= $this->entity['role_nickname'] ?>)&nbsp;&nbsp;&nbsp;
    <?php endif; ?>
    发布于:<?= Commons::date($this->entity['entity_pub_time']) ?>&nbsp;&nbsp;&nbsp;
    <?php if($this->entity['entity_mod_time']): ?>
    最后修改于:<?= Commons::date($this->entity['entity_mod_time']) ?>
    <?php endif; ?>
</p>

<!-- 主体 ////////////////////////////////////////////// -->
<div class="f14 span-24 last" style="overflow:hidden">
<?php if($this->entity['entity_private'] == 1 && $this->role != 'member'): ?>
<h2 class="txtc">抱歉~需要登录才能访问该信息</h2>
<form class="prepend-7" method="post" id="relogin_form" onsubmit="return relogin();">
	<table>
		<tr>
			<td class="txtr vm">登录账号：</td>
			<td><input class="text" name="uname" type="text" maxlength="16" value="<?= $this->uname; ?>" /></td>
		</tr>
		<tr>
			<td class="txtr vm">登录密码：</td>
			<td><input class="text" name="pswd" type="password" maxlength="16" value="<?= $this->pswd; ?>" /></td>
		</tr>
		<tr>
			<td class="txtr vm">记住我的账号：</td>
			<td><input id="alive" type="checkbox" checked="checked" value="0" name="alive" /></td>
		</tr>
		<tr>
			<td></td>
			<td><p class="txtr"><input style="width:100%" class="btn" id="btnLogin" type="submit" value="登 录" /></p></td>
		</tr>
	</table>
</form>
<script type="text/javascript">
    <?php if($this->uname && $this->pswd): ?>
    relogin();
    <?php endif; ?>
	// 会员登录
	function relogin() {
		var formdata = $("#relogin_form").fastSerialize();
	
		$.post("/member/login/dologin/", formdata, function(msg) {
			if ("redirect" == msg) {
				history.go(0);
			}
			else alert(msg);
		});
		return false;
	}
</script>
<?php else: ?>
<div class="oneCol print entity" style="padding:25px; line-height:170%">
<?= stripslashes($this->entity['entity_content']) ?>
</div>
<?php endif; ?>
</div>


<!-- 同类上下篇 ////////////////////////////////////////////// -->
<table width="100%">
<tr>
<?php if($this->sibling['previous']): ?>
<td width="50%" class="txtl"><img src="/static/images/icon/previous.gif" /> 
<a href="/info/view/detail/id/<?= $this->escape($this->sibling['previous']['entity_id']) ?>">
<?= $this->escape($this->sibling['previous']['entity_title']) ?></a>
</td>
<?php endif; ?>

<?php if($this->sibling['next']): ?>
<td width="50%" class="txtr">
<a href="/info/view/detail/id/<?= $this->escape($this->sibling['next']['entity_id']) ?>">
<?= $this->escape($this->sibling['next']['entity_title']) ?></a> 
<img src="/static/images/icon/next.gif" /> 
</td>
<?php endif; ?>
</tr>
</table>

<!-- 工具栏 ////////////////////////////////////////////// -->
<p class="extInline2 txtr">
已被阅读(<?= $this->entity['entity_view_num'] ?>)&nbsp;&nbsp;&nbsp;
<?php if($this->tag): ?>本文标签: 
<?php foreach ($this->tag as $k => $v): ?>
<a href="/info/search/look/for/<?= urlencode($this->escape($v)) ?>"><?= $this->escape($v) ?></a>
<?php endforeach; endif; ?>&nbsp;&nbsp;&nbsp;
<img src="/static/images/icon/top.gif" style="cursor:pointer" onclick="javascript:scroll(0,0)" align="absmiddle" />&nbsp;&nbsp;&nbsp;
<img style="cursor: pointer;" src="/static/images/icon/printer.gif" alt="打印" onclick="window.print()" align="absmiddle">
</p>


<div class="span-12 mgu10">
	<!-- 相关文章 ////////////////////////////////////////////// -->
	<table width="100%" class="table-1">
	<tr><th class="txtl">:: 相关文章 ::</th></tr>
	<?php if(!$this->similarity): ?>
	<tr><td class="pd5">没有找到</td></tr>
	<?php else: foreach ($this->similarity as $k2 => $v2): ?>
	<tr>
	<td class="f12 pd5 dashBorder">&raquo; <a href="/info/view/detail/id/<?= $v2['entity_id'] ?>"><?= $this->escape($v2['entity_title']) ?></a></td>
	</tr>
	<?php endforeach; endif; ?>
	</table>
</div>

<div class="span-12 last mgu10">
	<table class="table-1" width="100%">
	<tr><th colspan="2" class="txtl">:: <a href="javascript:toggle()" id="toggleBtn">查看回复</a> :: 
	<a href="javascript:commentForm(<?= $this->entity['entity_id'] ?>)">回复主题</a></th></tr>
	<tr>
		<?php if($this->entity['entity_private'] == 1 && $this->role != 'member'): ?>
		<td class="pd5">需要登录后才能查看回复</td>
		<?php else: ?>
		<td id="commentList" class="hide dashBorder pd10"></td>
		<?php endif; ?>
	</tr>
	</table>
</div>

<?php endif; ?>

<script type="text/javascript">
	function toggle()
	{
		if($('#toggleBtn').text() == '查看回复')
		{
			$('#toggleBtn').text('隐藏回复');
			$('#commentList').show();
		}
		else
		{
			$('#toggleBtn').text('查看回复');
			$('#commentList').hide();
		}
	}
	function commentView(entity_id, page)
	{
		$.post('/info/comment/view', {entity_id:entity_id, page:page}, function(html){
			$('#commentList').html(html);
		});
	}
	
	function commentForm(entity_id)
	{
		$.post('/info/comment/form', {entity_id:entity_id}, function(html){
			$.facebox(html);
		});
	}
	
	commentView(<?= $this->entity['entity_id'] ?>,1);
	toggle();
</script>

<script type="text/javascript">
	$(document).ready(function(){
		var t = window.setTimeout(function(){
			$('.entity img').each(function(){
				if($(this).width()>780)
				{
					$(this).width(780);
				}
				else
				{
					$(this).width('auto');
					$(this).height('auto');
				}
                $(this).wrap('<a target="_blank" href="'+$(this).attr('src')+'"></a>');
				$(this).parent().css('text-align','center');
			});
		},5000);
	});
</script>
