<div class="span-24 last oneCol">
	<p class="extInline2 mg10" style="line-height:150%">
		<?= Cmd::icon('emoticon_grin.png') ?>
		欢迎来到杭州浙江大学校友会网站。我们的
		<b>目标：</b>校友沟通、互助的平台和助手 
		<b>宗旨：</b>联络校友、帮助校友、回报母校
	</p>
	
	<div class="span-11">
		<form class="prepend-1" method="post" id="relogin_form" onsubmit="return relogin();">
			<table>
				<tr>
					<td class="txtr vm">账号：</td>
					<td><input class="text" name="uname" type="text" maxlength="16" value="<?= $this->uname; ?>" /></td>
				</tr>
				<tr>
					<td class="txtr vm">密码：</td>
					<td><input class="text" name="pswd" type="password" maxlength="16" /></td>
				</tr>
				<tr>
					<td class="txtr vm"></td>
					<td><label for="alive"><input id="alive" type="checkbox" checked="checked" value="0" name="alive" /> 记住我的账号</label></td>
				</tr>
				<tr>
					<td></td>
					<td><p class="txtr"><input style="width:100%" class="btn" id="btnLogin" type="submit" value="登 录" /></p></td>
				</tr>
			</table>
		</form>
	</div>
	
	<div class="span-6">
		<h3>杭州浙大校友在这里可以:</h3>
		<ul class="f14">
			<li><?= Cmd::icon('bullet_blue.png') ?> 拥有只属于浙大校友的互动空间</li>
			<li><?= Cmd::icon('bullet_blue.png') ?> 给予和得到来自校友的帮助</li>
			<li><?= Cmd::icon('bullet_blue.png') ?> 组建或参与校友的各种俱乐部</li>
			<li><?= Cmd::icon('bullet_blue.png') ?> 体验高质量的社交环境</li>
			<li><?= Cmd::icon('bullet_blue.png') ?> 自由安全地控制个人隐私</li>
		</ul>
	</div>
	
	<div class="prepend-1 span-4 last">
		<EMBED src=http://sports.sohu.com/upload/20061110daojishi2008/aoyun_djs.swf width=200 height=150 type=application/x-shockwave-flash wmode="transparent" allowNetworking="internal" allowScriptAccess="never"></EMBED>
	</div>
	
	<hr class="space" />
</div>


<div class="span-17 mgu10">
		<table width="100%" class="table-1">
			<tr>
				<th colspan="2" class="f14 txtl pd5"><strong>最新资讯</strong></th>
				<th class="f14 txtl"><strong><a href="/info/">查看更多</a></strong></th>
			</tr>
<?php if(!$this->cache->start('homepage')): ?>
		<?php $rows = $this->info_xmlrpc->call('rpcInfo.get_new'); ?>
		<?php foreach($rows as $row): ?>
		<tr>
			<td class="dashBorder pd5 f12">
				<?= Cmd::icon('bullet_black.png') ?>
				<strong><a href="/info/?category=<?= $row['category_id'] ?>"><?= $row['category_name'] ?></a></strong>
			</td>
			<td class="dashBorder pd5 f14 txtl">
				<a href="/info/view/detail/id/<?= $row['entity_id'] ?>"><?= $row['entity_title'] ?></a>
			</td>
			<td class="dashBorder pd5 quiet">
				<?= Lp_Date::timespan($row['entity_pub_time']) ?> 前
			</td>
		</tr>
		<?php endforeach; ?>
<?php $this->cache->end(); endif; ?>
		</table>
</div>
				
<?= $this->render('home-sub.phtml') ?>


<script type="text/javascript">
	// 会员登录
	function relogin() {
		var formdata = $("#relogin_form").fastSerialize();
	
		$.post("/member/login/dologin/", formdata, function(msg) {
			if ("redirect" == msg) {
				history.go(0);
			}
			else alert(msg);
		});
		return false;
	}
</script>