<div id="main">

<div class="sidebar" style="width:250px;">
<form method="post" onsubmit="return login()">
<div id="login_form">
<p class="account">
登陆账号:<br />
<input value="<?= $this->uname ?>" tabindex="1" name="uname" type="text" class="login_input" onfocus="input_focus('login_input')" onblur="input_blur('login_input')" />
</p>
<p class="password">
密码: (<a href="">忘记了?</a>)<br />
<input tabindex="2" name="pswd" type="password" class="login_input" onfocus="input_focus('login_input')" onblur="input_blur('login_input')" />
</p>
<p>
<input name="rememberme" type="hidden" value="0" />
<label for="alive"><input tabindex="3" id="alive" type="checkbox" checked="checked" value="0" name="alive" /> 记住我的登录账号</label>
</p>
<br />
<table>
<tr>
<td><input tabindex="4" type="image" src="/static/images/btn/login.gif" /></td>
<td valign="middle"><a href="/member/register/" class="registry">我要注册</a></td>
</tr>
</table>
</div>
</form>
</div>

<script type="text/javascript">
function login()
{
	$.post('/member/login/dologin/',
			$("#login_form").fastSerialize(),
			function(data){
				if(data == 'redirect')
				location.href="/home/welcome/";
				else $.facebox('<img src="/static/images/icon/stop.gif" align="absmiddle" /> 登陆失败！')
			}
		);
	return false;
}
</script>
<!-- 宣传+快捷连接 -->
<div class="sidebar">
<div class="intro">
<p class="notice">
	<b>目标：</b>校友沟通、互助的平台和助手<br />
	<b>宗旨：</b>联络校友、帮助校友、回报母校
</p>

<h2>杭州浙大校友在这里可以:</h2>
<ul>
<li>拥有只属于浙大校友的互动空间</li>
<li>给予和得到来自校友的帮助</li>
<li>组建或参与校友的各种俱乐部</li>
<li>体验高质量的社交环境</li>
<li>自由安全地控制个人隐私</li>
</ul>
</div>
</div>

<!-- 专题区 -->
<div class="sidebar subject">
<h2 class='clearfloat'>活动</h2>
<a href="http://www.zjuhz.com/info/view/detail/id/96">5月25日<img src="/static/images/icon/new.gif" /><br />“学在浙大－－浙江大学紫金港校区对外开放日”诚邀在杭校友参加</a>
<a href="http://www.zjuhz.com/info/view/detail/id/92" target="_blank">5月25日<img src="/static/images/icon/new.gif" /><br />金融俱乐部外汇沙龙 </a>
<a href="http://www.zjuhz.com/info/view/detail/id/91" target="_blank">5月24日<img src="/static/images/icon/new.gif" /><br />《中小企业如何在海外上市?》瑞士信贷投行部副总裁杨锐主讲
</a>
<h2>专题</h2>
<a href="/info/subject/index/of/qiushixungen-jiangxi">浙江大学求是寻根 - 江西段</a>
</div>

<?php 
if(!$this->cache->start('homepage')):
?>
<!-- 显示在首页的信息目录列 -->
<div class="sidebar" style="clear:left; width:172px;">
<div id="news_list">
<?php 
$cat_rows = $this->info_xmlrpc->call('rpcInfo.get_public_categories');
foreach ($cat_rows as $k => $v): ?>
<a href="/info/?category=<?= $v['category_id'] ?>" onmouseover="show_news(<?= $k+1 ?>)"><img src="/static/images/icon/<?= $v['category_icon'] ?>.gif" /><?= $v['category_name'] ?></a>
<?php endforeach; ?>
</div>
</div>

<!-- 相应的内容快照 -->
<div class="sidebar" style="width:667px; height:210px; margin-top:15px;">
<?php 
foreach ($cat_rows as $k => $v):
//获取相应文章快照
$art_rows = $this->info_xmlrpc->call('rpcInfo.get_arts_snapshot', array((int)$v['category_id']));
?>			
<table class="news_page" id="num_<?= $k+1 ?>">
<tr>
<td valign="top">							
<?php foreach ($art_rows as $k2 => $v): ?>
<a href="/info/view/detail/id/<?= $v['entity_id'] ?>" title="[<?= Commons::date($v['entity_pub_time']) ?>] <?= $v['entity_title'] ?>"><?= substr($v['entity_title'],0,60).'..' ?></a>
<?php endforeach; ?>
</td>
<td width="253"><img src="/static/images/pics/<?= $k+1 ?>.jpg" /></td>
</tr>
</table>
<?php endforeach; $this->cache->end(); endif; ?>
</div>

<script type="text/javascript">show_news(1)</script>