<?php

/* filename = 'language.extension' */

$lang_files=array();

$lang_files[]='english.utf8';
$lang_files[]='bulgarian.utf8';
$lang_files[]='chinese.utf8';
$lang_files[]='croatian.utf8';
$lang_files[]='czech.utf8';
$lang_files[]='deutsch.utf8';
$lang_files[]='dutch.utf8';
$lang_files[]='finnish.utf8';
$lang_files[]='french.utf8';
$lang_files[]='georgian.utf8';
$lang_files[]='greek.utf8';
$lang_files[]='hungarian.utf8';
$lang_files[]='italian.utf8';
$lang_files[]='norwegian.utf8';
$lang_files[]='polish.utf8';
$lang_files[]='portuguese.utf8';
$lang_files[]='russian.utf8';
$lang_files[]='serbian.utf8';
$lang_files[]='slovak.utf8';
$lang_files[]='slovenian.utf8';
$lang_files[]='spanish.utf8';
$lang_files[]='swedish.utf8';
$lang_files[]='turkish.utf8';
$lang_files[]='vietnamese.utf8';

?>