<div class="corner-box floatLeft">
    <b class="corner-box-title">企业资料</b>
    <ul style="padding-bottom:10px;">
        <li>正在完善商务供求</li>	  
    </ul>
</div>

<div class="floatLeft" style="padding-bottom:30px;">
  <h2>修改企业商务供求</h2>  
  <form name="frmBiz" id="frmBiz" autocomplete="off">
  <table style="margin:0 0 0 20px;" width="650px" cellpadding="0" cellspacing="0">
      <tr>
      <td>
          <p class="tip"><img src="/static/images/icon/info.gif" align="absmiddle" />&nbsp;&nbsp;<strong>在您输入以下内容时请务必以<u>空格</u>去间隔各关键字。例如：关键字1&nbsp;&nbsp;关键字2&nbsp;&nbsp;关键字3。</strong></p>
      </td>
      </tr>
  </table>
  <br />
  <table class="table" style="margin:0 0 0 20px;" width="650px" cellpadding="0" cellspacing="0">
      <tr>
          <td class="txtr">产品服务关键字：<br />(我公司能提供...)</td>
	  <td><textarea name="product" cols="60" rows="5" class="txt" id="product" tabindex="1"><?= $this->dataCompany['product'] ;?></textarea><p><span class="quiet f12">例如某房产公司可这样输入：楼房租售 权证过户 房产评估。</span></p></td>
      </tr>
      <tr>
	  <td class="txtr">岗位需求关键字：<br />(我公司要招聘...)</td>
	  <td><textarea name="job" cols="60" rows="5" class="txt" id="job" tabindex="2"><?= $this->dataCompany['job'] ;?></textarea>
	  <p><span class="quiet f12">例如某电脑公司可这样输入：软件测试 Java工程师 网页设计。</span></p></td>
      </tr>
      <tr>
          <td class="txtr">合作意向关键字：<br />(寻觅如下合作...)</td>
	  <td><textarea name="cooperate" cols="60" rows="5" class="txt" id="cooperate" tabindex="3"><?= $this->dataCompany['cooperate'] ;?></textarea><p><span class="quiet f12">您可输入如商务服务合作、产品合作、媒体合作、网站合作等各类关键字。</span></p></td>
      </tr>
      <tr>
	  <td>&nbsp;</td>
	  <td><input type="submit" id="btnBiz" tabindex="4" value=" 提 交 修 改 " class="buttonGreen" />
	    <table width="100%" border="0">
          <tr>
            <td colspan="2"><img src="/static/images/icon/lightbulb.gif">&nbsp;&nbsp;<span class="quiet f12">您在本页输入的内容最终是便于校友搜索，在输入时您可重复重要的关键字；<br />如某公司是联想电脑代理商，在输入"联想电脑"后同时还输入了"联想"和"电脑"。</span></td>
            </tr>
        </table>
	  </td>
      </tr>
      <tr>
	  <td>&nbsp;</td>
	  <td><div id="ajaxhint" style="width:300px"></div></td>
      </tr>
  </table>
  </form>
</div>
