<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="zh-CN" />
<?= $this->headMeta(); ?>
<script type="text/javascript" src="/static/scripts/jquery.js"></script>
<script type="text/javascript" src="/static/scripts/common.js"></script>
<?= $this->headLink().$this->headStyle().$this->render("head.phtml").$this->headScript(); ?>
<link rel="stylesheet" type="text/css" href="/static/styles/company/admin.css" media="screen" />
<title>企业展示 - 后台管理 :: 杭州浙江大学校友会</title>
</head>
<body>
	<div id="wrap">
		<div id="header" style="background:none">
    <table id="passport" cellpadding="0" cellspacing="0" width="100%">
      <tr>
        <td style="text-align:left"><a href="/member/">校友</a> | <a href="/info/">资讯</a> | <a href="/help/">互助</a> | <a href="/class/">班级</a> | <a href="#">群组</a> | <a href="#">活动</a> </td>
        <td style="text-align:right" class="pdr10">
        	<?php if ($this->sessCommon->login) { ?>
			您好，<?= $this->sessCommon->login['realName']; ?>|<a href="/company/my/">我的创业</a>|<a href="/member/my/">我的账号</a><!--|<a href="">站内信<?= ($this->sessCommon->login['unRead'] > 0) ? "({$this->sessCommon->login['unRead']})" : ''; ?></a>-->|<a href="/member/logout/" onClick="return window.confirm('确实要退出吗？');">退出</a>
			<?php }	else { ?>
			<a href="/member/register/">注册</a>|<a href="/member/login/">登录</a>
			<?php } ?>
		</td>
      </tr>
    </table>
			<h1><?= $this->company_name ?> - 企业展示管理</h1>
		</div>
		
		<div id="container">
			<?= $this->layout()->nav; ?>
			
			<div class="content">
				<?= $this->layout()->content; ?>
			</div>
		</div>
		
		<div id="footer">
		<a href="/info/support/help">帮助</a> | 
			<a href="/info/support/about">关于</a> | 
			<a href="/info/support/contact_us">联系我们</a> | 
			<a href="/info/support/privacy_claim">隐私声明</a> | 
			<a href="http://www.zjuhz.com/old" target="_blank">旧版回顾</a> | 
			<a href="http://ourzju.uu1001.com" target="_blank">校友论坛</a> 
			<a href="http://www.miibeian.gov.cn" target="_blank">浙ICP备06052510号</a> 
			
			杭州浙江大学校友会(筹)&copy;2008 
			
	</div>
		
	</div>
</body>
</html>