<style type="text/css">
.contactus{ padding:10px 30px;  font-size:13px; }
.contactus h2{ font-size:16px; color:#2A5877 }
.contactus p{ line-height:180%; font-size:14px; padding: 5px 0; }
</style>
<div class="sidebar p10 contactus">
<img src="/static/images/view-2.jpg" class="p8" align="right" />
<h2>:: 联系我们 ::</h2>
<hr />
<p>地址：杭州市西溪路525号浙大科技园C楼608</p>
 
<p>邮编：310013</p>
<p>电话：0571-8998 8185/8998 8186</p>
<p>传真：0571-8512 1608</p>
<p>网址：<a href="http://www.zjuhz.com">http://www.zjuhz.com</a></p>
 


<p class="txtc"><button onclick="history.back()" class="btn">返回</button></p>
</div>