<?= $this->render('home/index.phtml'); ?>
<!-- 管理条目 ///////////////////////////////////// -->
<div class="sidebar" style="width:160px">
<p class="toolbar">
<a href="/class/home?c=<?= $this->class_id ?>"><img src="/static/images/icon/arrow_undo.gif" /> 返回</a>
<a href="/class/album/public?c=<?= $this->class_id ?>"><img src="/static/images/icon/add.gif" /> 发布新照片</a>
</p>
</div>

<!-- 班级照片详细列表 ///////////////////////// -->
<div class="sidebar cont_list">
<table id="class_topics" width="100%">
<tr>
<th colspan="3" class="txtl quiet">
<img src="/static/images/icon/picture.gif" /> <b>班级相册</b>
<select class="inputtxt" style="width:150px" name="category" onchange="window.location.href='/class/album/list?c=<?= $this->class_id ?>&f='+this.value">
<?= $this->albumcategory($this->class_id, $this->f) ?>
</select>
<?= $this->numrows ?> 张
</th>
<th class="txtr"><a href="/class/album/public?c=<?= $this->class_id ?>" style="background:url(/static/images/icon/add.gif) no-repeat left center; padding-left:18px;">新照片</a></th>
</tr>
<tr class="quiet">
	<td width="40%">图片预览</td>
	<td width="20%">发布人</td>
	<td width="10%" class="txtc">评论</td>
	<td width="30%" class="txtc">操作</td>
</tr>

<?php if(count($this->items)>0): foreach($this->items as $v): ?>
<tr class="item" id="no_<?= $v['class_album_id']?>">
	<td>
		<a class="thickbox" href="/static/classes/<?= $this->class_id.'/album/'.$v['class_album_filename'] ?>">
			<img src="/static/classes/<?= $this->class_id.'/album/'.$v['class_album_filename'] ?>" alt="<?= stripslashes($v['class_album_name']) ?>" height="100" />
		</a>
	</td>
	<td>
		<a href=""><?= $v['realName'] ?></a><br />
		<?= Commons::date($v['class_album_pub_time']) ?>
	</td>
	<td class="txtc">
		<?= $v['class_album_reply_num'] ?>条 <br />
		<a href="/class/album/view?c=<?= $this->class_id ?>&aid=<?= $v['class_album_id'] ?>">查看</a>
	</td>
	<td class="txtc">
		
		<a href="/class/ajax/download_pic?c=<?= $this->class_id ?>&file=<?=$v['class_album_filename'] ?>&name=<?= stripslashes($v['class_album_name']) ?>">
			<img src="/static/images/icon/disk.gif" />
		</a>
		<a href="javascript:albumReplyForm(<?= $this->class_id.','.$v['class_album_id'].',1' ?>)">发表评论</a><br />
		<?php if(true == Cmd::isManager($this->class_id)): // 管理员可做 ?>
		移动到：
		<select class="inputtxt" name="change" onchange="moveAlbumCategory(<?= $v['class_album_id'].','.$this->class_id ?>)">
		<?= $this->albumcategory($this->class_id, $v['class_album_category']) ?>
		</select>
		<br />
		或：<input type="text" name="new" class="inputtxt" size="10" /> 
		<input class="btn" type="button" onclick="newAlbumCategory(<?= $v['class_album_id'].','.$this->class_id ?>)" value="新建" />
		<?php endif; ?>
	</td>
</tr>
<?php endforeach; else: ?>
<tr>
	<td colspan='4'>该类别没有任何照片</td>
</tr>
<?php endif; ?>
</table>

<div class="pagination"><?= $this->pagination ?></div>
</div>


<script type="text/javascript">
	$('.item').each(function(i){
		if(i%2 == 0) {
			$(this).css('background','#f5f5f5');
		}
	});
</script>