<form id="album_form" action="public?c=<?= $this->class_id ?>" enctype="multipart/form-data" method="post">
<input type="hidden" name="class_id" value="<?= $this->class_id ?>" ?>
<div class="sidebar" style="width:200px; padding:10px 0 10px 10px;">
<div class="options">
<p><b><img src="/static/images/icon/lock.gif" /> 隐私控制</b><br />
<select name="topic_public" style="width:150px" class="inputtxt mu5">
<option value="0">只对班级公开</option>
<option value="1">完全公开</option>
</select></p>

<p class="mu10">
  <b><img src="/static/images/icon/tag.gif" /> 标签</b><br />
   <input type="text" name="tag[]" size="6" class="inputtxt mu5" /><span class="tag_inner"></span>
  <a href="javascript:add_tag()">增加</a> <a href="javascript:strip_tag()">清除</a>
</p>
</div>
</div>

<!-- 发布新话题 /////////////////////////////////////// -->
<table class="sidebar" style="width:550px; padding:10px; margin:20px;">
<tr>
	<td class="pud10 quiet">
		<b>请选择分类：</b>
	</td>
	<td>
		<select name="category">
		<option value="未分类">未分类</option>
		</select>
		<input class="inputtxt" type="file" name="userfile" />
	</td>
</tr>
<tr>
	<td class="pud10 quiet">
		<b>照片名称：</b>
	</td>
	<td>
		<input type="text" name="name" class="inputtxt" style="width:400px;" maxlength="100" />
	</td>
</tr>
<tr>
	<td class="pud10 quiet">
		<b>照片描述：</b>
	</td>
	<td><textarea name="description" class="inputtxt" style="width:400px; height:100px"></textarea></td>
</tr>
<tr>
	<td></td>
	<td class="pud10 quiet">
		<input type="submit" value="上传新照片" class="btn" /> 
		<input type="button" value="返回" class="btn" onclick="history.back()" />
	</td>
</tr>
</table>
</form>
