<form id="reply_form" onsubmit="return postAlbumReply()">
<input type="hidden" name="class_id" value="<?= $this->class_id ?>" />
<input type="hidden" name="album_id" value="<?= $this->album_id ?>" />
<input type="hidden" name="page" value="<?= $this->page ?>" />
<h2 class="quiet f14">提交回复</h2>
<span id="result"></span>
<p class="pud10"><b>标题</b> <input type="text" name="reply_title" class="inputtxt" style="width:400px" /></p>
<p><textarea class="inputtxt" name="content" style="width:500px;height:180px;"></textarea></p>
<p class="pud10"><input type="submit" class="btn" value="提交回复" /></p>
</form>