<?php foreach ($this->rows as $key => $val): ?>
<table class="addressbook_item">
<tr>
<td width="10%" valign="top"><img src="/static/users/user_test/tiny_head.jpg" /></td>
<td>
	<table>
		<tr><th colspan="2" class="txtl" width="100%"><a href=""><?= $val['cname'] ?></a></th></tr>
		<tr>
			<td class="quiet" width="18%">手机：</td>
			<td width="32%"><?= $val['mobile'] ?></td>
			<td class="quiet" width="10%">座机：</td>
			<td width="40%"><?= $val['addressbook_telephone'] ?></td>
		</tr>
		<tr>
			<td class="quiet">QQ：</td>
			<td><?= $val['qq'] ?></td>
			<td class="quiet">MSN：</td>
			<td><?= $val['msn'] ?></td>
		</tr>
		<tr>
			<td class="quiet">公司：</td>
			<td><?= $val['addressbook_company'] ?></td>
			<td class="quiet">邮箱：</td>
			<td><?= $val['eMail'] ?></td>
		</tr>
		<tr>
			<td class="quiet">通讯地址：</td>
			<td colspan="3"><?= $val['address'] ?></td>
		</tr>
		<tr>
			<td class="quiet">邮政编码：</td>
			<td colspan="3"><?= $val['postcode'] ?></td>
		</tr>
	</table>
</td>
</tr>
</table>
<?php endforeach; ?>
<div class="pagination"><?= $this->pagination; ?></div>
