<table class="class_list" style="width:100%; margin-left:0">
<tr class="quiet">
<th><a href="javascript:selectAll('member_id')">全选</a></th>
<th>班级成员</th>
<th>身份</th>
<th>最后登录<input type="hidden" name="class_id" value="<?= $this->class_id ?>" /></th>
</tr>
<?php foreach ($this->members as $k=>$v): ?>
<tr>
<td><input type="checkbox" value="<?= $v['class_member_id'] ?>"<?php if($v['class_member_charge'] == 1 || $v['class_charge'] == $v['class_member_id']) echo ' disabled'; else echo 'name="member_id[]"'?> /></td>
<td><a href=""><?= $v['realName'] ?></a></td>
<td><?php 
	if($v['class_member_charge'] == 1) echo '管理员'; 
	elseif($v['class_charge'] == $v['class_member_id']) echo '创建人'; 
	else echo '成员' ?></td>
<td class="quiet f9"><?= $v['class_member_last_access'] != '' ? Commons::date($v['class_member_last_access']) : '未登录过' ?>
</td>
</tr>
<?php endforeach; ?>
</table>
<p class="txtc">
	<button class="btn" onclick="memberLvlup(<?= $this->class_id ?>)">提升为管理员</button> 
	<button class="btn" onclick="memberOut(<?= $this->class_id ?>)">踢出本班</button>
</p>