<div class="corner-box floatLeft">
    <b class="corner-box-title">企业资料</b>
	<ul style="padding-bottom:10px;">
	  <li>正在完善联系方式</li>	  
	</ul>
</div>

<div class="floatLeft" style="padding-bottom:30px;">
  <h2>修改企业联系方式</h2>
  <form name="frmContact" id="frmContact" autocomplete="off">
   <table class="table" style="margin:0 0 0 20px;" width="650px" cellpadding="0" cellspacing="0">
	  <tr>
		<td class="txtr">企业电话：</td>
		<td><input type="text" tabindex="1" maxlength="13" size="25" name="phone" id="phone" value="<?= $this->dataCompany['phone'] ;?>"><p><span class="quiet f12">格式为区号-电话，如0571-89988185。</span></p></td>
	  </tr>
	  <tr>
		<td class="txtr">企业传真：</td>
		<td><input type="text" tabindex="2" maxlength="13" size="25" name="fax" id="fax" value="<?= $this->dataCompany['fax'] ;?>"></td>
	  </tr>
	  <tr>
		<td class="txtr">电子邮箱：</td>
		<td><input type="text" tabindex="3" maxlength="50" size="50" name="eMail" id="eMail" value="<?= $this->dataCompany['eMail'] ;?>"><p><span class="quiet f12">输入您企业的业务联系邮箱，格式应为：yourname@domain.com。</span></p></td>
	  </tr>
	  <tr>
		<td class="txtr">企业网站：</td>
		<td><input type="text" tabindex="4" maxlength="50" size="50" name="url" id="url" value="<?= $this->dataCompany['url'] ;?>"> <p><span class="quiet f12">在此输入以 http:// 为前缀的网站域名。</span></p></td>
	  </tr>
	  <tr>
		<td class="txtr">办公地址：</td>
		<td><input type="text" tabindex="5" maxlength="80" size="50" name="address" id="address" value="<?= $this->dataCompany['address'] ;?>"></td>
	  </tr>
	  <tr>
		<td class="txtr">邮政编码：</td>
		<td><input type="text" tabindex="6" maxlength="6" size="10" name="postcode" id="postcode" value="<?= $this->dataCompany['postcode'] ;?>"></td>
	  </tr>
	  <tr>
		<td class="txtr">其它方式：</td>
		<td><textarea name="other" cols="50" class="txt" id="other" tabindex="7"><?= $this->dataCompany['other'] ;?></textarea><p><span class="quiet f12">在此可输入其它联系方式，如QQ/MSN/其它电话号码等。</span></p></td>
	  </tr>
	  <tr>
		<td>&nbsp;</td>
		<td><input type="submit" id="btnContact" tabindex="8" value=" 提 交 修 改 " class="buttonGreen" /></td>
	  </tr>
	  <tr>
		<td>&nbsp;</td>
		<td><div id="ajaxhint" style="width:300px"></div></td>
	  </tr>
	</table>
  </form>
</div>
