<div class="corner-box floatLeft">
    <b class="corner-box-title">产品上传</b>
    <ul style="padding-bottom:10px;">
        <li>上传产品图片介绍</li>
    </ul>
</div>

<div class="floatLeft" style="padding-bottom:30px;">
  <h2>产品展示</h2>
    <form target="doUpload" action="/biz/manage/doupload" name="pro_form" method="post" enctype="multipart/form-data" onsubmit="editor.data()">
        <p class="pd10">图片 <input type="file" name="img" value="" size="20" /> <span class="quiet">支持jpg、gif、png格式图片，每张限500K以内</span></p>
        <?php if(count($this->sorts) == 0): ?>
        <p class="pd10">分类 <input type="text" name="sort" /></p>
        <?php else: ?>
        <p class="pd10">分类 <select name="sort">
            <?php foreach($this->sorts as $s): ?>
            <option value="<?= $s['sort'] ?>">
                <?= $s['sort'] ?>
            </option>
            <?php endforeach; ?>
        </select>
        <input type="text" name="sort_n" /> <span class="quiet f12">(新分类,留空则使用选择框的分类)</span>
        </p>
        <?php endif; ?>
        <p class="pd10">名称 <input type="text" name="name" style="width:520px;" /></p>
        <p class="pd10">介绍 <input type="hidden" name="intro" id="intro" value="" /><?= ($this->kindeditor('intro','100%','200px')); ?></p>
        <p class="txtr"><input type="submit" value="提交" class="buttonGreen" /></p>
    </form>
    <iframe id="doUpload" style="display:none" name="doUpload"></iframe>
        <br />
    <span id="pro_tip"></span>
</div>
<script type="text/javascript">
    function setTip(html, ref)
    {
        $('#pro_tip').html(html);
        if(ref == 1)
        $('#pro_tip').children().fadeOut(2000, function(){ location.href="/biz/manage/company/type/production/"; });
        else
        $('#pro_tip').children().fadeOut(2000);
    }
</script>