<form id="modi_from" target="domodify" action="/biz/manage/domodify" method="post" enctype="multipart/form-data">
    <input type="hidden" name="pid" value="<?= $this->item['pid'] ?>" />
    <input type="hidden" name="img_n" value="<?= $this->item['img'] ?>" />
    <p class="pd10">图片 <input type="file" name="img" value="" size="20" /> <span class="quiet">支持jpg、gif、png格式图片，每张限500K以内</span></p>
    <p class="pd10">分类：<input name="sort" class="f14" type="text" value="<?= $this->item['sort'] ?>" /></p>
    <p class="pd10">名称：<input name="name" class="f14" type="text" value="<?= $this->item['name'] ?>" size="80" /></p>
    <p class="pd10">介绍：<textarea name="intro" style="width:800px; height:200px;"><?= stripslashes($this->item['intro']) ?></textarea></p>
    <p style="text-align:center"><input class="buttonGreen" type="submit" value="保存修改" /></p>
</form>
    <iframe id="domodify" style="display:none" name="domodify"></iframe>
