<table class="table" cellpadding="0" cellspacing="0" style="background:#fff; border:none;" width="100%">
    <tr>
        <th width="30%">连接名称</th>
        <th>地址</th>
        <th width="15%">操作</th>
    </tr>
    <tr>
        <td><input type="text" name="name" value="" style="width:100%" /></td>
        <td><input type="text" name="url" value="" style="width:100%" /></td>
        <td>
            <input type="button" class="buttonGreen" value="添加" />
        </td>
    </tr>
    <tr>
        <td><input type="text" name="name" style="width:100%" value="新浪体育" /></td>
        <td><input type="text" name="url" style="width:100%" value="http://sports.sina.com.cn" /></td>
        <td>
            <input type="button" class="buttonGreen" value="修改" />
            <input type="button" class="button" value="删除" />
        </td>
    </tr>
</table>