<div class="control_tab">
<a href="?sub=addressbook&tab=list">通讯录列表</a>
<a href="?sub=addressbook&tab=new">添加</a>
<a href="?sub=addressbook&tab=mod">修改</a>

<p style="float:right;margin-top:10px; color:#666">
<img src="/static/images/bullet/red.gif" />未邀请未注册 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<img src="/static/images/bullet/orange.gif" />已邀请未注册 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<img src="/static/images/bullet/green.gif" />已注册 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</p>
</div>

<div class="control_action">
<?= $this->render('index/home-data-addressbook-'.$this->tab.'.phtml'); ?>
</div>
<script>
$('.control_tab a').removeClass('focus');
$('.control_tab a[href="?sub=addressbook&tab=<?= $this->tab ?>"]').addClass('focus');
</script>