<form class="home_form">
<table id="job_tbl">
<tr>
<td><b>公司名称：</b></td>
<td><input type="text" class="txt" /></td>
</tr>
<tr>
<td><b>职位：</b></td>
<td><input type="text" class="txt" /></td>
</tr>
<tr>
<td><b>描述：</b></td>
<td><textarea class="bigtxt"></textarea></td>
</tr>
<tr>
<td><b>工作时间：</b></td>
<td><select name="join_year_1" tabindex="5" id="join_year_1" class="select"><option value="0">年份：</option>
									
									
									


		
			<option value="2008">2008</option>
		
			<option value="2007">2007</option>
		
			<option value="2006">2006</option>
		
			<option value="2005">2005</option>

		
			<option value="2004">2004</option>
		
			<option value="2003">2003</option>
		
			<option value="2002">2002</option>
		
			<option value="2001">2001</option>
		
			<option value="2000">2000</option>
		
			<option value="1999">1999</option>

		
			<option value="1998">1998</option>
		
			<option value="1997">1997</option>
		
			<option value="1996">1996</option>
		
			<option value="1995">1995</option>
		
			<option value="1994">1994</option>
		
			<option value="1993">1993</option>

		
			<option value="1992">1992</option>
		
			<option value="1991">1991</option>
		
			<option value="1990">1990</option>
		
			<option value="1989">1989</option>
		
			<option value="1988">1988</option>
		
			<option value="1987">1987</option>

		
			<option value="1986">1986</option>
		
			<option value="1985">1985</option>
		
			<option value="1984">1984</option>
		
			<option value="1983">1983</option>
		
			<option value="1982">1982</option>
		
			<option value="1981">1981</option>

		
			<option value="1980">1980</option>
		
			<option value="1979">1979</option>
		
			<option value="1978">1978</option>
		
			<option value="1977">1977</option>
		
			<option value="1976">1976</option>
		
			<option value="1975">1975</option>

		
			<option value="1974">1974</option>
		
			<option value="1973">1973</option>
		
			<option value="1972">1972</option>
		
			<option value="1971">1971</option>
		
			<option value="1970">1970</option></select>
								<select name="join_month_1" tabindex="6" id="join_month_1" class="select"><option value="0">月份：</option>

									
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>

<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option></select>
								到
								<span style="" id="quit_span_1">
								<select name="quit_year_1" tabindex="7" id="quit_year_1" class="select"><option value="0">年份：</option>

									
									
									


		
			<option value="2008">2008</option>
		
			<option value="2007">2007</option>
		
			<option value="2006">2006</option>
		
			<option value="2005">2005</option>
		
			<option value="2004">2004</option>
		
			<option value="2003">2003</option>

		
			<option value="2002">2002</option>
		
			<option value="2001">2001</option>
		
			<option value="2000">2000</option>
		
			<option value="1999">1999</option>
		
			<option value="1998">1998</option>
		
			<option value="1997">1997</option>

		
			<option value="1996">1996</option>
		
			<option value="1995">1995</option>
		
			<option value="1994">1994</option>
		
			<option value="1993">1993</option>
		
			<option value="1992">1992</option>
		
			<option value="1991">1991</option>

		
			<option value="1990">1990</option></select>
								<select name="quit_month_1" tabindex="8" id="quit_month_1" class="select"><option value="0">月份：</option>
									
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>

<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option></select></td>
</tr>
</table>

<table id="expand"></table>

<table>
<tr>
<td><b>附加内容：</b></td>
<td><a href="javascript:new_job()">添加公司</a></td>
</tr>
<tr>
<td>&nbsp;</td>
<td><input type="submit" class="btn" value="保存修改" /></td>
</tr>
</table>
</form>
<script>
function new_job()
{
	$('#expand').append($('#job_tbl').html());
}
</script>