<!-- 左侧栏 //////////////////////////////////////// -->
<div class="sidebar">
<div class="member_card">
<table>
<tr>
<td><img src="/static/users/user_test/tiny_head.jpg" class="head" /></td>
<td>
<p>小王</p>
<p>积分 100</p>
</td>
</tr>
</table>
</div>

<div class="control_link">
<a href="">我的首页</a>
<a href="" class="focus">我的提问</a>
<a href="">我的回答</a>
<a href="">我的收藏</a>
<a href="">我的好友</a>
</div>
</div>

<!-- 中间部分 ////////////////////////////////////////// -->
<div class="sidebar">
<h2 class="control_nav">
<a href="/temp/index/home/of/data">资料</a> - 互助 - <a href="/temp/index/home/of/class">班级</a> - <a href="/temp/index/home/of/address_list">通讯录</a> - <a href="">相册</a> - <a href="">日志</a> - <a href="">活动</a>
</h2>
<div class="control_content">
<table>
<tr class="control_tab">
<td>
<a href="" class="focus">等待校友帮助的问题</a>
<a href="">已经解决的问题</a>
<a href="">不了了之的问题</a>
</td>
</tr>

<tr>
<td colspan="3">
<!-- 问题列表 //////////////////////////////////////// -->
<table class="help_list">
<tr>
<th class="txtl">标题</th>
<th class="txtl">回答数</th>
<th class="txtl">提交时间</th>
</tr>
<tr>
<td><a href="">编程#include <stdio.h></a> [<a href="" class="cat">编程</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">瑞星杀毒软件没装防火墙对于电脑上网安全有没有大碍?</a> [<a href="" class="cat">反病毒</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">谁有网页教学好的网站最好是从最低级的开始</a> [<a href="" class="cat">互联网</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">怎么知道一个网站的动态效果是用什么做的?</a> [<a href="" class="cat">网页制作</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">请教div+css中padding的一些用法？</a> [<a href="" class="cat">编程</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">为什么要上网?</a> [<a href="" class="cat">互联网</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">编程#include <stdio.h></a> [<a href="" class="cat">编程</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">编程#include <stdio.h></a> [<a href="" class="cat">编程</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">编程#include <stdio.h></a> [<a href="" class="cat">编程</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">编程#include <stdio.h></a> [<a href="" class="cat">编程</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>

</table>
</td>
</tr>
</table>

<div class="pagination"><a href="">上一页</a> <a href="">1</a> <a href="">2</a>  <b>3</b> <a href="">下一页</a></div>
</div>

</div>