<form class="home_form">
<p><b>兴趣爱好</b><br />
<textarea class="bigtxt"></textarea>
</p>
<p><b>喜欢的音乐</b><br />
<textarea class="bigtxt"></textarea>
</p>
<p><b>喜欢的电影</b><br />
<textarea class="bigtxt"></textarea>
</p>
<p><b>喜欢的运动</b><br />
<textarea class="bigtxt"></textarea>
</p>
<p><b>喜欢的人物</b><br />
<textarea class="bigtxt"></textarea>
</p>
<p><b>喜欢的书籍</b><br />
<textarea class="bigtxt"></textarea>
</p>
<p>
        					<input type="submit" value="保存修改" class="btn" />
        				</p>
</form>