<table class="control_list">
<tr>
<th>
<form>
<select class="txt">
<option>名字</option>
<option>手机</option>
<option>邮箱</option>
<option>地址</option>
</select>
<input type="text" class="txt" /> <input type="submit" class="btn" value="查找" />
</form>
</th>
<th class="txtl">状态</th>
<th class="txtl">操作</th>
</tr>
<tr>
<td>
<p>
<a href="">某某某

</a>
<span class="more"><img src="/static/images/icon/building.gif" />  浙江省杭州市学院路130号（中宙大厦）718室</span>
</p>
</td>
<td><img src="/static/images/bullet/orange.gif" /></td>
<td><button>修改</button></td>
</tr>

</table>

<div class="pagination"><a href="">1</a><a href="">2</a><b>3</b></div>