<table class="control_list">
<tr>
<th class="txt">标题</th>
<th class="txtl">回答数</th>
<th class="txtl">提交时间</th>
</tr>
<tr>
<td><a href="">编程#include <stdio.h></a> [<a href="" class="cat">编程</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">瑞星杀毒软件没装防火墙对于电脑上网安全有没有大碍?</a> [<a href="" class="cat">反病毒</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">谁有网页教学好的网站最好是从最低级的开始</a> [<a href="" class="cat">互联网</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">怎么知道一个网站的动态效果是用什么做的?</a> [<a href="" class="cat">网页制作</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">请教div+css中padding的一些用法？</a> [<a href="" class="cat">编程</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
<tr>
<td><a href="">为什么要上网?</a> [<a href="" class="cat">互联网</a>]</td>
<td width="10%">23</td>
<td width="20%">2008-04-03 11:24</td>
</tr>
</table>

<div class="pagination"><a href="">1</a><a href="">2</a><b>3</b></div>