<!-- 互助分类 -->
<div class="sidebar">
<div class="help_category">
<h2 class="fw14">问题分类</h2>
<p>
<a href="" class="M">时尚生活</a>
<a href="">购物</a>
<a href="">旅行</a>
<a href="">美食</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">娱乐休闲</a>
<a href="">影视</a>
<a href="">明星</a>
<a href="">占卜</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">电脑网络</a>
<a href="">联网</a>
<a href="">硬件</a>
<a href="">软件</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">电子游戏</a>
<a href="">网络</a>
<a href="">单机</a>
<a href="">家用</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">健康医学</a>
<a href="">咨询</a>
<a href="">常识</a>
<a href="">健身</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">商业经济</a>
<a href="">房产</a>
<a href="">股票</a>
<a href="">外汇</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">体育运动</a>
<a href="">篮球</a>
<a href="">足球</a>
<a href="">奥运</a>
<a href="">..</a>
</p>

<p>
<a href="" class="M">职场人际</a>
<a href="">交际</a>
<a href="">求职</a>
<a href="">跳槽</a>
<a href="">..</a>
</p>

</div>
</div>


<div class="sidebar">
<!-- 互助广播 -->
<div class="help_notice" start="2">
<strong><img src="/static/images/icon/sound_none.gif" /></strong>
<a href="" class="nt" style="display:block">* 最近有什么好看的电视剧吗?</a>
<a href="" class="nt">* 在公司做Pro/E设计师该注意什么？</a>
<a href="" class="nt">* 夏利车是7101电喷的发动机的带速乎高乎低怎么办？</a>
<a href="" class="nt">* 凡高的代表作是什么?</a>
<a href="" class="nt">* 去法国旅游，最值得去的景点有哪些？</a>
<a href="" class="nt">* 天上为什么会有太阳</a>
</div>

<!-- 问题集合 -->
<table class="help_set">
	<tr>
	<th class="txtl">最新求助</th>
	<th class="txtr" colspan="2">更多&raquo;</th>
	</tr>
	<tr>
	<td class="cat"><a href="/temp/index/sub/">[反病毒]</a></td>
	<td><a href="/temp/index/detail/">个人电脑装什么防火墙和杀毒软件好啊</a></td>
	</tr>
	<tr>
	<td class="cat"><a href="">[人际交往]</a></td>
	<td><a href="">如何处理好人际关系？</a></td>
	</tr>
	<tr>
	<td class="cat"><a href="">[节日假期]</a></td>
	<td><a href="">如何提倡国人文明扫墓？</a></td>
	</tr>
	<tr>
	<td class="cat"><a href="">[留学移民]</a></td>
	<td><a href="">办日本的学生需要什么证件和流程?</a></td>
	</tr>
	<tr>
	<td class="cat"><a href="">[奥运]</a></td>
	<td><a href="">	2008奥运会跳水项目在哪进行？</a></td>
	</tr>
	<!-- 高分////////////////////////////////////////// -->
	<tr>
	<th class="txtl">高分求助</th>
	<th class="txtr" colspan="2">更多&raquo;</th>
	</tr>
	<tr>
	<td class="cat"><a href="">[反病毒]</a></td>
	<td><a href="">个人电脑装什么防火墙和杀毒软件好啊</a></td>
	<td class="coin">40</td>
	</tr>
	<tr>
	<td class="cat"><a href="">[人际交往]</a></td>
	<td><a href="">如何处理好人际关系？</a></td>
	<td class="coin">30</td>
	</tr>
	<tr>
	<td class="cat"><a href="">[节日假期]</a></td>
	<td><a href="">如何提倡国人文明扫墓？</a></td>
	<td class="coin">20</td>
	</tr>
	<tr>
	<td class="cat"><a href="">[留学移民]</a></td>
	<td><a href="">办日本的学生需要什么证件和流程?</a></td>
	<td class="coin">10</td>
	</tr>
	<tr>
	<td class="cat"><a href="">[奥运]</a></td>
	<td><a href="">	2008奥运会跳水项目在哪进行？</a></td>
	<td class="coin">5</td>
	</tr>
	<!-- 被遗忘////////////////////////////////////////// -->
	<tr>
	<th class="txtl">被遗忘的</th>
	<th class="txtr" colspan="2">更多&raquo;</th>
	</tr>
	<tr>
	<td class="cat"><a href="">[反病毒]</a></td>
	<td><a href="">个人电脑装什么防火墙和杀毒软件好啊</a></td>
	</tr>
	<tr>
	<td class="cat"><a href="">[人际交往]</a></td>
	<td><a href="">如何处理好人际关系？</a></td>
	</tr>
	<tr>
	<td class="cat"><a href="">[节日假期]</a></td>
	<td><a href="">如何提倡国人文明扫墓？</a></td>
	</tr>
	<tr>
	<td class="cat"><a href="">[留学移民]</a></td>
	<td><a href="">办日本的学生需要什么证件和流程?</a></td>
	</tr>
	<tr>
	<td class="cat"><a href="">[奥运]</a></td>
	<td><a href="">	2008奥运会跳水项目在哪进行？</a></td>
	</tr>
	<!-- 结帖////////////////////////////////////////// -->
	<tr>
	<th class="txtl">最近结束</th>
	<th class="txtr" colspan="2">更多&raquo;</th>
	</tr>
	<tr>
	<td class="cat"><a href="">[反病毒]</a></td>
	<td><a href="">个人电脑装什么防火墙和杀毒软件好啊</a></td>
	</tr>
	<tr>
	<td class="cat"><a href="">[人际交往]</a></td>
	<td><a href="">如何处理好人际关系？</a></td>
	</tr>
	<tr>
	<td class="cat"><a href="">[节日假期]</a></td>
	<td><a href="">如何提倡国人文明扫墓？</a></td>
	</tr>
	<tr>
	<td class="cat"><a href="">[留学移民]</a></td>
	<td><a href="">办日本的学生需要什么证件和流程?</a></td>
	</tr>
	<tr>
	<td class="cat"><a href="">[奥运]</a></td>
	<td><a href="">	2008奥运会跳水项目在哪进行？</a></td>
	</tr>
</table>
</div>

<div class="sidebar">

<!-- 帮助+公告 ///////////////////////////////////////////// -->
<div class="box">
<a href="" class="help_link">帮助</a>
<a href="" class="help_rule">规则</a>
</div>
<a href="" class="need_help">需要帮助</a>

<!-- 积分排行 ////////////////////////////////////////////// -->
<table class="help_rank">
<tr>
<th class="txtl" colspan="2">总积分榜</th>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td>100</td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td>100</td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td>100</td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td>100</td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td>100</td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td>100</td>
</tr>
</table>
<!-- 踊跃 ///////////////////////////////// -->
<table class="help_rank">
<tr>
<th class="txtl" colspan="2">活跃排行</th>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td>100</td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td>100</td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td>100</td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td>100</td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td>100</td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td>100</td>
</tr>
</table>
</div>

<script>
function show_notice()
{
	var notice_num = parseInt($('.help_notice a').length);
	var show_num = parseInt($('.help_notice').attr('start'));
	$('.help_notice a').hide();
	$('.help_notice a:eq('+(show_num-1)+')').show('slow');
	show_num++;
	if(show_num > notice_num) 
	{
		show_num = 1;
	}
	$('.help_notice').attr('start',show_num);
}
var t = setInterval("show_notice()",4000);

$('.help_rank').each(function(i)
{ 
	$('.help_rank:eq('+i+') a.rank').each(function(j)
	{ 
		$(this).css('background','url(/static/images/icon/rank/n'+(j+1)+'.jpg) no-repeat left center');
	}); 
});
</script>

