<!-- 互助所在分类 /////////////////////////////////// -->
<div id="help_position">
<a href="">校友互助</a> / <a href="">电脑网络</a> / 反病毒
</div>

<!-- 互助分类 -->
<div class="sidebar">
<?= $this->render('help-category.phtml') ?>
</div>

<!-- 中间位置 ////////////////////////////////////////////////////////// -->
<div class="sidebar">
<!-- 互助广播 -->
<div class="sub_category">
<h2>电脑网络</h2>
<table>
<tr>
<td><a href="">互联网<small>(316824)</small></a></td>
<td><a href="">电脑常识<small>(333400)</small></a></td>
<td><a href="">操作系统<small>(271022)</small></a></td>
<td><a href="">硬件<small>(178574)</small></a></td>
</tr>
<tr>
<td><a href="">软件<small>(284135)</small></a></td>
<td>反病毒<small>(146205)</small></td>
<td><a href="">编程<small>(80860)</small></a></td>
<td><a href="">多媒体<small>(299721)</small></a></td>
</tr>
<tr>
<td><a href="">资源共享<small>(81877)</small></a></td>
<td><a href="">网页制作<small>(73929)</small></a></td>
<td></td>
<td></td>
</tr>
</table>
</div>

<!-- 问题集合TAB /////////////////////////////////////////////////////// -->
<table>
<tr>
<th id="help_tab_btn">
<a href="javascript:showTab(0)">待解决的问题</a>
<a href="javascript:showTab(1)">已经解决的问题</a>
<a href="javascript:showTab(2)">被遗忘的问题</a>
</th>
</tr>
<tr>
<td>
<table class="tab_content">
<tr>
<td><a href="">QQ登录器中木马怎么处理</a> <img src="/static/images/icon/coin.gif" />120</td>
<td class="date">1小时前</td>
</tr>
<tr>
<td><a href="">恢复u盘实际大小</a></td>
<td class="date">21小时前</td>
</tr>
</table>


<table class="tab_content">
<tr>
<td><a href="">QQ登录器中木马怎么处理2</a> <img src="/static/images/icon/coin.gif" />120</td>
<td class="date">1小时前</td>
</tr>
<tr>
<td><a href="">恢复u盘实际大小</a></td>
<td class="date">21小时前</td>
</tr>
</table>


<table class="tab_content">
<tr>
<td><a href="">QQ登录器中木马怎么处理3</a> <img src="/static/images/icon/coin.gif" />120</td>
<td class="date">1小时前</td>
</tr>
<tr>
<td><a href="">恢复u盘实际大小</a></td>
<td class="date">21小时前</td>
</tr>
</table>
</td>
</table>

<div class="pagination"><a href="">上一页</a> <a href="">1</a> <a href="">2</a>  <b>3</b> <a href="">下一页</a></div>
</div>

<!-- 积分排行 ////////////////////////////////////////////// -->
<div class="sidebar">
<table class="help_rank">
<tr>
<th class="txtl" colspan="2">电脑网络行家</th>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td></td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td></td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td></td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td></td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td></td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td></td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td></td>
</tr>
<tr>
<td><a href="" class="rank">求职上boleme</a></td>
<td></td>
</tr>
</table>
</div>
<script>
$('.help_rank').each(function(i)
{ 
	$('.help_rank:eq('+i+') a.rank').each(function(j)
	{ 
		$(this).css('background','url(/static/images/icon/rank/n'+(j+1)+'.jpg) no-repeat left center');
	}); 
});
showTab(0)
</script>