<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
<meta http-equiv="Content-Language" content="zh-CN" >
<title>会员注册</title>
<meta name="keywords" content="">
<meta name="description" content="">
<link rel="stylesheet" type="text/css" href="/static/styles/member.css">
<script language="javascript" type="text/javascript" src="/static/scripts/jquery.js"></script>
<script language="javascript" type="text/javascript" src="/static/scripts/common.js"></script>
<script language="javascript" type="text/javascript" src="/static/scripts/member/register.js"></script>
</head>

<body>
<div id="ajaxloading"></div>
<div id="login">
    <div><a href="/" id="logo"><b>zjuhz.com</b><p>杭州浙江大学校友会</p></a></div>

    <form name="frmRegister" id="frmRegister" method="post">
    <div class="reg_tit"><a href="/member/">会员中心</a> >> 会员注册</div>	
	<div class="zc">
	<ul>	
      <li class="msg" style="margin-top:10px;">如果您已经是本站会员，可以使用已有的账号直接 <a href="/member/login/">登录</a></li>
	
	  <li><span class="reg_tda">登录帐号：</span><input style="margin-left:48px;" name="uname"  autocomplete="off" class="user_txt" type="text" maxlength="16" value="" /><input type="button" value="检查帐号是否可用"><li class="ligray">3-16位的字母、数字、下划线</li>
	
      <li><span class="reg_tda">设置密码：</span><input style="margin-left:48px;" name="pswd"  autocomplete="off" class="user_txt" type="password" maxlength="16" value="" /></li><li class="ligray">6-16位的任意字符，不区分大小写</li>
	
      <li><span class="reg_tda">密码确认：</span><input style="margin-left:48px;" name="repswd" autocomplete="off" class="user_txt" type="password" maxlength="16" value="" /></li><li class="ligray">请再次输入密码以确认</li>	
	
      <li><span class="reg_tda">真实姓名：</span><input style="margin-left:48px;" name="rname" autocomplete="off" class="user_txt" type="text" maxlength="20" /></li><li class="ligray">至少2位以上，且不能含有数字和符号</li>
	
      <li><span class="reg_tda">性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：</span><input  style="margin-left:48px;" name="sex" type="radio" value="M" checked="checked" /> 男 <input type="radio" name="sex" value="F" /> 女</li>	
	
	  <li><span class="reg_tda">附&nbsp;&nbsp;加&nbsp;&nbsp;码：</span><input  style="margin-left:46px;width:102px;" type="text" class="user_txt" name="vcode" autocomplete="off" maxlength="4"><a href="javascript:verify('verify','/member/index/verify/')"><img id="verify" src="/member/index/verify/" border="0" /></a></li><li class="ligray" style="padding-bottom:0px;">请输入上图中的数字，<a href="javascript:verify('verify','/member/index/verify/')">看不清楚？</a></li>
	
      <li><span class="reg_tda"><p></p></span><input type="submit" id="btnSubmit" name="btnSubmit" value="同意以下服务条款，提交注册信息" /></li>

      <li><div id="ajaxhint"></div></li>
	</ul>
	</div>
	<input type="hidden" name="ikey" value="<?php echo $this->ikey; ?>" />

	</form>

	<div id="footer">
		<p><a href="">帮助</a> | <a href="">关于</a> | <a href="">客服</a> | <a href="">隐私声明</a></p>
		<p><span style="float:right; margin-top:-23px;">杭州浙江大学校友会(筹) &copy; 2008 
		<a href="http://www.miibeian.gov.cn" target="_blank">浙ICP备06052510号</a></span></p>
	</div>
</div>
</body>

</html>
