<div class="container" style="width:480px">
<h4 class="quiet">班级公告编辑
<small id="notice_result" style="font-size:12px; font-weight:normal;color:orange"></small></h2>
<textarea id="class_notice_content" class="inputtxt" style="width:99%;height:100px;">
<?= stripslashes($this->content) ?>
</textarea>
<p class="txtr">
<button onclick="modClassNotice(<?= $this->class_id ?>,1)" class="btn">保存修改</button>
</p>
</div>