<div style="overflow:hidden">
<h2 style="font-size:14px; color:#666">加入班级申请
<small id="apply_result" style="font-size:12px; font-weight:normal;color:orange"></small></h2>
<textarea id="class_apply_content" class="inputtxt" style="width:360px; height:100px;"></textarea>
<button onclick="classJoinApply(<?= $this->class_id ?>)" class="btn" style="float:right; margin:10px 20px 0 0;">提交申请</button>
</div>