

<div class="sidebar" style="padding:20px;">
<a href="javascript:ucard(1)">22222</a>
<a href="javascript:ucard(2)">33333</a>
<a href="javascript:ucard(3)">44444</a>
<a href="javascript:ucard(4)">44444</a>
<a href="javascript:ucard(5)">44444</a>
</div>

<script type="text/javascript">

	function ucard(id)
	{
		return false;
	}
	function ucardInit()
	{
		$('a[href^="javascript:ucard"]').bind('mouseover',function(){
			$('.cardContainer').remove();
			var id = $(this).attr('href');
			id = id.replace('javascript:ucard(','');
			id = parseInt(id.replace(')',''));
			var x = $(this).offset().left;
			var y = $(this).offset().top+20;
			var w = $('body').width();
			var h = $('body').height();
			var card_w = 200;
			$(this).after('<div class="cardContainer">加载个人信息...</div>');
			$('.cardContainer').css({border:'1px solid #ccc', opacity:'0.9', position:'absolute', width:card_w, top:y, background:'#f5f5f5'});
			if((card_w+x) > w)
			{
				x = x-card_w;
			}
			$('.cardContainer').css({left:x});
			$('.cardContainer').load('/temp/card/load?id='+id);
		});
	}
	ucardInit();
</script>