<style>
<!--
	#ucard { margin:10px; }
	#ucard u{ text-decoration:none; border-bottom:1px solid #666; }
-->
</style>
<p><img style="cursor:pointer;" src="/static/images/icon/close.gif" onclick="$('.cardContainer').remove()" /></p>
<table id="ucard">
<tr>
	<td valign="top"><img src="/static/images/default-face.jpg" /></td>
	<td style="padding:0 0 0 10px" valign="bottom">
		<p>性别：<u>男</u></p>
		<p>最后登录：<u>3天前</u></p>
		<p>入学年份：<u>2006</u></p>
		<p>所在学院：<u>外国语言文化与国际交流学院</u></p>
	</td>
</tr>
</table>