<div class="span-7 mgu10 last">
    <div class="sideBar pdd10">
        <ul class="mglf10">
            <h3>活动</h3>
            <li><a href="/info/?category=9">暑期走访校友行 <img src="/static/images/icon/new.gif" /></a></li>
            <li><a target="_blank" href="http://www.zju.zj.cn/Details/DongTaiDetail_532.html">“心系灾区，大爱无垠”——浙江大学企业家经理人高级研修班爱心捐款</a></li>
        </ul>
    </div>
</div>

<div class="span-7 mgu10 last">
    <div class="sideBar pdd10">     
        <ul class="mglf10">
            <h3>专题</h3>
            <li><a target="_blank" href="http://www.zjuhz.com/info/view/detail/id/186">杭州校友会筹备工作一览<img src="/static/images/icon/new.gif" /></a></li>
            <li><a href="/info/subject/index/of/qiushixungen-jiangxi">浙江大学求是寻根 - 江西段</a></li>
        </ul>
    </div>
</div>
            
<div class="span-7 mgu10 last">
    <div class="sideBar pdd10">     
        <ul class="mglf10">
            <h3>网站进度</h3>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组个人资料开通</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组在线校友统计</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组互访记录</li>
            <li><?= Cmd::icon('plugin_add.png') ?> 群组角色字定义，成员任命、踢出</li>
            <li><?= Cmd::icon('bug_delete.png') ?> 修复修改群组基础信息后无法加入群组</li>
        </ul>
    </div>
</div>