<div id="main">
	<div class="sidebar">
		<div class="info_category">
			<h2>信息中心</h2>
			<dl>
				<?php if($this->categories): foreach ($this->categories as $cate): ?>
				<dd>
				<a href="?category=<?= $cate->category_id ?>"<?php if($this->categoryId == $cate->category_id) echo ' style="background:#D9E6F7"' ?>>
				<img border="0" src="/static/images/icon/<?= $cate->category_icon ?>.gif" />
				<?= $cate->category_name ?></a>
				</dd>
				<?php endforeach; endif; ?>
			</dl>
		</div>
	</div>
	
	<table class="sidebar entity_list" cellspacing="0">
		<tr>
			<th width="70%">标题 <small> <?= $this->numrows ?>篇 , <?= $this->numpages ?>页</small></th>
			<th width="20%">发布时间</th>
			<th width="10%">浏览</th>
		</tr>
		<?php if(!count($this->rows)): ?>
		<tr><td colspan="3">该类尚未发布任何信息</td></tr>
		<?php else: foreach ($this->rows as $row): ?>
		<tr class="entity_row">
			<td style="font-size:14px">
				<img src="/static/images/bullet/green.gif" align="absmiddle" /> 
				<a href="/info/view/detail/id/<?= $row->entity_id ?>"><?= $row->entity_title ?></a>
			</td>
			<td style="font-size:10px"><?= Commons::date($row->entity_pub_time) ?></td>
			<td style="font-size:10px"><?= $row->entity_view_num ?></td>
		</tr>
		<?php endforeach; endif; ?>
		<tr>
		<td colspan="3"><div class="pagination"><?= $this->pagination ?></div></td>
		</tr>
	</table>
	
	
</div>



<script>
$('.entity_row').mouseover(function(){ $('td',this).css('background','#fff') });
$('.entity_row').mouseout(function(){ $('td',this).css('background','#f5f5f5') });
</script>