<div class="span-4">
	<div class="sideBar pdd10">
		<h3 class="mg10">资讯中心</h3>
		<ul>
			<?php if($this->categories): foreach ($this->categories as $cate): ?>
			<li class="mglf10">
			<a class="disblock pd3" href="?category=<?= $cate->category_id ?>"<?php if($this->categoryId == $cate->category_id) echo ' style="background:#F7F4E5"' ?>>
			<img border="0" src="/static/images/icon/<?= $cate->category_icon ?>.gif" />
			<?= $cate->category_name ?></a>
			</li>
			<?php endforeach; endif; ?>
		</ul>
	</div>
</div>

<div class="span-20 last">
	<table class="table-1" cellspacing="0" width="100%">
		<tr>
			<th width="70%">
				<strong class="f14"><?= Cmd::getCateName($this->categoryId) ?></strong> 共：
				<small> <?= $this->numrows ?>篇 , 
				<?= $this->numpages ?>页</small>
			</th>
			<th width="20%">发布时间</th>
			<th width="10%" class="txtc">点击数</th>
		</tr>
		<?php if(!count($this->rows)): ?>
		<tr><td colspan="3">该类尚未发布任何信息</td></tr>
		<?php else: foreach ($this->rows as $k => $v): ?>
		<tr>
			<td class="pd5 f14 dashBorder">
				<?php if($v['entity_top'] == 1): ?>
				<img src="/static/images/bullet/red.gif" align="absmiddle" /> 
				<?php else : ?>
				<img src="/static/images/bullet/green.gif" align="absmiddle" /> 
				<?php endif; ?>
				<a href="/info/view/detail/id/<?= $v['entity_id'] ?>"><?= $v['entity_title'] ?></a>
				<?php if(time()-$v['entity_pub_time'] < (12*3600)): ?>
				<img src="/static/images/icon/new.gif" />
				<?php endif; ?>
			</td>
			<td class="f12 dashBorder"><?= Lp_Date::timespan($v['entity_pub_time']) ?>前</td>
			<td class="f12 dashBorder txtc"><?= $v['entity_view_num'] ?></td>
		</tr>
		<?php endforeach; endif; ?>
	</table>
	<div class="pagination"><?= $this->pagination ?></div>
</div>
	
	
