<style type="text/css">
	.info_category{
		width:150px;
		background: url(/static/images/bg/category.jpg) no-repeat left top;
		margin-top:18px;
	}
	.info_category h2{
		padding:8px 0 3px 40px;
		font-size:14px;
		background:url(/static/images/icon/book_open.gif) no-repeat 15px 8px;
		color:#263F5B;
	}
	.info_category dl{
		margin:5px 5px 0 5px;
		background:#EFF7FF;
		border-left:1px solid #D9E6F7;
		border-right:1px solid #D9E6F7;
		border-bottom:2px solid #AFCAEF;
		padding:1px;
	}
	.info_category dd{
		height:25px;
		border-bottom:1px solid #D9E6F7;
		overflow:hidden;
	}
	.info_category dd a{
		display:block;
		padding:3px 0 3px 5px;
		text-decoration:none;
		font-size:12px;
		color:#314973;
		margin-top:1px;
	}
	.info_category dd a:hover{
		background:#D9E6F7
	}
	.info_category dd img{
		border:none;
		margin-right:5px;
	}
	
	.entity_list{
		margin:20px 0 0 15px;
		width:600px;
		padding-right:2px;
		background:#f5f5f5;
	}
	
	.entity_list th{
		font-size:13px;
		text-align:left;
		padding:4px 0 3px 10px;
		border-left:2px solid #f5f5f5;
		border-top:2px solid #f5f5f5;
		background:#999;
	}
	.entity_list td{
		padding:10px 0 3px 10px;
		border-bottom:1px dashed #ccc;
		background:#f5f5f5;
	}
</style>
<div id="main" style="height:500px;">
	<div class="sub_bar" style="width:150px;">
		<div class="info_category">
			<h2>信息中心</h2>
			<dl>
				<?php if($this->categories): foreach ($this->categories as $cate): ?>
				<dd>
				<a href="?category=<?php echo $cate->category_id ?>"<?php if($this->category_id == $cate->category_id) echo ' style="background:#D9E6F7"' ?>>
				<img border="0" src="/static/images/icon/<?php echo $cate->category_icon ?>.gif" />
				<?php echo $cate->category_name ?></a>
				</dd>
				<?php endforeach; endif; ?>
			</dl>
		</div>
	</div>
	
	<table class="sub_bar entity_list" cellspacing="0">
		<tr>
			<th width="70%">标题</th>
			<th width="20%">发布时间</th>
			<th width="10%">浏览</th>
		</tr>
		<?php if(!count($this->rows)): ?>
		<tr><td colspan="3">该类尚未发布任何信息</td></tr>
		<?php else: foreach ($this->rows as $row): ?>
		<tr class="entity_row">
			<td style="font-size:14px"><?php echo $row->entity_title ?></td>
			<td style="font-size:10px"><?php echo Commons::date($row->entity_pub_time) ?></td>
			<td style="font-size:10px"><?php echo $row->entity_view_num ?></td>
		</tr>
		<?php endforeach; endif; ?>
	</table>
</div>

<div id="news_list_tt">&nbsp;</div>

<script>
$('.entity_row').mouseover(function(){ $('td',this).css('background','#EFF7FF') });
$('.entity_row').mouseout(function(){ $('td',this).css('background','#f5f5f5') });
</script>