<div class="sidebar">
<!-- 互助分类 -->
<?= $this->render('dynamic/sort.phtml'); ?>
</div>

<div class="sidebar">

<!-- 搜索结果 -->
<table class="help_set_large">

    <!-- 结果概括 -->
	<tr>
	<th colspan="2" class="txtl">有  <?= $this->total; ?> 项符合 <?= $this->wd; ?> 的搜索结果</th>
	</tr>

    <!-- 结果显示 -->	
	<?php foreach ($this->searchList as $value) { ?>
	<tr>
	<td><a href="/help/question/detail/qid/<?= $value['qid']; ?>/"><?= Commons::highlight($this->wd, $value['title']); ?></a> <img src="/static/images/icon/icn_status_<?= $value['status']; ?>.gif"> <span class="f9"><?php if ($value['offer'] > 0 ) { ?><img src="/static/images/icon/icn_offer.gif" title="积分悬赏"><?= $value['offer']; } ?></span> <a class="collection" id="collection" title="收藏该问题" onclick="javascript:collection_insert(<?= $value['qid']; ?>);">收藏</a></td>
	</tr>
	<tr>
	  <td><?= Commons::highlight($this->wd, strip_tags($value['content'])); ?></td>
    </tr>
	<tr>
	  <td><?= $value['realName']; ?> <?= date('Y-m-d H:i', strtotime($value['addTime'])); ?><br /><br /></td>
    </tr>
	<?php } ?>
	
</table>

<table align="center">

	<tr>
	<td><?= $this->paging; ?></td>
	</tr>
	
</table>
</div>
