<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
<meta http-equiv="Content-Language" content="zh-CN" >
<title>会员中心首页 - 杭州浙江大学校友会 - zjuhz.com</title>
<meta name="keywords" content="">
<meta name="description" content="">
<script language="javascript" type="text/javascript" src="/static/scripts/jquery.js"></script>
<script language="javascript" type="text/javascript" src="/static/scripts/common.js"></script>
<script language="javascript" type="text/javascript" src="/static/scripts/member/member.js"></script>
<script language="javascript" type="text/javascript" src="/static/scripts/member/index/index.js"></script>
<link rel="stylesheet" type="text/css" href="/static/styles/common.css">
<link rel="stylesheet" type="text/css" href="/static/styles/member.css">
</head>

<body>
<div id="ajaxhint" style="width:190px"></div>
<form name="frmLogin" id="frmLogin" method="post">
<table class="login">
<tbody>	  
<tr>
<td>账&nbsp; 号:</td>
<td><input class="logininput" id="uname" maxlength="16" name="uname" value="<?php echo $this->uname; ?>" /></td>
</tr>
<tr>
<td>密&nbsp; 码:</td>
<td><input name="pswd" type="password" class="logininput" id="pswd" maxlength="16" /></td>
</tr>
<tr>
<td>&nbsp;</td>
<td class="cookie"><input id="alive" type="checkbox" checked="checked" value="0" name="alive" />
<label for="rememberme">记住我的账号</label></td>
</tr>
<tr>
<td>&nbsp;</td>
<td><input class="s_button" type="submit" value=" 登 录 " id="btnSubmit" name="btnSubmit" /></td>
</tr>			
</tbody>
</table>
</FORM>

</body>

</html>