<?= $this->render('home/index.phtml'); ?>

<div class="sidebar" style="width:160px">
<!-- 管理条目 ///////////////////////////////////// -->
<p class="toolbar">
<a href=""><img src="/static/images/icon/user.gif" /> 邀请加入</a>
<a href=""><img src="/static/images/icon/email.gif" /> 群发邮件</a>
<a href=""><img src="/static/images/icon/book.gif" /> 班级通讯录</a>
</p>
</div>

<!-- 信息显示区 //////////////////////////////////////  -->
<div class="sidebar class_show" style="width:500px; margin:0 10px">
<h2 class="quiet"><img src="/static/images/icon/layers.gif" /> 班级黑板报</h2>
<div id="class_notice">
<?= stripcslashes($this->class_base_info['class_notice']) ?>
</div>


<h2 class="quiet"><img src="/static/images/icon/picture.gif" /> 班级相册</h2>
<div id="class_picture">尚未开放..</div>

<h2 class="quiet"><img src="/static/images/icon/comments.gif" /> 班级讨论</h2>
<div id="class_comments"></div>
</div>


<!-- 班级基本信息 ///////////////////////////////////////// -->
<?= $this->render('home/baseinfo.phtml'); ?>