<script type="text/javascript" src="/static/scripts/help/help.js"></script>
<?php
	echo $this->headScript()->appendFile("/static/scripts/{$this->header['modelName']}/{$this->request->getControllerName()}/{$this->request->getActionName()}.js");
?>
<link href="/static/styles/help.css" media="screen" rel="stylesheet" type="text/css" />
<?php
	$this->headTitle()->setSeparator(' - ');
	echo $this->headTitle('校友互助 - 杭州浙江大学校友会 [ zjuhz.com ]','append');
?>