<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link rel="stylesheet" type="text/css" href="/static/styles/info/screen.css" media="screen" />
<link rel="stylesheet" type="text/css" href="/static/styles/info/print.css" media="print" />
<script type="text/javascript" src="/static/scripts/jquery.js"></script>
<script type="text/javascript" src="/static/scripts/jquery.pngFix.pack.js"></script>
<script type="text/javascript" src="/static/scripts/common.js"></script>
<script type="text/javascript" src="/static/scripts/info/action.js"></script>
<script type="text/javascript" src="/static/scripts/thickbox-compressed.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="zh-CN" />
<?php $this->headTitle('新闻资讯_杭州浙江大学校友会')->setSeparator('_'); ?>
<?= $this->headTitle(); ?>
</head>

<body style="background:url(/static/images/bg/2009.jpg) repeat-x left top">
	<div id="header" class="container">
		<div class="span-11">
			<a href="/"><img src="/static/images/group/2009zjuhz.jpg" alt="新闻资讯" /></a>
		</div>
		<div class="span-13 last">
			<div id="passport" class="hrefspan-8 push-1 last">
				<?php if ($this->passport()): ?>
				<span style="color:#fff">您好！<?= $this->passport('realName') ?> </span>
                <a style="color:#ffc" href="javascript:fastInvite()">邀请校友</a> 
                <a style="color:#ffc" target="_blank" href="/chat/">聊天室</a> 
				<a style="color:#ffc" href="/member/my/">我的账号</a> 
				<span style="color:#fff">资讯积分(<?= $this->coin(Cmd::myid()) ?>) </span>
				<a style="color:#ffc" href="/info/admin">投稿</a> 
				<a style="color:#ffc" href="/member/logout/" onClick="return window.confirm('确实要退出吗？');">退出</a>
				<?php else: ?>
				<a style="color:#ffc" href="/member/register/">注册</a>
				<a style="color:#ffc" href="/member/login/">登录</a>
                <a style="color:#ffc" href="/home/passport/find">找回密码</a>
				<?php endif; ?>
			</div>
			<div class="global-nav span-13 last hrefspan-8">
                <a href="/biz/">创业</a>
				<a href="/member/">校友</a>
				<a href="/info/" class="here">资讯</a>
				<a href="/help/">互助</a>
				<a href="/class/">班级</a>
				<a href="/group/">群组</a>
				<a href="/group/events/list">活动</a>
			</div>
		</div>
		
		<div class="sub-nav span-13 last">
			<form method="POST" action="/info/search/look/">
			<input name="for" class="text" type="text" value="<?= $this->escape($this->keywords) ?>" />
			<input class="btn" type="submit" value="资讯搜索" /> 
			</form>
		</div>
		
	</div>
	<div id="container" class="container">
		<span id="top_tip"></span>
		<?= $this->layout()->sidebar; ?>
		<?= $this->layout()->content; ?>
	</div>
	
	<div id="footer" class="container txtc hrefspan-8 pd10">
		<hr />
		<a href="/info/support/help">帮助</a>
		<a style="color:red" target="_blank" href="http://v2.zjuhz.com/public/index/doc/of/aboutus">关于本会</a>
		<a target="_blank" href="http://v2.zjuhz.com/addon_partners/list">赞助单位</a>
		<a href="/info/support/contact_us">联系我们</a>
		<a href="/info/support/privacy_claim">隐私声明</a>
		<a href="http://www.zjuhz.com/old" target="_blank">旧版回顾</a>
		<a href="http://ourzju.uu1001.com" target="_blank">校友论坛</a>
		<a href="http://www.miibeian.gov.cn" target="_blank">浙ICP备08109401号</a>
		杭州浙江大学校友会&copy;2008
		<script type="text/javascript" src="http://js.tongji.cn.yahoo.com/705170/ystat.js"></script><noscript><a href="http://tongji.cn.yahoo.com"><img src="http://img.tongji.cn.yahoo.com/705170/ystat.gif"/></a></noscript>
	</div>
	<hr class="space" />
	<script type="text/javascript">
		$(document).ready(function(){
			$('.btn').hover(
				function(){$(this).css('background','#FFFF99')},
				function(){$(this).css('background','#D4D0C8')}
			);
			$('img[src$="png"]').parent().pngFix(); 
			var controller = $('div.sub-nav').attr('rel');
			$('div.sub-nav a[href*="'+controller+'"]').addClass('here');
			$('input[type="text"]').focus(function(){
				$(this).css('border','1px solid #666');
			});
			$('input[type="text"]').blur(function(){
				$(this).css('border','1px solid #bbb');
			});
            $('.table-1 td').parent().hover(
                function(){$(this).css('background','#F9FBFA')},
				function(){$(this).css('background','#FFFFFF')}
            );
			$('#top_tip').load('/group/index/toptip?gid=<?= $this->gid ?>');
		});
		function notip()
		{
			$('#top_tip').load('/group/index/toptip?close=1',null,function(){
				$('#top_tip').remove();	
			});
		}
	</script>
</body>
</html>