<?php echo "{$this->Doctype('XHTML1_TRANSITIONAL')}\n"; //HTML文档类型 ?>
<html>
<head>
<?php 
//HEAD区域附加信息 <title> <meta> <script> <style> <link>
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                 ->appendHttpEquiv('Content-Language', 'zh-CN');
$this->headScript()->appendFile('/static/scripts/jquery.js')->appendFile('/static/scripts/common.js');
$this->headTitle('杭州浙江大学校友会 [ zjuhz.com ]','append'); $this->headTitle()->setSeparator(' - ');
echo $this->headTitle().$this->headMeta().$this->headScript().$this->headStyle().$this->headLink();
?>
</head>
<body>
<div id="wrap">

<table class="rc">
<tr><td class="rc_tl"></td><td class="rc_tr"></td></tr>
</table>

<table id="header">
<tr>
<td id="logo" title="杭州浙江大学校友会欢迎您 - zjuhz.com" onclick="location.href='/'">
	<i>zjuhz.com</i>
	<p>杭州浙江大学校友会</p>
</td>
<td>
<table id="global_search">
	<tr>
	<td class="models">
		<?php 
		// 根据用户是否登陆来判断显示的模块连接
		echo $this->partial("partial/{$this->role}-model.phtml", $this->header) ?>
	</td>
	<td class="nav">
		<?php 
		// 显示用户当前的状态(登陆/登出/各便捷连接)
		echo $this->partial("partial/{$this->role}-nav.phtml", $this->account_info) ?>
	</td>
	</tr>
	<tr>
	<td class="search_form" colspan="2">
		<?php 
		// 不同模块显示不通的搜索条
		echo $this->partial("partial/global-search.phtml", $this->header) ?>
	</td>
	</tr>
</table>
</td>
</tr>
</table>
<?php 
//Script主体内容
echo $this->layout()->content;

if(!$this->footer)
$this->footer = 'global';
echo $this->partial("partial/{$this->footer}-footer.phtml");
?>

<table class="rc">
<tr><td class="rc_bl"></td><td class="rc_br"></td></tr>
</table>
</div>
</body>
</html>