<script type="text/javascript" src="/static/scripts/member/member.js"></script>
<?php
if (!$this->disableCtrlScript) {
	echo $this->headScript()->appendFile("/static/scripts/{$this->header['modelName']}/{$this->request->getControllerName()}/{$this->request->getActionName()}.js");
}
?>
<link href="/static/styles/member.css" media="screen" rel="stylesheet" type="text/css" />
<?php
	$this->headTitle()->setSeparator(' - ');
	echo $this->headTitle('会员中心 - 杭州浙江大学校友会 [ zjuhz.com ]','append');
?>