<?php 

// 分配title
$this->headTitle($this->escape($this->entity['entity_title']));
// 分配 meta 关键字
$this->headMeta()->appendName('keywords', $this->escape($this->entity['entity_tag']));
?>

<div id="global_pos">
<img src="/static/images/icon/newspaper.gif" />
<a href="/info/">信息资讯</a> / 
<a href="/info/?category=<?= $this->escape($this->entity['category_id']) ?>"><?= $this->escape($this->entity['category_name']) ?></a> / 
<?= $this->escape($this->entity['entity_title']) ?> 
</div>

<div class="sidebar">

<!-- 标题 ////////////////////////////////////////////// -->
<?php if(!$this->entity): ?>
<h2 class="entity_none">您所请求的信息不存在!</h2>
<?php else: ?>
<h2 class="print entity_title">
<?= $this->escape($this->entity['entity_title']) ?>
</h2>


<!-- 主体 ////////////////////////////////////////////// -->
<div class="print entity">
<?php if($this->entity['entity_private'] == 1 && $this->role != 'member'): ?>
<p class="err_message">您需要登录后才能阅读这篇文章。</p>
<?php else: ?>
<?= stripslashes($this->entity['entity_content']) ?>
<?php endif; ?>
<p id="maker">
发布人:<?= $this->entity['user_name'] ?>(<?= $this->entity['role_nickname'] ?>)<br />
发布于:<?= Commons::date($this->entity['entity_pub_time']) ?>
<?php if($this->entity['entity_mod_time']): ?>
<br />最后修改于:<?= Commons::date($this->entity['entity_mod_time']) ?>
<?php endif; ?>
</p>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('.entity img').each(function(){
			$(this).width('auto');
			$(this).height('auto');
		});
		
		var t = window.setInterval(function(){
			$('.entity img').each(function(){
				if($(this).width()>780)
				{
					$(this).width(780);
				}
			});
		},1000);
	});
</script>

<!-- 同类上下篇 ////////////////////////////////////////////// -->
<table width="100%">
<tr>
<?php if($this->sibling['previous']): ?>
<td class="sibling_previous"><img src="/static/images/icon/previous.gif" /> 
<a href="/info/view/detail/id/<?= $this->escape($this->sibling['previous']['entity_id']) ?>">
<?= $this->escape($this->sibling['previous']['entity_title']) ?></a>
</td>
<?php endif; ?>

<?php if($this->sibling['next']): ?>
<td class="sibling_next">
<a href="/info/view/detail/id/<?= $this->escape($this->sibling['next']['entity_id']) ?>">
<?= $this->escape($this->sibling['next']['entity_title']) ?></a> 
<img src="/static/images/icon/next.gif" /> 
</td>
<?php endif; ?>
</tr>
</table>

<!-- 工具栏 ////////////////////////////////////////////// -->
<p class="toolbar">
已被阅读(<?= $this->entity['entity_view_num'] ?>)&nbsp;&nbsp;&nbsp;
<?php if($this->tag): ?>本文标签: 
<?php foreach ($this->tag as $k => $v): ?>
<a href="/info/search/look/for/<?= urlencode($this->escape($v)) ?>"><?= $this->escape($v) ?></a>
<?php endforeach; endif; ?>&nbsp;&nbsp;&nbsp;
<img src="/static/images/icon/top.gif" style="cursor:pointer" onclick="javascript:scroll(0,0)" align="absmiddle" />&nbsp;&nbsp;&nbsp;
<img style="cursor: pointer;" src="/static/images/icon/printer.gif" alt="打印" onclick="window.print()" align="absmiddle">
</p>


<div id="sub_container">
	<!-- 相关文章 ////////////////////////////////////////////// -->
	<table class="similarity" style="float:left">
	<tr><th colspan="2">:: 相关文章 ::</th></tr>
	<?php if(!$this->similarity): ?>
	<tr><td colspan="2">没有找到</td></tr>
	<?php else: foreach ($this->similarity as $k2 => $v2): ?>
	<tr>
	<td class="f12"><a href="/info/view/detail/id/<?= $v2['entity_id'] ?>"><?= $this->escape($v2['entity_title']) ?></a></td>
	<td class="f9"><?= Commons::date($v2['entity_pub_time']) ?></td>
	</tr>
	<?php endforeach; endif; ?>
	</table>
	<table class="similarity" style="float:right">
	<tr><th colspan="2">:: <a href="javascript:toggle()" id="toggleBtn">查看评论</a> :: 
	<a href="javascript:commentForm(<?= $this->entity['entity_id'] ?>)">发表评论</a></th></tr>
	<tr>
		<?php if($this->entity['entity_private'] == 1 && $this->role != 'member'): ?>
		<td>需要登陆后才能查看评论</td>
		<?php else: ?>
		<td id="commentList" class="hide"></td>
		<?php endif; ?>
	</tr>
	</table>
</div>

<?php endif; ?>
</div>

<script type="text/javascript">
	function toggle()
	{
		if($('#toggleBtn').text() == '查看评论')
		{
			$('#toggleBtn').text('隐藏评论');
			$('#commentList').show();
		}
		else
		{
			$('#toggleBtn').text('查看评论');
			$('#commentList').hide();
		}
	}
	function commentView(entity_id, page)
	{
		$.post('/info/comment/view', {entity_id:entity_id, page:page}, function(html){
			$('#commentList').html(html);
		});
	}
	
	function commentForm(entity_id)
	{
		$.post('/info/comment/form', {entity_id:entity_id}, function(html){
			$.facebox(html);
		});
	}
	
	commentView(<?= $this->entity['entity_id'] ?>,1);
	toggle();
</script>
