<!-- 边栏 //////////////////////////////////////////// -->
    <div class="span-5">
        <div class="sideBar mgu10">
            <?= $this->managebar($this->gid, $this->controller_name) ?>
        </div>
        <div class="sideBar mgu10">
            <?= $this->groupbar($this->groupInfo) ?>
        </div>
        <div class="sideBar mgu10">
            <?= $this->clickbar($this->groupInfo) ?>
        </div>
    </div>